package com.dhanantry.scapeandrunparasites.client.model.entity.primitive;

import com.dhanantry.scapeandrunparasites.client.legacy.ModelRenderer;
import com.dhanantry.scapeandrunparasites.client.model.ModelSRP;
import com.dhanantry.scapeandrunparasites.entity.ai.misc.EntityParasiteBase;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.Entity;

public class ModelCanra
extends ModelSRP {
    public ModelRenderer mainbody;
    public ModelRenderer body;
    public ModelRenderer jointBLLX;
    public ModelRenderer jointFLLX;
    public ModelRenderer jointFRLX;
    public ModelRenderer jointBRLX;
    public ModelRenderer jointH;
    public ModelRenderer body_1;
    public ModelRenderer body_2;
    public ModelRenderer jointdont;
    public ModelRenderer jointBLLY;
    public ModelRenderer leg;
    public ModelRenderer jointBLL1;
    public ModelRenderer legdec;
    public ModelRenderer leg_1;
    public ModelRenderer jointBLL2;
    public ModelRenderer leg_2;
    public ModelRenderer jointBLL3;
    public ModelRenderer leg_3;
    public ModelRenderer leg_4;
    public ModelRenderer jointdont_1;
    public ModelRenderer jointFLLY;
    public ModelRenderer leg_5;
    public ModelRenderer jointFLL1;
    public ModelRenderer legdec_1;
    public ModelRenderer leg_6;
    public ModelRenderer jointFLL2;
    public ModelRenderer leg_7;
    public ModelRenderer jointFLL3;
    public ModelRenderer leg_8;
    public ModelRenderer leg_9;
    public ModelRenderer jointdont_2;
    public ModelRenderer jointFRLY;
    public ModelRenderer leg_10;
    public ModelRenderer jointFRL1;
    public ModelRenderer legdec_2;
    public ModelRenderer leg_11;
    public ModelRenderer jointFRL2;
    public ModelRenderer leg_12;
    public ModelRenderer jointFRL3;
    public ModelRenderer leg_13;
    public ModelRenderer leg_14;
    public ModelRenderer jointdont_3;
    public ModelRenderer jointBRLY;
    public ModelRenderer leg_15;
    public ModelRenderer jointBRL1;
    public ModelRenderer legdec_3;
    public ModelRenderer leg_16;
    public ModelRenderer jointBRL2;
    public ModelRenderer leg_17;
    public ModelRenderer jointBRL3;
    public ModelRenderer leg_18;
    public ModelRenderer leg_19;
    public ModelRenderer body_3;
    public ModelRenderer jointLM;
    public ModelRenderer jointRM;
    public ModelRenderer mouth;
    public ModelRenderer teeth;
    public ModelRenderer teeth_1;
    public ModelRenderer teeth_2;
    public ModelRenderer mouth_1;
    public ModelRenderer teeth_3;
    public ModelRenderer teeth_4;
    public ModelRenderer teeth_5;

    public ModelCanra() {
        this.textureWidth = 128;
        this.textureHeight = 75;
        this.leg_12 = new ModelRenderer(this, 56, 41);
        this.leg_12.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_12.addBox(-1.0f, -2.0f, -2.0f, 13, 4, 4, 0.0f);
        this.setRotateAngle(this.leg_12, 0.0f, 0.0f, 0.7679449f);
        this.jointdont_3 = new ModelRenderer(this, 116, 2);
        this.jointdont_3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointdont_3.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.jointdont_3, 0.0f, -2.4783676f, 0.0f);
        this.leg_2 = new ModelRenderer(this, 63, 22);
        this.leg_2.setRotationPoint(0.0f, -1.0f, 0.0f);
        this.leg_2.addBox(-1.0f, -2.0f, -2.0f, 8, 4, 4, 0.0f);
        this.setRotateAngle(this.leg_2, 0.0f, 0.0f, -0.9075712f);
        this.body = new ModelRenderer(this, 0, 0);
        this.body.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.body.addBox(-8.0f, -5.0f, -4.5f, 16, 10, 9, 0.0f);
        this.setRotateAngle(this.body, 0.20943952f, 0.0f, 0.0f);
        this.jointdont_2 = new ModelRenderer(this, 49, 2);
        this.jointdont_2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointdont_2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.jointdont_2, 0.0f, 2.4260077f, 0.0f);
        this.jointBLLY = new ModelRenderer(this, 86, 0);
        this.jointBLLY.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointBLLY.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg = new ModelRenderer(this, 86, 0);
        this.leg.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg.addBox(-1.0f, -2.0f, -2.0f, 11, 4, 4, 0.0f);
        this.setRotateAngle(this.leg, 0.0f, 0.0f, 0.12217305f);
        this.jointFRL2 = new ModelRenderer(this, 86, 2);
        this.jointFRL2.setRotationPoint(15.3f, 0.0f, 0.0f);
        this.jointFRL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointdont_1 = new ModelRenderer(this, 123, 1);
        this.jointdont_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointdont_1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.jointdont_1, 0.0f, 0.715585f, 0.0f);
        this.legdec_2 = new ModelRenderer(this, 91, 38);
        this.legdec_2.setRotationPoint(2.0f, -2.5f, 0.0f);
        this.legdec_2.addBox(-2.5f, -1.5f, -2.5f, 7, 4, 5, 0.0f);
        this.setRotateAngle(this.legdec_2, 0.0f, 0.0f, 0.12217305f);
        this.jointBRL1 = new ModelRenderer(this, 123, 3);
        this.jointBRL1.setRotationPoint(7.5f, 0.0f, 0.0f);
        this.jointBRL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_5 = new ModelRenderer(this, 0, 27);
        this.leg_5.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_5.addBox(-1.0f, -2.0f, -2.0f, 17, 4, 4, 0.0f);
        this.setRotateAngle(this.leg_5, 0.0f, 0.0f, -0.9773844f);
        this.leg_9 = new ModelRenderer(this, 0, 35);
        this.leg_9.setRotationPoint(0.5f, 1.0f, 0.0f);
        this.leg_9.addBox(-2.0f, -1.0f, -1.0f, 9, 2, 2, 0.0f);
        this.setRotateAngle(this.leg_9, 0.0f, 0.0f, 0.55850536f);
        this.body_3 = new ModelRenderer(this, 84, 58);
        this.body_3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.body_3.addBox(-4.0f, -2.0f, -2.0f, 8, 6, 6, 0.0f);
        this.leg_18 = new ModelRenderer(this, 42, 57);
        this.leg_18.setRotationPoint(0.0f, 1.0f, 0.0f);
        this.leg_18.addBox(-1.5f, -1.0f, -1.5f, 10, 2, 3, 0.0f);
        this.setRotateAngle(this.leg_18, 0.0f, 0.0f, 0.7330383f);
        this.body_1 = new ModelRenderer(this, 50, 0);
        this.body_1.setRotationPoint(0.0f, 0.0f, 5.0f);
        this.body_1.addBox(-6.0f, -4.0f, -2.0f, 12, 8, 8, 0.0f);
        this.setRotateAngle(this.body_1, 0.19198622f, 0.0f, 0.0f);
        this.leg_11 = new ModelRenderer(this, 0, 44);
        this.leg_11.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.leg_11.addBox(-2.5f, -1.5f, -1.5f, 18, 3, 3, 0.0f);
        this.setRotateAngle(this.leg_11, 0.0f, 0.0f, 2.1118484f);
        this.legdec = new ModelRenderer(this, 45, 16);
        this.legdec.setRotationPoint(0.0f, -2.0f, 0.0f);
        this.legdec.addBox(-2.5f, -1.0f, -2.5f, 6, 2, 5, 0.0f);
        this.setRotateAngle(this.legdec, 0.34906584f, 0.0f, 0.0f);
        this.leg_13 = new ModelRenderer(this, 87, 47);
        this.leg_13.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_13.addBox(-1.5f, -1.0f, -1.5f, 9, 2, 3, 0.0f);
        this.setRotateAngle(this.leg_13, 0.0f, 0.0f, -0.55850536f);
        this.jointH = new ModelRenderer(this, 53, 0);
        this.jointH.setRotationPoint(0.0f, 2.0f, -5.0f);
        this.jointH.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointFLL2 = new ModelRenderer(this, 41, 2);
        this.jointFLL2.setRotationPoint(15.3f, 0.0f, 0.0f);
        this.jointFLL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointBRL2 = new ModelRenderer(this, 0, 4);
        this.jointBRL2.setRotationPoint(10.5f, 0.0f, 0.0f);
        this.jointBRL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointFLL1 = new ModelRenderer(this, 4, 2);
        this.jointFLL1.setRotationPoint(15.5f, 0.0f, 0.0f);
        this.jointFLL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_15 = new ModelRenderer(this, 58, 49);
        this.leg_15.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_15.addBox(-1.0f, -2.0f, -2.0f, 11, 4, 4, 0.0f);
        this.setRotateAngle(this.leg_15, 0.0f, 0.0f, 0.12217305f);
        this.leg_19 = new ModelRenderer(this, 68, 57);
        this.leg_19.setRotationPoint(0.5f, 1.0f, 0.0f);
        this.leg_19.addBox(-1.0f, -1.0f, -1.0f, 9, 2, 2, 0.0f);
        this.setRotateAngle(this.leg_19, 0.0f, 0.0f, 0.55850536f);
        this.mouth_1 = new ModelRenderer(this, 13, 61);
        this.mouth_1.setRotationPoint(-1.0f, 0.5f, -1.0f);
        this.mouth_1.addBox(-1.5f, -1.0f, -3.5f, 3, 4, 7, 0.0f);
        this.setRotateAngle(this.mouth_1, 1.5707964f, -0.2617994f, 0.0f);
        this.jointBLL2 = new ModelRenderer(this, 116, 0);
        this.jointBLL2.setRotationPoint(10.5f, 0.0f, 0.0f);
        this.jointBLL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointBLLX = new ModelRenderer(this, 4, 0);
        this.jointBLLX.setRotationPoint(6.0f, -7.0f, 13.0f);
        this.jointBLLX.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.teeth_5 = new ModelRenderer(this, 0, 6);
        this.teeth_5.setRotationPoint(0.0f, -2.2f, 2.0f);
        this.teeth_5.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth_5, -0.08726646f, 0.0f, 0.27925268f);
        this.leg_7 = new ModelRenderer(this, 62, 33);
        this.leg_7.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_7.addBox(-1.0f, -2.0f, -2.0f, 13, 4, 4, 0.0f);
        this.setRotateAngle(this.leg_7, 0.0f, 0.0f, 0.7679449f);
        this.jointFRLX = new ModelRenderer(this, 45, 0);
        this.jointFRLX.setRotationPoint(-8.0f, -3.0f, -1.0f);
        this.jointFRLX.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.legdec_3 = new ModelRenderer(this, 0, 50);
        this.legdec_3.setRotationPoint(0.0f, -2.0f, 0.0f);
        this.legdec_3.addBox(-2.5f, -1.0f, -2.5f, 6, 2, 5, 0.0f);
        this.setRotateAngle(this.legdec_3, -0.34906584f, 0.0f, 0.0f);
        this.mouth = new ModelRenderer(this, 0, 57);
        this.mouth.setRotationPoint(1.0f, 0.5f, -1.0f);
        this.mouth.addBox(-1.5f, -1.0f, -3.5f, 3, 4, 7, 0.0f);
        this.setRotateAngle(this.mouth, 1.5707964f, 0.2617994f, 0.0f);
        this.teeth_4 = new ModelRenderer(this, 120, 4);
        this.teeth_4.setRotationPoint(0.0f, -2.2f, -2.4f);
        this.teeth_4.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth_4, 0.08726646f, 0.0f, 0.27925268f);
        this.teeth_2 = new ModelRenderer(this, 82, 4);
        this.teeth_2.setRotationPoint(0.0f, -2.2f, 2.0f);
        this.teeth_2.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth_2, -0.08726646f, 0.0f, -0.27925268f);
        this.teeth_1 = new ModelRenderer(this, 53, 4);
        this.teeth_1.setRotationPoint(0.0f, -2.2f, -2.4f);
        this.teeth_1.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth_1, 0.08726646f, 0.0f, -0.27925268f);
        this.legdec_1 = new ModelRenderer(this, 42, 27);
        this.legdec_1.setRotationPoint(2.0f, -2.5f, 0.0f);
        this.legdec_1.addBox(-2.5f, -1.5f, -2.5f, 7, 4, 5, 0.0f);
        this.setRotateAngle(this.legdec_1, 0.0f, 0.0f, 0.12217305f);
        this.jointBRLY = new ModelRenderer(this, 120, 2);
        this.jointBRLY.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointBRLY.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointLM = new ModelRenderer(this, 41, 4);
        this.jointLM.setRotationPoint(2.5f, 0.5f, -1.5f);
        this.jointLM.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointFRL1 = new ModelRenderer(this, 82, 2);
        this.jointFRL1.setRotationPoint(15.5f, 0.0f, 0.0f);
        this.jointFRL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_16 = new ModelRenderer(this, 88, 52);
        this.leg_16.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.leg_16.addBox(-1.0f, -1.5f, -1.5f, 12, 3, 3, 0.0f);
        this.setRotateAngle(this.leg_16, 0.0f, 0.0f, 1.43117f);
        this.teeth = new ModelRenderer(this, 49, 4);
        this.teeth.setRotationPoint(0.0f, -2.2f, -0.2f);
        this.teeth.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth, 0.0f, 0.0f, -0.27925268f);
        this.jointBRLX = new ModelRenderer(this, 49, 0);
        this.jointBRLX.setRotationPoint(-6.0f, -7.0f, 13.0f);
        this.jointBRLX.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_1 = new ModelRenderer(this, 0, 19);
        this.leg_1.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.leg_1.addBox(-1.0f, -1.5f, -1.5f, 12, 3, 3, 0.0f);
        this.setRotateAngle(this.leg_1, 0.0f, 0.0f, 1.43117f);
        this.leg_17 = new ModelRenderer(this, 18, 53);
        this.leg_17.setRotationPoint(0.0f, -1.0f, 0.0f);
        this.leg_17.addBox(-1.0f, -2.0f, -2.0f, 8, 4, 4, 0.0f);
        this.setRotateAngle(this.leg_17, 0.0f, 0.0f, -0.9075712f);
        this.leg_3 = new ModelRenderer(this, 87, 22);
        this.leg_3.setRotationPoint(0.0f, 1.0f, 0.0f);
        this.leg_3.addBox(-1.5f, -1.0f, -1.5f, 10, 2, 3, 0.0f);
        this.setRotateAngle(this.leg_3, 0.0f, 0.0f, 0.7330383f);
        this.jointBLL1 = new ModelRenderer(this, 112, 0);
        this.jointBLL1.setRotationPoint(7.5f, 0.0f, 0.0f);
        this.jointBLL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointFLL3 = new ModelRenderer(this, 45, 2);
        this.jointFLL3.setRotationPoint(12.9f, -0.3f, 0.0f);
        this.jointFLL3.addBox(-0.5f, 0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_10 = new ModelRenderer(this, 18, 36);
        this.leg_10.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_10.addBox(-1.0f, -2.0f, -2.0f, 17, 4, 4, 0.0f);
        this.setRotateAngle(this.leg_10, 0.0f, 0.0f, -0.9773844f);
        this.leg_4 = new ModelRenderer(this, 28, 23);
        this.leg_4.setRotationPoint(0.5f, 1.0f, 0.0f);
        this.leg_4.addBox(-1.0f, -1.0f, -1.0f, 9, 2, 2, 0.0f);
        this.setRotateAngle(this.leg_4, 0.0f, 0.0f, 0.55850536f);
        this.body_2 = new ModelRenderer(this, 82, 8);
        this.body_2.setRotationPoint(0.0f, 0.0f, 6.0f);
        this.body_2.addBox(-5.5f, -3.0f, -1.0f, 11, 6, 8, 0.0f);
        this.setRotateAngle(this.body_2, 0.20943952f, 0.0f, 0.0f);
        this.leg_14 = new ModelRenderer(this, 40, 49);
        this.leg_14.setRotationPoint(0.5f, 1.0f, 0.0f);
        this.leg_14.addBox(-2.0f, -1.0f, -1.0f, 9, 2, 2, 0.0f);
        this.setRotateAngle(this.leg_14, 0.0f, 0.0f, 0.55850536f);
        this.jointRM = new ModelRenderer(this, 45, 4);
        this.jointRM.setRotationPoint(-2.5f, 0.5f, -1.5f);
        this.jointRM.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.teeth_3 = new ModelRenderer(this, 116, 4);
        this.teeth_3.setRotationPoint(0.0f, -2.2f, -0.2f);
        this.teeth_3.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth_3, 0.0f, 0.0f, 0.27925268f);
        this.mainbody = new ModelRenderer(this, 0, 0);
        this.mainbody.setRotationPoint(0.0f, 6.0f, -6.0f);
        this.mainbody.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.jointBRL3 = new ModelRenderer(this, 4, 4);
        this.jointBRL3.setRotationPoint(7.5f, -0.1f, 0.0f);
        this.jointBRL3.addBox(-0.5f, 0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointdont = new ModelRenderer(this, 82, 0);
        this.jointdont.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointdont.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.jointdont, 0.0f, -0.6632251f, 0.0f);
        this.jointFLLY = new ModelRenderer(this, 0, 2);
        this.jointFLLY.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointFLLY.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointFLLX = new ModelRenderer(this, 41, 0);
        this.jointFLLX.setRotationPoint(8.0f, -3.0f, -1.0f);
        this.jointFLLX.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointBLL3 = new ModelRenderer(this, 120, 0);
        this.jointBLL3.setRotationPoint(7.5f, -0.1f, 0.0f);
        this.jointBLL3.addBox(-0.5f, 0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_6 = new ModelRenderer(this, 84, 27);
        this.leg_6.setRotationPoint(0.0f, 0.5f, 0.0f);
        this.leg_6.addBox(-2.5f, -1.5f, -1.5f, 18, 3, 3, 0.0f);
        this.setRotateAngle(this.leg_6, 0.0f, 0.0f, 2.1118484f);
        this.jointFRLY = new ModelRenderer(this, 53, 2);
        this.jointFRLY.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointFRLY.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointFRL3 = new ModelRenderer(this, 112, 2);
        this.jointFRL3.setRotationPoint(12.9f, -0.3f, 0.0f);
        this.jointFRL3.addBox(-0.5f, 0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_8 = new ModelRenderer(this, 96, 33);
        this.leg_8.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_8.addBox(-1.5f, -1.0f, -1.5f, 9, 2, 3, 0.0f);
        this.setRotateAngle(this.leg_8, 0.0f, 0.0f, -0.55850536f);
        this.jointFRL2.addChild(this.leg_12);
        this.jointBRLX.addChild(this.jointdont_3);
        this.jointBLL2.addChild(this.leg_2);
        this.mainbody.addChild(this.body);
        this.jointFRLX.addChild(this.jointdont_2);
        this.jointdont.addChild(this.jointBLLY);
        this.jointBLLY.addChild(this.leg);
        this.leg_11.addChild(this.jointFRL2);
        this.jointFLLX.addChild(this.jointdont_1);
        this.leg_10.addChild(this.legdec_2);
        this.leg_15.addChild(this.jointBRL1);
        this.jointFLLY.addChild(this.leg_5);
        this.leg_8.addChild(this.leg_9);
        this.jointH.addChild(this.body_3);
        this.jointBRL3.addChild(this.leg_18);
        this.body.addChild(this.body_1);
        this.jointFRL1.addChild(this.leg_11);
        this.leg.addChild(this.legdec);
        this.jointFRL3.addChild(this.leg_13);
        this.mainbody.addChild(this.jointH);
        this.leg_6.addChild(this.jointFLL2);
        this.leg_16.addChild(this.jointBRL2);
        this.leg_5.addChild(this.jointFLL1);
        this.jointBRLY.addChild(this.leg_15);
        this.leg_18.addChild(this.leg_19);
        this.jointRM.addChild(this.mouth_1);
        this.leg_1.addChild(this.jointBLL2);
        this.mainbody.addChild(this.jointBLLX);
        this.mouth_1.addChild(this.teeth_5);
        this.jointFLL2.addChild(this.leg_7);
        this.mainbody.addChild(this.jointFRLX);
        this.leg_15.addChild(this.legdec_3);
        this.jointLM.addChild(this.mouth);
        this.mouth_1.addChild(this.teeth_4);
        this.mouth.addChild(this.teeth_2);
        this.mouth.addChild(this.teeth_1);
        this.leg_5.addChild(this.legdec_1);
        this.jointdont_3.addChild(this.jointBRLY);
        this.body_3.addChild(this.jointLM);
        this.leg_10.addChild(this.jointFRL1);
        this.jointBRL1.addChild(this.leg_16);
        this.mouth.addChild(this.teeth);
        this.mainbody.addChild(this.jointBRLX);
        this.jointBLL1.addChild(this.leg_1);
        this.jointBRL2.addChild(this.leg_17);
        this.jointBLL3.addChild(this.leg_3);
        this.leg.addChild(this.jointBLL1);
        this.leg_7.addChild(this.jointFLL3);
        this.jointFRLY.addChild(this.leg_10);
        this.leg_3.addChild(this.leg_4);
        this.body_1.addChild(this.body_2);
        this.leg_13.addChild(this.leg_14);
        this.body_3.addChild(this.jointRM);
        this.mouth_1.addChild(this.teeth_3);
        this.leg_17.addChild(this.jointBRL3);
        this.jointBLLX.addChild(this.jointdont);
        this.jointdont_1.addChild(this.jointFLLY);
        this.mainbody.addChild(this.jointFLLX);
        this.leg_2.addChild(this.jointBLL3);
        this.jointFLL1.addChild(this.leg_6);
        this.jointdont_2.addChild(this.jointFRLY);
        this.leg_12.addChild(this.jointFRL3);
        this.jointFLL3.addChild(this.leg_8);
    }

    public void render(Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale) {
        super.render(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
        this.mainbody.render(scale);
    }

    public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn) {
        EntityParasiteBase parasite = (EntityParasiteBase)entityIn;
        this.jointFLLX.rotateAngleY = 0.0f;
        this.jointFLLY.rotateAngleZ = 0.0f;
        this.jointFRLX.rotateAngleY = 0.0f;
        this.jointFRLY.rotateAngleZ = 0.0f;
        this.jointBLLX.rotateAngleY = 0.0f;
        this.jointBLLY.rotateAngleZ = 0.0f;
        this.jointBRLX.rotateAngleY = 0.0f;
        this.jointBRLY.rotateAngleZ = 0.0f;
        this.jointLM.rotateAngleY = 0.0f;
        this.jointRM.rotateAngleY = 0.0f;
        this.mainbody.offsetY = 0.0f;
        this.jointH.rotateAngleX = 0.0f;
        this.jointH.rotateAngleY = 0.0f;
        byte i = parasite.getParasiteStatus();
        if (i == 0) {
            if (!parasite.getStillAni()) {
                float GS = 2.0f;
                float GD = 1.0f;
                this.swingY(this.jointFLLX, 0.2f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFLLY, 0.2f * GS, 0.5f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointFRLX, 0.2f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFRLY, 0.2f * GS, 0.5f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBLLX, 0.2f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBLLY, 0.2f * GS, 0.4f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBRLX, 0.2f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBRLY, 0.2f * GS, 0.4f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointLM, 0.2f * GS, 0.5f * GD, 1, limbSwing, limbSwingAmount);
                this.swingY(this.jointRM, 0.2f * GS, 0.5f * GD, -1, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.4f * GS, 1, limbSwing, limbSwingAmount, 0.04f);
            }
            float f1 = Mth.cos((float)(ageInTicks * 0.2f)) * 0.1f;
            this.jointLM.rotateAngleY = -1.0f * f1;
            this.jointRM.rotateAngleY = f1;
        } else if (i == 1) {
            if (!parasite.getStillAni()) {
                float GS = 2.0f;
                float GD = 1.0f;
                this.swingY(this.jointFLLX, 0.2f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFLLY, 0.2f * GS, 0.5f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointFRLX, 0.2f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFRLY, 0.2f * GS, 0.5f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBLLX, 0.2f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBLLY, 0.2f * GS, 0.4f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBRLX, 0.2f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBRLY, 0.2f * GS, 0.4f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointLM, 0.2f * GS, 0.5f * GD, 1, limbSwing, limbSwingAmount);
                this.swingY(this.jointRM, 0.2f * GS, 0.5f * GD, -1, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.4f * GS, 1, limbSwing, limbSwingAmount, 0.04f);
            } else {
                float f1 = Mth.cos((float)(ageInTicks * 0.4f)) * 0.2f;
                this.jointLM.rotateAngleY = -1.0f * f1;
                this.jointRM.rotateAngleY = f1;
            }
        } else if (i == 2) {
            if (!parasite.getStillAni()) {
                float GS = 1.6f;
                float GD = 0.6f;
                this.swingY(this.jointFLLX, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFLLY, 0.3f * GS, 0.5f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointFRLX, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFRLY, 0.3f * GS, 0.5f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBLLX, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBLLY, 0.3f * GS, 0.4f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBRLX, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBRLY, 0.3f * GS, 0.4f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointLM, 0.35f * GS, 0.6f * GD, 1, limbSwing, limbSwingAmount);
                this.swingY(this.jointRM, 0.35f * GS, 0.6f * GD, -1, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.6f * GS, 1, limbSwing, limbSwingAmount, 0.04f);
            }
            float f1 = Mth.cos((float)(ageInTicks * 0.4f)) * 0.2f;
            this.jointLM.rotateAngleY = -1.0f * f1;
            this.jointRM.rotateAngleY = f1;
        } else if (i == 10) {
            float f2 = Mth.cos((float)(ageInTicks * 0.6f)) * 0.4f;
            float f3 = Mth.cos((float)(ageInTicks * 0.3f)) * 0.3f;
            this.jointLM.rotateAngleY = -0.3f + f3;
            this.jointRM.rotateAngleY = 0.5f + -1.0f * f3;
            this.jointH.rotateAngleX = -0.1f;
            this.jointH.rotateAngleY = f2;
        }
        this.underground(parasite, ageInTicks, this.mainbody);
    }
}

