import os,re,json,glob,collections
J='/home/claude/work/jar'; S='/home/claude/work/src/com/dhanantry/scapeandrunparasites'; A=J+'/assets/srparasites'
out=[]
w=out.append
def pk(p): return sorted(f for f in os.listdir(p)) if os.path.isdir(p) else []
def jfiles(d): 
    return sorted(os.path.relpath(os.path.join(r,f),d) for r,_,fs in os.walk(d) for f in fs if f.endswith('.java'))
w('# SRP 1.10.9 jar inventory (generated from CFR 0.152 decompile)\n')
w('Source of truth: `SRParasites-1_10_9.jar` (modid `srparasites`, author Dhanantry). Generated by `porting/tools/inventory.py`; counts are exact, lists are abbreviated where long.\n')
w('> **Decompile quality:** 1,094 files decompiled by CFR; 7 contain partial-decompile warnings (listed at end). Everything else is clean.\n')
# packages
w('## 1. Code packages (`com/dhanantry/scapeandrunparasites`)\n')
w('| Package | Decompiled files |\n|---|---|')
for d in pk(S):
    p=os.path.join(S,d)
    if os.path.isdir(p): w(f'| {d} | {len(jfiles(p))} |')
w('')
w('Root classes: `SRPMain` (@Mod), `SRPCoreMod` (FMLCorePlugin + MixinTweaker, shipped Mixin 0.8.7 + MixinExtras 0.5.4).\n')
# configs
spec=json.load(open('/home/claude/work/spec/config_spec.json'))
w('## 2. Config (holds every default)\n')
w('| Class | File | Entries | Categories |\n|---|---|---|---|')
for n,sp in spec.items():
    cats=collections.OrderedDict()
    for r in sp: cats[r['category']]=cats.get(r['category'],0)+1
    w(f"| {n} | `srparasites/{sp[0]['file']}` | {len(sp)} | {len(cats)} |")
w(f"\nTotal config entries: **{sum(len(v) for v in spec.values())}**. Types: "+', '.join(f'{k}={v}' for k,v in collections.Counter(r['fn'] for v in spec.values() for r in v).items())+'.\n')
w('`SRPConfigBlockConversions` holds `DEFAULT_INFESTATION_CONVERT_BLOCKS` (uses 1.12 `id:meta` strings; needs flattening).\n')
w('Categories per file:\n')
for n,sp in spec.items():
    cats=collections.OrderedDict()
    for r in sp: cats[r['category']]=cats.get(r['category'],0)+1
    w(f"- **{n}**: "+', '.join(f'`{c}` ({k})' for c,k in cats.items()))
w('')
# entities
src=open(S+'/init/SRPEntities.java',encoding='utf-8').read()
ents=re.findall(r'CreateEntity(Mob|Projectile|NoEgg)\("(\w+)", (\w+)\.class,? ?([^)]*?)\)',src)
mobs=[e for e in ents if e[0]=='Mob']; proj=[e for e in ents if e[0]!='Mob']
w('## 3. Registries\n')
w(f'### Entities (`SRPEntities`): {len(mobs)} mobs + {len(proj)} projectile/misc entities\n')
w('Mob registry names (all `srparasites:`): '+', '.join(f'`{m[1]}`' for m in mobs)+'\n')
w('Projectile/misc: '+', '.join(f'`{m[1]}`' for m in proj)+'\n')
w('Tile entities: `tileentitycanister`, `tileentitydod`, `parasite_loot` (+ see tileentity package).\n')
# bestiary
bd=A+'/bestiary'; tier=collections.Counter(); 
for f in glob.glob(bd+'/*.json'):
    if f.endswith('index.json'): continue
    tier[json.load(open(f,encoding='utf-8')).get('tier')]+=1
w(f'### Bestiary: {sum(tier.values())} entries + `index.json`\n')
w(', '.join(f'{k}={v}' for k,v in tier.items())+'\n')
# blocks / items from assets
bs=[f[:-5] for f in pk(A+'/blockstates')]
w(f'### Blocks: {len(bs)} blockstate files\n')
w(', '.join(f'`{b}`' for b in bs)+'\n')
im=[f[:-5] for f in pk(A+'/models/item')]
w(f'### Item models: {len(im)}\n')
w(', '.join(f'`{b}`' for b in im)+'\n')
# other registries sizes
for cls in ['SRPBlocks','SRPItems','SRPPotions','SRPSounds','SRPSoundTypes','SRPSpawning','SRPSmelting','SRPMusic','SRPToolMaterials','SRPCreativeTabs','SRPBiomes','SRPFluids']:
    p=S+('/util/' if cls=='SRPCreativeTabs' else '/init/')+cls+'.java'
    if os.path.exists(p): w(f'- `{cls}`: {sum(1 for _ in open(p,encoding="utf-8"))} lines')
w('')
_ps=open(S+'/init/SRPPotions.java',encoding='utf-8').read()
pot=[('','e:'+n) for n in re.findall(r'new (?!PotionType|PotionEffect)\w+\("(\w+)", (?:true|false)',_ps)]
pot_t=re.findall(r'new PotionType\("srparasites:(\w+)"',_ps)
w(f'### Potions: {len(pot)} effects, {len(pot_t)} potion types (brewable)\n')
w('Effects: '+', '.join(f'`{p[1][2:]}`' for p in pot)+'\n')
w('Potion types: '+', '.join(f'`{p}`' for p in pot_t)+'\n')
# phase
w('## 4. Phase classes\n- `phase/EvoPhase` (number, pointThreshold, originCount, originBonusHealth, originPenalty, scentBonus, pointGainDelay, spawn entries, warning message), `phase/EvoPhases` (sorted list, `updateCurrentPhase(totalPoints)`).\n')
# commands
w('## 5. Commands\n')
for f in ['util/SRPCommandSummonNidus','util/CommandForceCelestial','util/CommandExtremeSnow']:
    w(f'- `{f}.java`')
cm=subprocess_out=os.popen(f"grep -rl 'CommandBase' {S} | sed 's|{S}/||'").read().split()
w('- All classes extending `CommandBase`: '+', '.join(f'`{c}`' for c in cm)+'\n')
# network
nw=jfiles(S+'/network')
w(f'## 6. Network ({len(nw)} classes)\n'+', '.join(f'`{n[:-5]}`' for n in nw)+'\n')
# other packages lists
for d,t in [('compatibility','Compat'),('container','Containers'),('gui','GUI'),('tileentity','Tile entities'),('recipes','Recipes'),('advancements','Advancement triggers'),('mixins','Mixins'),('events','Events'),('feature','Feature'),('fluid','Fluids'),('proxy','Proxy'),('api','API'),('potion','Potion classes')]:
    fl=jfiles(S+'/'+d)
    w(f'## {t} (`{d}`, {len(fl)})\n'+', '.join(f'`{n[:-5]}`' for n in fl)+'\n')
w('## 7. World / generation (`world`)\n')
for sub in ['biome','celestial','gen','spawner','star']:
    fl=jfiles(S+'/world/'+sub)
    w(f'- **world/{sub}** ({len(fl)}): '+', '.join(f'`{n[:-5]}`' for n in fl))
w('- world root: '+', '.join(f'`{n[:-5]}`' for n in jfiles(S+'/world') if '/' not in n)+'\n')
# util/handlers
w('## 8. util\n')
for sub in ['','handlers','spawn','convert']:
    fl=[n for n in jfiles(S+'/util'+('/'+sub if sub else '')) if '/' not in n]
    w(f'- util/{sub}: '+', '.join(f'`{n[:-5]}`' for n in fl))
w('')
# item classes
w('## 9. Item / block classes\n- item ('+str(len(jfiles(S+'/item')))+'): '+', '.join(f'`{n[:-5]}`' for n in jfiles(S+'/item'))+'\n')
w('- block ('+str(len(jfiles(S+'/block')))+'): '+', '.join(f'`{n[:-5]}`' for n in jfiles(S+'/block'))+'\n')
# assets
w('## 10. Assets (`assets/srparasites`)\n')
w('| Folder | Files |\n|---|---|')
for d in pk(A):
    p=os.path.join(A,d)
    if os.path.isdir(p): w(f'| {d} | {sum(len(fs) for _,_,fs in os.walk(p))} |')
w('')
w('- `assets/minecraft/textures` overrides: '+str(sum(len(fs) for _,_,fs in os.walk(J+'/assets/minecraft/textures')))+' files: '+', '.join(sorted(os.path.relpath(os.path.join(r,f),J+'/assets/minecraft') for r,_,fs in os.walk(J+'/assets/minecraft/textures') for f in fs)[:30])+'\n')
w('- lang files: '+', '.join(pk(A+'/lang'))+'\n')
w('- advancements ('+str(len(pk(A+'/advancements')))+' top-level entries; recursive: '+str(sum(len(fs) for _,_,fs in os.walk(A+'/advancements')))+')\n')
w('- loot_tables: '+', '.join(os.path.relpath(os.path.join(r,f),A+'/loot_tables') for r,_,fs in os.walk(A+'/loot_tables') for f in fs)+' (all other drops are hard-coded in Java / config "Loot Table" string-list keys)\n')
w('- recipes: '+str(len(pk(A+'/recipes')))+' JSON (1.12 format)\n')
w('- shaders: '+', '.join(sorted(os.path.relpath(os.path.join(r,f),A+'/shaders') for r,_,fs in os.walk(A+'/shaders') for f in fs))+'\n')
w('- structures (.nbt, '+str(len(pk(A+'/structures')))+'): '+', '.join(pk(A+'/structures'))+'\n')
sj=json.load(open(A+'/sounds.json')); w(f'- sounds.json events: {len(sj)}; sound files: {sum(len(fs) for _,_,fs in os.walk(A+"/sounds"))}\n')
w('## 11. Mixins (`mixins.srparasites.json`, all client-side)\n- `MixinEntityRendererBlizzard` (targets `EntityRenderer.setupFog`, `renderRainSnow`, `Biome.canRain`, `Biome.getEnableSnow`)\n- `MixinRenderGlobalBlizzardSky` (targets `RenderGlobal.renderSky`, `WorldProvider.calcSunriseSunsetColors`)\n- `accessor.AccessorShaderGroup` (accessor for `ShaderGroup.listShaders`)\n')
w('## 12. Partial-decompile warnings\n')
bad=os.popen(f"cd /home/claude/work/src && grep -rl 'Exception decompiling\\|Decompilation failed\\|WARNING - Removed try catching' .").read().split()
w('\n'.join(f'- `{b[2:]}`' for b in bad)+'\n')
open('/home/claude/work/project/docs/JAR_INVENTORY.md','w',encoding='utf-8').write('\n'.join(out))
print(len('\n'.join(out)))
