"""Rule tables for srp_translate.py (1.12.2 MCP names -> 1.21.1 Mojang names)."""
import re

# SRG ids whose MCP name is ambiguous: replaced by a unique token that REGEX_RULES knows.
SRG_SPECIAL = {
    'field_73012_v': 'worldRand',
    'field_70146_Z': 'rand',
    'field_187136_p': 'rand',
    'func_177982_a': 'blockposAdd',
    'func_177971_a': 'blockposAddV',
    'func_178787_e': 'vecAdd',
    'func_177977_b': 'below',
    'func_177979_c': 'below',
    'func_177984_a': 'above',
    'func_177981_b': 'above',
    'func_177978_c': 'north',
    'func_177964_d': 'north',
    'func_177974_f': 'east',
    'func_177965_g': 'east',
    'func_177968_d': 'south',
    'func_177970_e': 'south',
    'func_177976_e': 'west',
    'func_177985_f': 'west',
    'func_177972_a': 'relative',
    'func_72317_d': 'aabbOffset',
    'func_70005_c_': 'entityGetName',
    'func_176610_l': 'getSerializedName',
    'func_175656_a': 'setBlockStateNoFlags',
    'func_180501_a': 'setBlockStateFlags',
    'func_175739_a': 'sendParticlesServer',
    'func_175688_a': 'addParticleWorld',
    'func_184185_a': 'entityPlaySound',
    'func_184148_a': 'worldPlaySoundXYZ',
    'func_184133_a': 'worldPlaySoundPos',
    'func_184134_a': 'worldPlaySoundLocal',
    'func_72872_a': 'getEntitiesWithinAABB',
    'func_175647_a': 'getEntitiesWithinAABB',
    'func_70092_e': 'getDistanceSqXYZ',
    'func_174818_b': 'getDistanceSqPos',
    'func_177951_i': 'distanceSqPos',
    'func_177954_c': 'distanceSqXYZ',
    'func_70071_h_': 'onUpdate',
    'func_70105_a': 'setSize',
    'func_180430_e': 'fallEntity',
    'func_70227_a': 'onImpact',
    'func_76222_j': 'isReplaceableMaterial',
    'func_176200_f': 'isReplaceable',
    'func_189515_b': 'writeToNBTEntity',
    'func_189511_e': 'writeToNBTEntity',
    'func_70020_e': 'readFromNBTEntity',
    'func_70037_a': 'readEntityFromNBT',
    'func_184221_a': 'setUniqueId',
    'func_186854_a': 'setUUIDTag',
    'func_186860_b': 'getUUIDTag',
    'func_186857_a': 'getUUIDTag',
    'func_74764_b': 'hasKey',
    'func_150297_b': 'hasKeyType',
    'func_188566_a': 'hasUUIDKey',
    'func_74767_n': 'getBoolean',
    'func_82766_b': 'getGameRuleBoolean',
    'func_190918_g': 'shrink',
    'func_186664_h': 'shrink',
    'func_74737_b': 'copyNBT',
    'func_77946_l': 'copyStack',
    'func_70046_E': 'getCollisionBoundingBox',
    'func_185890_d': 'getCollisionBoundingBox',
    'func_180640_a': 'getCollisionBoundingBox',
    'func_70070_b': 'getBrightnessForRender',
    'func_189214_a': 'getBrightnessForRender',
    'func_145838_q': 'getBlockType',
    'func_145831_w': 'getWorldTE',
    'func_191301_a': 'getKeyEntity',
    'func_191306_a': 'getKeyClass',
    'func_185904_a': 'getMaterial',
    'func_149688_o': 'getMaterial',
    'func_77973_b': 'getItem',
    'func_185473_a': 'getItemPickBlock',
    'func_177230_c': 'getBlock',
    'func_70631_g_': 'isChild',
    'func_184218_aH': 'isRiding',
    'field_70165_t': 'posX',
    'field_70163_u': 'posY',
    'field_70161_v': 'posZ',
    'field_70130_N': 'width',
    'field_70131_O': 'height',
    'field_70122_E': 'onGround',
    'field_70159_w': 'motionX',
    'field_70181_x': 'motionY',
    'field_70179_y': 'motionZ',
    'field_70170_p': 'worldObj',
    'field_70235_a': 'shootingEntity',
    'field_70250_c': 'thrownByEntity',
}

DOTTED_SPECIAL = {
    'AxisAlignedBB.grow(double)': 'grow',
    'EntityDataManager.createKey': '__define',
    'ItemStack.EMPTY': 'EMPTY',
    'ItemStack.isEmpty': 'isEmpty',
    'dataManager.get': '__get',
    'dataManager.register': '__defineId',
    'dataManager.set': '__set',
}

TYPE_MAP = {
    'EntityLivingBase': 'LivingEntity', 'EntityLiving': 'Mob', 'EntityCreature': 'PathfinderMob', 'EntityMob': 'Monster',
    'EntityPlayer': 'Player', 'EntityPlayerMP': 'ServerPlayer', 'World': 'Level', 'WorldServer': 'ServerLevel',
    'IBlockAccess': 'BlockGetter', 'IBlockState': 'BlockState', 'Vec3d': 'Vec3', 'Vec3i': 'Vec3i', 'AxisAlignedBB': 'AABB',
    'NBTTagCompound': 'CompoundTag', 'NBTTagList': 'ListTag', 'NBTBase': 'Tag', 'ResourceLocation': 'ResourceLocation',
    'EnumHand': 'InteractionHand', 'EnumFacing': 'Direction', 'EnumDifficulty': 'Difficulty', 'EnumParticleTypes': 'ParticleTypes',
    'MathHelper': 'Mth', 'EnumHandSide': 'HumanoidArm', 'SoundCategory': 'SoundSource', 'DifficultyInstance': 'DifficultyInstance',
    'DataParameter': 'EntityDataAccessor', 'DataSerializers': 'EntityDataSerializers', 'EntityDataManager': 'SynchedEntityData',
    'PotionEffect': 'MobEffectInstance', 'Potion': 'MobEffect', 'MobEffects': 'MobEffects',
    'EntityAIBase': 'Goal', 'EntityAISwimming': 'FloatGoal', 'EntityAILookIdle': 'RandomLookAroundGoal',
    'EntityAILeapAtTarget': 'LeapAtTargetGoal', 'EntityAIHurtByTarget': 'HurtByTargetGoal', 'EntityAIOpenDoor': 'OpenDoorGoal',
    'EntityAINearestAttackableTarget': 'NearestAttackableTargetGoal', 'EntityAIAttackMelee': 'MeleeAttackGoal',
    'EntityAIAvoidEntity': 'AvoidEntityGoal', 'EntityAITarget': 'TargetGoal',
    'EntityMoveHelper': 'MoveControl', 'EntityLookHelper': 'LookControl', 'EntityJumpHelper': 'JumpControl',
    'PathNavigate': 'PathNavigation', 'PathNavigateGround': 'GroundPathNavigation', 'PathNavigateFlying': 'FlyingPathNavigation',
    'PathNavigateSwimmer': 'WaterBoundPathNavigation', 'PathNavigateClimber': 'WallClimberNavigation',
    'PathPoint': 'Node', 'PathNodeType': 'PathType', 'Path': 'Path', 'WalkNodeProcessor': 'WalkNodeEvaluator',
    'SharedMonsterAttributes': 'Attributes', 'IAttributeInstance': 'AttributeInstance', 'IEntityLivingData': 'SpawnGroupData',
    'EntityEquipmentSlot': 'EquipmentSlot', 'EntityItem': 'ItemEntity', 'EntityXPOrb': 'ExperienceOrb',
    'EntityAreaEffectCloud': 'AreaEffectCloud', 'EntityFallingBlock': 'FallingBlockEntity', 'EntityLightningBolt': 'LightningBolt',
    'EntityBoat': 'Boat', 'EntityMinecart': 'AbstractMinecart', 'EntityVillager': 'Villager', 'EntityWaterMob': 'WaterAnimal',
    'EntityAnimal': 'Animal', 'EntityCreeper': 'Creeper', 'EntitySlime': 'Slime', 'AbstractSkeleton': 'AbstractSkeleton',
    'EntityFireball': 'Fireball', 'EntityThrowable': 'ThrowableProjectile', 'IRangedAttackMob': 'RangedAttackMob',
    'MoverType': 'MoverType', 'RayTraceResult': 'HitResult', 'TextFormatting': 'ChatFormatting',
    'ITextComponent': 'Component', 'TextComponentString': 'Component', 'TextComponentTranslation': 'Component',
    'TileEntity': 'BlockEntity', 'BlockLiquid': 'LiquidBlock', 'BlockBush': 'BushBlock', 'BlockPortal': 'NetherPortalBlock',
    'BlockEndPortalFrame': 'EndPortalFrameBlock', 'BlockEndGateway': 'EndGatewayBlock', 'BlockDoor': 'DoorBlock',
    'BlockFenceGate': 'FenceGateBlock', 'EnumCreatureType': 'MobCategory', 'CooldownTracker': 'ItemCooldowns',
    'ItemFood': 'Item', 'ItemShield': 'ShieldItem', 'ItemArmor': 'ArmorItem', 'BossInfoServer': 'ServerBossEvent',
    'BossInfo': 'BossEvent', 'EnumSkyBlock': 'LightLayer', 'EntityEquipmentSlot2': 'EquipmentSlot', 'IInventory': 'Container',
    'InventoryPlayer': 'Inventory', 'Container': 'AbstractContainerMenu', 'EnumDyeColor': 'DyeColor', 'NonNullList': 'NonNullList',
    'Biome': 'Biome', 'IItemHandler': 'IItemHandler', 'MultiPartEntityPart': 'EntityPart', 'IEntityMultiPart': 'IEntityMultiPart',
    'ItemStackHelper': 'ContainerHelper', 'EntityDamageSourceIndirect': 'DamageSource', 'EntityDamageSource': 'DamageSource',
    'EntitySelectors': 'EntitySelector', 'EnchantmentHelper': 'EnchantmentHelper', 'ForgeEventFactory': 'EventHooks',
    'Material': 'Material', 'EntityFishHook': 'FishingHook', 'Packet': 'Packet', 'Team': 'Team',
    'ProjectileHelper': 'ProjectileUtil', 'EntitySquid': 'Squid', 'EntitySilverfish': 'Silverfish',
    'StatList': 'Stats', 'PotionType': 'Potion', 'PotionUtils': 'PotionContents', 'PotionTypes': 'Potions',
    'ModelBase': 'EntityModel', 'RandomPositionGenerator': 'DefaultRandomPos', 'ISound': 'SoundInstance',
    'Item': 'Item', 'ITickable': 'TickableBlockEntity',
    'IProperty': 'Property', 'ToolMaterial': 'Tier', 'ActionResult': 'InteractionResultHolder', 'ITooltipFlag': 'TooltipFlag', 'EnumActionResult': 'InteractionResult', 'Random': 'RandomSource',
}

# classes that must not be imported automatically (the translator rewrites them / they live elsewhere)
DONT_IMPORT = {'Random', 'Material', 'EntityPart', 'IEntityMultiPart', 'EntityList', 'TickableBlockEntity', 'PotionContents', 'Potions', 'Team', 'Packet'}
REMOVED_IMPORTS = set()
REMOVED_SIMPLE = {'SRPPacketParticle', 'SRPPacketMovingSound', 'SRPPacketEntityBodyDead', 'SRPPacketEntityBodyHit', 'MsgQlipShake', 'SRPMain', 'SRPNetwork', 'IMessage', 'SRPPacketHandler', 'TileEntityBeacon'}

IMPORT_OVERRIDES = {
    'Entity': 'net.minecraft.world.entity.Entity',
    'Player': 'net.minecraft.world.entity.player.Player',
    'ServerPlayer': 'net.minecraft.server.level.ServerPlayer',
    'Level': 'net.minecraft.world.level.Level',
    'ServerLevel': 'net.minecraft.server.level.ServerLevel',
    'Block': 'net.minecraft.world.level.block.Block',
    'Blocks': 'net.minecraft.world.level.block.Blocks',
    'BlockState': 'net.minecraft.world.level.block.state.BlockState',
    'Item': 'net.minecraft.world.item.Item',
    'Items': 'net.minecraft.world.item.Items',
    'ItemStack': 'net.minecraft.world.item.ItemStack',
    'DamageSource': 'net.minecraft.world.damagesource.DamageSource',
    'SoundEvent': 'net.minecraft.sounds.SoundEvent',
    'SoundEvents': 'net.minecraft.sounds.SoundEvents',
    'SoundSource': 'net.minecraft.sounds.SoundSource',
    'Mth': 'net.minecraft.util.Mth',
    'Attributes': 'net.minecraft.world.entity.ai.attributes.Attributes',
    'Goal': 'net.minecraft.world.entity.ai.goal.Goal',
    'AABB': 'net.minecraft.world.phys.AABB',
    'Vec3': 'net.minecraft.world.phys.Vec3',
    'BlockPos': 'net.minecraft.core.BlockPos',
    'Direction': 'net.minecraft.core.Direction',
    'Pose': 'net.minecraft.world.entity.Pose',
    'Component': 'net.minecraft.network.chat.Component',
    'MobEffects': 'net.minecraft.world.effect.MobEffects',
    'MobEffectInstance': 'net.minecraft.world.effect.MobEffectInstance',
    'MobEffect': 'net.minecraft.world.effect.MobEffect',
    'ParticleTypes': 'net.minecraft.core.particles.ParticleTypes',
    'CompoundTag': 'net.minecraft.nbt.CompoundTag',
    'Tag': 'net.minecraft.nbt.Tag',
    'ListTag': 'net.minecraft.nbt.ListTag',
    'Difficulty': 'net.minecraft.world.Difficulty',
    'EntityDataAccessor': 'net.minecraft.network.syncher.EntityDataAccessor',
    'EntityDataSerializers': 'net.minecraft.network.syncher.EntityDataSerializers',
    'SynchedEntityData': 'net.minecraft.network.syncher.SynchedEntityData',
    'LivingEntity': 'net.minecraft.world.entity.LivingEntity',
    'Mob': 'net.minecraft.world.entity.Mob',
    'PathfinderMob': 'net.minecraft.world.entity.PathfinderMob',
    'Monster': 'net.minecraft.world.entity.monster.Monster',
    'Animal': 'net.minecraft.world.entity.animal.Animal',
    'WaterAnimal': 'net.minecraft.world.entity.animal.WaterAnimal',
    'Villager': 'net.minecraft.world.entity.npc.Villager',
    'EntityType': 'net.minecraft.world.entity.EntityType',
    'MobCategory': 'net.minecraft.world.entity.MobCategory',
    'MoverType': 'net.minecraft.world.entity.MoverType',
    'EquipmentSlot': 'net.minecraft.world.entity.EquipmentSlot',
    'InteractionHand': 'net.minecraft.world.InteractionHand',
    'InteractionResult': 'net.minecraft.world.InteractionResult',
    'SpawnGroupData': 'net.minecraft.world.entity.SpawnGroupData',
    'MobSpawnType': 'net.minecraft.world.entity.MobSpawnType',
    'DifficultyInstance': 'net.minecraft.world.DifficultyInstance',
    'ServerLevelAccessor': 'net.minecraft.world.level.ServerLevelAccessor',
    'BlockGetter': 'net.minecraft.world.level.BlockGetter',
    'LevelReader': 'net.minecraft.world.level.LevelReader',
    'LevelAccessor': 'net.minecraft.world.level.LevelAccessor',
    'HitResult': 'net.minecraft.world.phys.HitResult',
    'BlockHitResult': 'net.minecraft.world.phys.BlockHitResult',
    'EntityHitResult': 'net.minecraft.world.phys.EntityHitResult',
    'ClipContext': 'net.minecraft.world.level.ClipContext',
    'ThrowableProjectile': 'net.minecraft.world.entity.projectile.ThrowableProjectile',
    'Fireball': 'net.minecraft.world.entity.projectile.Fireball',
    'Projectile': 'net.minecraft.world.entity.projectile.Projectile',
    'ResourceLocation': 'net.minecraft.resources.ResourceLocation',
    'ChatFormatting': 'net.minecraft.ChatFormatting',
    'BlockEntity': 'net.minecraft.world.level.block.entity.BlockEntity',
    'LiquidBlock': 'net.minecraft.world.level.block.LiquidBlock',
    'MeleeAttackGoal': 'net.minecraft.world.entity.ai.goal.MeleeAttackGoal',
    'ItemEntity': 'net.minecraft.world.entity.item.ItemEntity',
    'ExperienceOrb': 'net.minecraft.world.entity.ExperienceOrb',
    'EventHooks': 'net.neoforged.neoforge.event.EventHooks',
    'NeoForge': 'net.neoforged.neoforge.common.NeoForge',
    'Biome': 'net.minecraft.world.level.biome.Biome',
    'Holder': 'net.minecraft.core.Holder',
    'BuiltInRegistries': 'net.minecraft.core.registries.BuiltInRegistries',
    'Registries': 'net.minecraft.core.registries.Registries',
    'DimKeys': 'com.dhanantry.scapeandrunparasites.phase.DimKeys',
    'Mot': 'com.dhanantry.scapeandrunparasites.util.Mot',
    'SubscribeEvent': 'net.neoforged.bus.api.SubscribeEvent',
    'Property': 'net.minecraft.world.level.block.state.properties.Property',
    'PacketDistributor': 'net.neoforged.neoforge.network.PacketDistributor',
    'ParticlePayload': 'com.dhanantry.scapeandrunparasites.network.ParticlePayload',
    'MovingSoundPayload': 'com.dhanantry.scapeandrunparasites.network.MovingSoundPayload',
    'EntityBodyDeadPayload': 'com.dhanantry.scapeandrunparasites.network.EntityBodyDeadPayload',
    'EntityBodyHitPayload': 'com.dhanantry.scapeandrunparasites.network.EntityBodyHitPayload',
    'QlipShakePayload': 'com.dhanantry.scapeandrunparasites.network.QlipShakePayload',
    'PhaseTables': 'com.dhanantry.scapeandrunparasites.phase.PhaseTables',
    'MobEffectCategory': 'net.minecraft.world.effect.MobEffectCategory',
    'DamageTypes': 'net.minecraft.world.damagesource.DamageTypes',
    'Particles': 'com.dhanantry.scapeandrunparasites.util.SRPEntityUtil',
    'SRPEntityUtil': 'com.dhanantry.scapeandrunparasites.util.SRPEntityUtil',
    'SRPGoal': 'com.dhanantry.scapeandrunparasites.entity.ai.SRPGoal',
    'EnumSet': 'java.util.EnumSet',
    'Predicate': 'java.util.function.Predicate',
    'GameRules': 'net.minecraft.world.level.GameRules',
    'MobSpawnType2': 'net.minecraft.world.entity.MobSpawnType',
}

EXTRA_IMPORT_TRIGGERS = {}

# Block/Item/Sound constant renames (1.12 name -> 1.21 field), others get UPPER_CASE
BLOCK_CONST = {
    'stained_glass': 'WHITE_STAINED_GLASS', 'stained_glass_pane': 'WHITE_STAINED_GLASS_PANE', 'hell': 'NETHERRACK',
    'netherrack': 'NETHERRACK', 'web': 'COBWEB', 'sponge': 'SPONGE', 'grass': 'GRASS_BLOCK', 'tallgrass': 'SHORT_GRASS',
    'yellow_flower': 'DANDELION', 'red_flower': 'POPPY', 'deadbush': 'DEAD_BUSH', 'double_plant': 'TALL_GRASS',
    'lit_pumpkin': 'JACK_O_LANTERN', 'piston_head': 'PISTON_HEAD', 'mob_spawner': 'SPAWNER', 'snow_layer': 'SNOW',
    'snow': 'SNOW_BLOCK', 'clay': 'CLAY', 'log': 'OAK_LOG', 'log2': 'ACACIA_LOG', 'leaves': 'OAK_LEAVES', 'leaves2': 'ACACIA_LEAVES',
    'planks': 'OAK_PLANKS', 'sapling': 'OAK_SAPLING', 'flowing_water': 'WATER', 'flowing_lava': 'LAVA', 'water': 'WATER',
    'lava': 'LAVA', 'barrier': 'BARRIER', 'cactus': 'CACTUS', 'reeds': 'SUGAR_CANE', 'vine': 'VINE', 'ice': 'ICE',
    'packed_ice': 'PACKED_ICE', 'end_portal_frame': 'END_PORTAL_FRAME', 'end_gateway': 'END_GATEWAY', 'portal': 'NETHER_PORTAL',
    'end_portal': 'END_PORTAL', 'glass': 'GLASS', 'glass_pane': 'GLASS_PANE', 'sand': 'SAND', 'gravel': 'GRAVEL',
    'dirt': 'DIRT', 'stone': 'STONE', 'cobblestone': 'COBBLESTONE', 'bedrock': 'BEDROCK', 'fire': 'FIRE', 'torch': 'TORCH',
    'air': 'AIR', 'wool': 'WHITE_WOOL', 'carpet': 'WHITE_CARPET', 'obsidian': 'OBSIDIAN', 'farmland': 'FARMLAND',
    'mycelium': 'MYCELIUM', 'soul_sand': 'SOUL_SAND', 'magma': 'MAGMA_BLOCK', 'bookshelf': 'BOOKSHELF', 'ladder': 'LADDER',
    'crafting_table': 'CRAFTING_TABLE', 'furnace': 'FURNACE', 'chest': 'CHEST', 'beacon': 'BEACON', 'anvil': 'ANVIL',
    'bone_block': 'BONE_BLOCK', 'cake': 'CAKE', 'dragon_egg': 'DRAGON_EGG', 'leaves3': 'OAK_LEAVES',
}
ITEM_CONST = {
    'TOTEM_OF_UNDYING': 'TOTEM_OF_UNDYING', 'GOLDEN_APPLE': 'GOLDEN_APPLE', 'BONE': 'BONE', 'SNOWBALL': 'SNOWBALL',
    'ENDER_PEARL': 'ENDER_PEARL', 'FIRE_CHARGE': 'FIRE_CHARGE',
}
SOUND_CONST = {
    'ENTITY_ENDERMEN_TELEPORT': 'ENDERMAN_TELEPORT', 'ENTITY_ENDERMEN_SCREAM': 'ENDERMAN_SCREAM', 'ENTITY_ENDERMEN_STARE': 'ENDERMAN_STARE',
    'ENTITY_ENDERDRAGON_FLAP': 'ENDER_DRAGON_FLAP', 'ENTITY_ENDERDRAGON_HURT': 'ENDER_DRAGON_HURT', 'ENTITY_LIGHTNING_IMPACT': 'LIGHTNING_BOLT_IMPACT',
    'ENTITY_LIGHTNING_THUNDER': 'LIGHTNING_BOLT_THUNDER', 'ENTITY_FIREWORK_BLAST': 'FIREWORK_ROCKET_BLAST', 'ENTITY_GENERIC_EXPLODE': 'GENERIC_EXPLODE',
    'ENTITY_IRONGOLEM_STEP': 'IRON_GOLEM_STEP', 'ENTITY_SHULKER_BULLET_HURT': 'SHULKER_BULLET_HURT', 'ITEM_SHIELD_BLOCK': 'SHIELD_BLOCK',
    'BLOCK_ANVIL_LAND': 'ANVIL_LAND', 'BLOCK_GRASS_STEP': 'GRASS_STEP', 'BLOCK_NOTE_HAT': 'NOTE_BLOCK_HAT',
}
SOUND_HOLDERS = set()
try:
    for _l in open('C:/srp_work/mcsrc/net/minecraft/sounds/SoundEvents.java', encoding='utf8'):
        _m = re.search(r'Holder\.Reference<SoundEvent> (\w+)', _l)
        if _m:
            SOUND_HOLDERS.add(_m.group(1))
except OSError:
    pass
PARTICLE_CONST = {
    'SMOKE_NORMAL': 'SMOKE', 'SMOKE_LARGE': 'LARGE_SMOKE', 'EXPLOSION_NORMAL': 'POOF', 'EXPLOSION_LARGE': 'EXPLOSION',
    'EXPLOSION_HUGE': 'EXPLOSION_EMITTER', 'SPELL_MOB': 'ENTITY_EFFECT', 'SPELL_MOB_AMBIENT': 'ENTITY_EFFECT', 'SPELL': 'EFFECT',
    'SPELL_INSTANT': 'INSTANT_EFFECT', 'SPELL_WITCH': 'WITCH', 'REDSTONE': 'DUST', 'CRIT_MAGIC': 'ENCHANTED_HIT', 'WATER_BUBBLE': 'BUBBLE',
    'WATER_SPLASH': 'SPLASH', 'WATER_WAKE': 'FISHING', 'VILLAGER_HAPPY': 'HAPPY_VILLAGER', 'VILLAGER_ANGRY': 'ANGRY_VILLAGER',
    'SNOWBALL': 'ITEM_SNOWBALL', 'SNOW_SHOVEL': 'POOF', 'LAVA': 'LAVA', 'DRIP_LAVA': 'DRIPPING_LAVA', 'DRIP_WATER': 'DRIPPING_WATER',
    'ENCHANTMENT_TABLE': 'ENCHANT', 'SUSPENDED': 'UNDERWATER', 'SUSPENDED_DEPTH': 'UNDERWATER', 'TOWN_AURA': 'MYCELIUM',
    'FIREWORKS_SPARK': 'FIREWORK', 'SLIME': 'ITEM_SLIME', 'HEART': 'HEART', 'FLAME': 'FLAME', 'PORTAL': 'PORTAL', 'CRIT': 'CRIT',
    'DRAGON_BREATH': 'DRAGON_BREATH', 'END_ROD': 'END_ROD', 'CLOUD': 'CLOUD', 'NOTE': 'NOTE', 'BARRIER': 'BLOCK_MARKER',
    'MOB_APPEARANCE': 'ELDER_GUARDIAN', 'SPIT': 'SPIT', 'DAMAGE_INDICATOR': 'DAMAGE_INDICATOR', 'SWEEP_ATTACK': 'SWEEP_ATTACK',
    'BLOCK_CRACK': 'BLOCK', 'BLOCK_DUST': 'BLOCK', 'ITEM_CRACK': 'ITEM', 'FALLING_DUST': 'FALLING_DUST', 'TOTEM': 'TOTEM_OF_UNDYING',
}
MOBEFFECT_CONST = {
    'moveSlowdown': 'MOVEMENT_SLOWDOWN', 'moveSpeed': 'MOVEMENT_SPEED', 'digSlowdown': 'DIG_SLOWDOWN', 'digSpeed': 'DIG_SPEED',
    'damageBoost': 'DAMAGE_BOOST', 'harm': 'HARM', 'heal': 'HEAL', 'jump': 'JUMP', 'confusion': 'CONFUSION', 'regeneration': 'REGENERATION',
    'resistance': 'DAMAGE_RESISTANCE', 'fireResistance': 'FIRE_RESISTANCE', 'waterBreathing': 'WATER_BREATHING', 'invisibility': 'INVISIBILITY',
    'blindness': 'BLINDNESS', 'nightVision': 'NIGHT_VISION', 'hunger': 'HUNGER', 'weakness': 'WEAKNESS', 'poison': 'POISON',
    'wither': 'WITHER', 'healthBoost': 'HEALTH_BOOST', 'absorption': 'ABSORPTION', 'saturation': 'SATURATION', 'glowing': 'GLOWING',
    'levitation': 'LEVITATION', 'luck': 'LUCK', 'unluck': 'UNLUCK',
}
ATTRIBUTE_CONST = {
    'maxHealth': 'MAX_HEALTH', 'followRange': 'FOLLOW_RANGE', 'knockbackResistance': 'KNOCKBACK_RESISTANCE', 'movementSpeed': 'MOVEMENT_SPEED',
    'attackDamage': 'ATTACK_DAMAGE', 'attackSpeed': 'ATTACK_SPEED', 'armor': 'ARMOR', 'armorToughness': 'ARMOR_TOUGHNESS', 'luck': 'LUCK',
    'flyingSpeed': 'FLYING_SPEED',
}
BIOME_CONST = {}
DAMAGE_CONST = {}
CONST_TABLES = {}

# simple regex rules (ordered). Applied after structural rewrites.
REGEX_RULES = [
    # --- casts / noise
    (r'\(Object\)\s*', ''),
    (r'\((?:EntityAIBase|Goal|DataSerializer|EntityDataSerializer<[^>]*>)\)\s*', ''),
    (r'@SideOnly\(Side\.\w+\)\s*', ''),
    (r'@Override\s*\n(\s*)@Override', r'@Override'),
    # --- fields
    (r'\.worldObj\b', '.level()'),
    (r'\bworldRand\b', 'random'),
    (r'(?<=\))\.rand\b', '.getRandom()'),
    (r'\bthis\.rand\b', 'this.getRandom()'),
    (r'\.dataWatcher\b', '.entityData'),
    (r'\.experienceValue\b', '.xpReward'),
    (r'\.ticksExisted\b', '.tickCount'),
    (r'\.isDead\b', '.isRemoved()'),
    (r'\.isRemote\b', '.isClientSide'),
    (r'\.onGround\b(?!\s*\()', '.onGround()'),
    (r'\.navigator\b', '.getNavigation()'),
    (r'\.moveHelper\b', '.moveControl'),
    (r'\.tasks\b', '.goalSelector'),
    (r'\.targetTasks\b', '.targetSelector'),
    (r'\.entityAge\b', '.noActionTime'),
    (r'\.isJumping\b', '.jumping'),
    (r'\.moveStrafing\b', '.xxa'),
    (r'\.moveForward\b', '.zza'),
    (r'\.isCollidedHorizontally\b', '.horizontalCollision'),
    (r'\.isCollidedVertically\b', '.verticalCollision'),
    (r'\.isCollided\b', '.horizontalCollision'),
    (r'\.noClip\b', '.noPhysics'),
    (r'\.capabilities\b', '.getAbilities()'),
    (r'\.isCreativeMode\b', '.instabuild'),
    (r'\.isFlying\b(?!\()', '.flying'),
    (r'\.mainInventory\b', '.items'),
    (r'\.armorInventory\b', '.armor'),
    (r'\.inventory\b(?!\s*[=(])', '.getInventory()'),
    (r'\.attackingPlayer\b', '.lastHurtByPlayer'),
    (r'\.recentlyHit\b', '.lastHurtByPlayerTime'),
    (r'\.renderYawOffset\b', '.yBodyRot'),
    (r'\.prevRenderYawOffset\b', '.yBodyRotO'),
    (r'\.rotationYawHead\b', '.yHeadRot'),
    (r'\.prevRotationYawHead\b', '.yHeadRotO'),
    (r'\.prevRotationYaw\b', '.yRotO'),
    (r'\.prevRotationPitch\b', '.xRotO'),
    (r'\.randomYawVelocity\b', '.rotA'),
    (r'\.fallDistance\b', '.fallDistance'),
    (r'\.provider\.getDimension\(\)', '.dimensionKeyPlaceholder()'),
    (r'\.provider\b', '.dimensionType()'),
    (r'\.playerEntities\b', '.players()'),
    (r'\.shootingEntity\b', '.getOwner()'),
    (r'\.deathTime\b', '.deathTime'),
    (r'\.entityHit\b', '.entityHit'),
    # --- name mapping for calls (method name -> mojang)
    (r'\.getAttackTarget\(\)', '.getTarget()'),
    (r'\.setAttackTarget\(', '.setTarget('),
    (r'\.getEntityAttribute\(', '.getAttribute('),
    (r'\.getAttributeValue\(\)', '.getValue()'),
    (r'\.isEntityAlive\(\)', '.isAlive()'),
    (r'\.getDistanceSqToEntity\(', '.distanceToSqr('),
    (r'\.getDistanceToEntity\(', '.distanceTo('),
    (r'\.getDistanceSqXYZ\(', '.distanceToSqr('),
    (r'\.getDistanceSqPos\(', '.distToCenterSqr('),
    (r'\.getPosition\(\)', '.blockPosition()'),
    (r'\.getPositionEyes\(', '.getEyePosition('),
    (r'\.getLookVec\(\)', '.getLookAngle()'),
    (r'\.getLook\(', '.getViewVector('),
    (r'\.getEntityBoundingBox\(\)', '.getBoundingBox()'),
    (r'\.setEntityBoundingBox\(', '.setBoundingBox('),
    (r'\.getEyeHeight\(\)', '.getEyeHeight()'),
    (r'\.grow\(', '.inflate('),
    (r'\.expand\(', '.expandTowards('),
    (r'\.aabbOffset\(', '.move('),
    (r'\.intersectsWith\(', '.intersects('),
    (r'\.getEntitiesWithinAABBExcludingEntity\(', '.getEntities('),
    (r'\.getEntitiesWithinAABB\(', '.getEntitiesOfClass('),
    (r'\.spawnEntityInWorld\(', '.addFreshEntity('),
    (r'\.isAirBlock\(', '.isEmptyBlock('),
    (r'\.setBlockStateNoFlags\(', '.setBlockAndUpdate('),
    (r'\.setBlockStateFlags\(', '.setBlock('),
    (r'\.setBlockToAir\(([^()]*(?:\([^()]*\))*[^()]*)\)', r'.removeBlock(\1, false)'),
    (r'\.getTileEntity\(', '.getBlockEntity('),
    (r'\.getDefaultState\(\)', '.defaultBlockState()'),
    (r'\.withProperty\(', '.setValue('),
    (r'\.getMetaFromState\(', '.getMetaFromStatePlaceholder('),
    (r'\.below\(\)', '.below()'),
    (r'\.blockposAdd\(', '.offset('),
    (r'\.blockposAddV\(', '.offset('),
    (r'\.vecAdd\(', '.add('),
    (r'\.getOpposite\(\)', '.getOpposite()'),
    (r'\.getHorizontalFacing\(\)', '.getDirection()'),
    (r'\.isPotionActive\(', '.hasEffect('),
    (r'\.getActivePotionEffect\(', '.getEffect('),
    (r'\.getActivePotionEffects\(\)', '.getActiveEffects()'),
    (r'\.addPotionEffect\(', '.addEffect('),
    (r'\.removePotionEffect\(', '.removeEffect('),
    (r'\.removeActivePotionEffect\(', '.removeEffect('),
    (r'\.clearActivePotions\(\)', '.removeAllEffects()'),
    (r'\.getPotion\(\)', '.getEffect()'),
    (r'\.isPotionApplicable\(', '.canBeAffected('),
    (r'\.getHeldItemMainhand\(\)', '.getMainHandItem()'),
    (r'\.getHeldItemOffhand\(\)', '.getOffhandItem()'),
    (r'\.getHeldItem\(', '.getItemInHand('),
    (r'\.getItemStackFromSlot\(', '.getItemBySlot('),
    (r'\.getItem\(\)', '.getItem()'),
    (r'\.copyStack\(\)', '.copy()'),
    (r'\.isEmpty\(\)', '.isEmpty()'),
    (r'\.damageItem\(([^,()]+),\s*', r'.hurtAndBreak(\1, '),
    (r'\.setEntityState\(([^,()]+),\s*', r'.broadcastEntityEvent(\1, '),
    (r'\.handleStatusUpdate\(', '.handleEntityEvent('),
    (r'\.getSoundVolume\(\)', '.getSoundVolume()'),
    (r'\.getSoundPitch\(\)', '.getVoicePitch()'),
    (r'\.setPositionAndUpdate\(', '.teleportTo('),
    (r'\.setLocationAndAngles\(', '.moveTo('),
    (r'\.copyLocationAndAnglesFrom\(', '.copyPosition('),
    (r'\.setPosition\(', '.setPos('),
    (r'\.setDead\(\)', '.discard()'),
    (r'\.setInvisible\(', '.setInvisible('),
    (r'\.setNoGravity\(', '.setNoGravity('),
    (r'\.setGlowing\(', '.setGlowingTag('),
    (r'\.heal\(', '.heal('),
    (r'\.getMaxHealth\(\)', '.getMaxHealth()'),
    (r'\.getHealth\(\)', '.getHealth()'),
    (r'\.getAbsorptionAmount\(\)', '.getAbsorptionAmount()'),
    (r'\.getCreatureAttribute\(\)', '.getMobTypePlaceholder()'),
    (r'\.entityGetName\(\)', '.getName().getString()'),
    (r'\.getUniqueID\(\)', '.getUUID()'),
    (r'\.getEntityId\(\)', '.getId()'),
    (r'\.getEntityByID\(', '.getEntity('),
    (r'\.getAITarget\(\)', '.getLastHurtByMob()'),
    (r'\.setRevengeTarget\(', '.setLastHurtByMob('),
    (r'\.getAttackingEntity\(\)', '.getLastHurtByMob()'),
    (r'\.setLastAttacker\(', '.setLastHurtMob('),
    (r'\.getRidingEntity\(\)', '.getVehicle()'),
    (r'\.dismountRidingEntity\(\)', '.stopRiding()'),
    (r'\.startRiding\(', '.startRiding('),
    (r'\.getPassengers\(\)', '.getPassengers()'),
    (r'\.isBeingRidden\(\)', '.isVehicle()'),
    (r'\.isRiding\(\)', '.isPassenger()'),
    (r'\.isInWater\(\)', '.isInWater()'),
    (r'\.isInLava\(\)', '.isInLava()'),
    (r'\.isBurning\(\)', '.isOnFire()'),
    (r'\.isSneaking\(\)', '.isShiftKeyDown()'),
    (r'\.isSprinting\(\)', '.isSprinting()'),
    (r'\.isInvisible\(\)', '.isInvisible()'),
    (r'\.isSpectator\(\)', '.isSpectator()'),
    (r'\.isCreative\(\)', '.isCreative()'),
    (r'\.isSilent\(\)', '.isSilent()'),
    (r'\.setFire\(', '.igniteForSeconds('),
    (r'\.extinguish\(\)', '.clearFire()'),
    (r'\.canEntityBeSeen\(', '.hasLineOfSight('),
    (r'\.getEntitySenses\(\)\.canSee\(', '.getSensing().hasLineOfSight('),
    (r'\.getNavigator\(\)', '.getNavigation()'),
    (r'\.getMoveHelper\(\)', '.getMoveControl()'),
    (r'\.getLookHelper\(\)', '.getLookControl()'),
    (r'\.getJumpHelper\(\)', '.getJumpControl()'),
    (r'\.clearPathEntity\(\)', '.stop()'),
    (r'\.noPath\(\)', '.isDone()'),
    (r'\.tryMoveToEntityLiving\(', '.moveTo('),
    (r'\.tryMoveToXYZ\(', '.moveTo('),
    (r'\.getPathToEntityLiving\(', '.createPath('),
    (r'\.getPathToXYZ\(', '.createPath('),
    (r'\.setPath\(', '.moveTo('),
    (r'\.setMoveTo\(', '.setWantedPosition('),
    (r'\.setLookPositionWithEntity\(', '.setLookAt('),
    (r'\.setLookPosition\(', '.setLookAt('),
    (r'\.setCanSwim\(', '.setCanFloat('),
    (r'\.setCanEnterDoors\(', '.setCanOpenDoors('),
    (r'\.setEnterDoors\(', '.setCanPassDoors('),
    (r'\.setCanFloat\(', '.setCanFloat('),
    (r'\.addTask\(', '.addGoal('),
    (r'\.removeTask\(', '.removeGoal('),
    (r'\.addVelocity\(', '.push('),
    (r'\.knockBack\(', '.knockback('),
    (r'\.attackEntityFrom\(', '.hurt('),
    (r'\.attackEntityAsMob\(', '.doHurtTarget('),
    (r'\.onUpdate\(\)', '.tick()'),
    (r'\.onLivingUpdate\(\)', '.aiStep()'),
    (r'\.onDeath\(', '.die('),
    (r'\.onKillEntity\(', '.killedEntityOld('),
    (r'\.playLivingSound\(\)', '.playAmbientSound()'),
    (r'\.updateAITasks\(\)', '.customServerAiStep()'),
    (r'\.entityInit\(\)', '.defineSynchedDataPlaceholder()'),
    (r'\.initEntityAI\(\)', '.registerGoals()'),
    (r'\.applyEntityAttributes\(\)', '.applyEntityAttributesPlaceholder()'),
    (r'\.writeEntityToNBT\(', '.addAdditionalSaveData('),
    (r'\.readEntityFromNBT\(', '.readAdditionalSaveData('),
    (r'\.getBlockPathWeight\(', '.getWalkTargetValue('),
    (r'\.canDespawn\(\)', '.removeWhenFarAway(0.0)'),
    (r'\.despawnEntity\(\)', '.checkDespawn()'),
    (r'\.isOnLadder\(\)', '.onClimbable()'),
    (r'\.getExperiencePoints\(([^()]*)\)', '.getBaseExperienceReward()'),
    (r'\.getTalkInterval\(\)', '.getAmbientSoundInterval()'),
    (r'\.getMaxSpawnedInChunk\(\)', '.getMaxSpawnClusterSize()'),
    (r'\.isNoDespawnRequired\(\)', '.isPersistenceRequired()'),
    (r'\.enablePersistence\(\)', '.setPersistenceRequired()'),
    (r'\.isAIDisabled\(\)', '.isNoAi()'),
    (r'\.setSwingingArms\(', '.setAggressive('),
    (r'\.swingArm\(', '.swing('),
    (r'\.setHealth\(', '.setHealth('),
    (r'\.getDataManager\(\)', '.getEntityData()'),
    (r'\.__defineId\(', '.__defineId('),
    (r'\.isDone\(\)', '.isDone()'),
    # --- NBT
    (r'\.hasKeyType\(', '.contains('),
    (r'\.hasUUIDKey\(', '.hasUUID('),
    (r'\.hasKey\(', '.contains('),
    (r'\.getInteger\(', '.getInt('),
    (r'\.setInteger\(', '.putInt('),
    (r'\.setBoolean\(', '.putBoolean('),
    (r'\.setString\(', '.putString('),
    (r'\.setFloat\(', '.putFloat('),
    (r'\.setDouble\(', '.putDouble('),
    (r'\.setByte\(', '.putByte('),
    (r'\.setShort\(', '.putShort('),
    (r'\.setLong\(', '.putLong('),
    (r'\.setTag\(', '.put('),
    (r'\.getTagList\(', '.getList('),
    (r'\.getCompoundTagAt\(', '.getCompound('),
    (r'\.getCompoundTag\(', '.getCompound('),
    (r'\.tagCount\(\)', '.size()'),
    (r'\.appendTag\(', '.add('),
    (r'\.setUUIDTag\(', '.putUUID('),
    (r'\.getUUIDTag\(', '.getUUID('),
    (r'\.removeTag\(', '.remove('),
    # --- math / util
    (r'\bMth\.sqrt_double\(', '(float)Math.sqrt('),
    (r'\bMth\.sqrt_float\(', 'Mth.sqrt('),
    (r'\bMth\.floor_double\(', 'Mth.floor('),
    (r'\bMth\.clamp_int\(', 'Mth.clamp('),
    (r'\bMth\.clamp_float\(', 'Mth.clamp('),
    (r'\bMth\.clamp_double\(', 'Mth.clamp('),
    (r'\bMth\.sin\(', 'Mth.sin('),
    (r'\bMth\.cos\(', 'Mth.cos('),
    (r'\bMth\.atan2\(', 'Mth.atan2('),
    (r'\bMth\.wrapDegrees\(', 'Mth.wrapDegrees('),
    (r'\bMth\.ceil\(', 'Mth.ceil('),
    (r'\bMth\.abs\(', 'Mth.abs('),
    (r'\.lengthVector\(\)', '.length()'),
    (r'\.crossProduct\(', '.cross('),
    (r'\.dotProduct\(', '.dot('),
    (r'\.squareDistanceTo\(', '.distanceToSqr('),
    (r'\.addVector\(', '.add('),
    (r'\.getAverageEdgeLength\(\)', '.getSize()'),
    (r'\.calculateIntercept\(', '.clip('),
    (r'\.rotateYCCW\(\)', '.getCounterClockWise()'),
    (r'\.rotateY\(\)', '.getClockWise()'),
    # --- fields on blocks / state
    (r'\.getBlockHardness\(', '.getDestroySpeed('),
    (r'\.isFullBlock\(\)', '.isCollisionShapeFullBlock(level, pos)'),
    (r'\.getBlockState\(([^()]*(?:\([^()]*\))*[^()]*)\)\.getMaterial\(\)', r'.getBlockState(\1).getMaterialPlaceholder()'),
    # --- guava Predicate -> java Predicate
    (r'public boolean apply\(', 'public boolean test('),
    # --- sounds
    (r'\bentityPlaySound\(', 'playSound('),
    (r'\.worldPlaySoundXYZ\(', '.playSound('),
    (r'\.worldPlaySoundPos\(', '.playSound('),
    (r'\.worldPlaySoundLocal\(', '.playLocalSound('),
    (r'\.getAmbientSound\(\)', '.getAmbientSound()'),
    # --- misc
    (r'\bnew AxisAlignedBB\(', 'new AABB('),
    (r'\bnew BlockPos\(\(Entity\)this\)', 'this.blockPosition()'),
    (r'\bSRPSounds\.([A-Z0-9_]+)\b(?!\.get\(\))', r'SRPSounds.\1.get()'),
    (r'\bEnumParticleTypes\.', 'ParticleTypes.'),
    (r'\bnew int\[0\]', ''),
    (r'\.dimensionKeyPlaceholder\(\)', '.dimensionKeyPlaceholder()'),
]


# class name -> SRPEntities constant (filled by srp_translate from the original registration table)
CLASS_CONST = {}


