package com.dhanantry.scapeandrunparasites.client.model.entity.infected.special;

import com.dhanantry.scapeandrunparasites.client.legacy.ModelRenderer;
import com.dhanantry.scapeandrunparasites.client.model.ModelSRP;
import com.dhanantry.scapeandrunparasites.entity.ai.misc.EntityParasiteBase;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.Entity;

public class ModelSpeVillager
extends ModelSRP {
    public ModelRenderer mainbody;
    public ModelRenderer body;
    public ModelRenderer b;
    public ModelRenderer b_1;
    public ModelRenderer b_2;
    public ModelRenderer b_3;
    public ModelRenderer joint;
    public ModelRenderer body_1;
    public ModelRenderer jointLA;
    public ModelRenderer jointRA;
    public ModelRenderer body_2;
    public ModelRenderer jointLL;
    public ModelRenderer jointRL;
    public ModelRenderer jointdont;
    public ModelRenderer leg;
    public ModelRenderer jointLL1;
    public ModelRenderer leg_1;
    public ModelRenderer jointdont_1;
    public ModelRenderer leg_2;
    public ModelRenderer jointRL1;
    public ModelRenderer leg_3;
    public ModelRenderer jointdont_2;
    public ModelRenderer arm;
    public ModelRenderer dec;
    public ModelRenderer jointdont_3;
    public ModelRenderer arm_1;
    public ModelRenderer dec_1;
    public ModelRenderer neck;
    public ModelRenderer joint_1;
    public ModelRenderer jointM;
    public ModelRenderer head;
    public ModelRenderer head_1;
    public ModelRenderer dec_2;
    public ModelRenderer mouth;
    public ModelRenderer nose;
    public ModelRenderer m;
    public ModelRenderer jointM_1;
    public ModelRenderer mouth_1;
    public ModelRenderer teeth;
    public ModelRenderer teeth_1;
    public ModelRenderer teeth_2;
    public ModelRenderer teeth_3;
    public ModelRenderer teeth_4;
    public ModelRenderer teeth_5;

    public ModelSpeVillager() {
        this.textureWidth = 128;
        this.textureHeight = 64;
        this.mainbody = new ModelRenderer(this, 0, 0);
        this.mainbody.setRotationPoint(0.0f, 24.5f, -0.2f);
        this.mainbody.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointRL = new ModelRenderer(this, 58, 0);
        this.jointRL.setRotationPoint(-3.0f, -0.6f, -0.4f);
        this.jointRL.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.mouth_1 = new ModelRenderer(this, 0, 31);
        this.mouth_1.setRotationPoint(0.0f, 0.0f, -0.3f);
        this.mouth_1.addBox(-3.5f, 0.0f, -4.3f, 7, 2, 5, 0.0f);
        this.setRotateAngle(this.mouth_1, 0.67718774f, 0.0f, 0.0f);
        this.dec_1 = new ModelRenderer(this, 27, 17);
        this.dec_1.setRotationPoint(-0.6f, 0.0f, 0.3f);
        this.dec_1.addBox(-1.5f, -1.5f, -1.5f, 3, 3, 3, 0.0f);
        this.setRotateAngle(this.dec_1, -0.08726646f, 0.2443461f, -0.57595867f);
        this.leg_1 = new ModelRenderer(this, 75, 10);
        this.leg_1.setRotationPoint(0.0f, 1.4f, 0.3f);
        this.leg_1.addBox(-2.0f, -1.2f, -2.5f, 4, 7, 5, 0.0f);
        this.setRotateAngle(this.leg_1, 0.32463124f, 0.0f, 0.0f);
        this.arm = new ModelRenderer(this, 0, 14);
        this.arm.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.arm.addBox(0.0f, -1.0f, -1.0f, 7, 2, 2, 0.0f);
        this.setRotateAngle(this.arm, 0.0f, 0.0f, 0.82030475f);
        this.teeth_5 = new ModelRenderer(this, 94, 2);
        this.teeth_5.setRotationPoint(3.9f, 0.0f, -3.2f);
        this.teeth_5.addBox(-0.5f, -1.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth_5, 0.0f, (float)Math.PI, 0.10471976f);
        this.leg_3 = new ModelRenderer(this, 48, 13);
        this.leg_3.setRotationPoint(0.0f, 1.4f, 0.3f);
        this.leg_3.addBox(-2.0f, -1.2f, -2.5f, 4, 7, 5, 0.0f);
        this.setRotateAngle(this.leg_3, 0.32463124f, 0.0f, 0.0f);
        this.leg = new ModelRenderer(this, 113, 7);
        this.leg.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.leg.addBox(-1.5f, -1.0f, -1.5f, 3, 6, 3, 0.0f);
        this.setRotateAngle(this.leg, -0.6387905f, 0.0f, 0.0f);
        this.jointRL1 = new ModelRenderer(this, 94, 0);
        this.jointRL1.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.jointRL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.dec = new ModelRenderer(this, 18, 14);
        this.dec.setRotationPoint(-0.6f, 0.0f, -0.3f);
        this.dec.addBox(-1.5f, -1.5f, -1.5f, 3, 3, 3, 0.0f);
        this.setRotateAngle(this.dec, 0.08726646f, -0.2443461f, -0.57595867f);
        this.b = new ModelRenderer(this, 32, 0);
        this.b.setRotationPoint(0.0f, -25.0f, 4.3f);
        this.b.addBox(-1.0f, -2.0f, -1.0f, 2, 6, 3, 0.0f);
        this.setRotateAngle(this.b, -0.18849556f, 0.0f, 0.0f);
        this.body_2 = new ModelRenderer(this, 27, 9);
        this.body_2.setRotationPoint(0.0f, 4.5f, 0.0f);
        this.body_2.addBox(-4.0f, -1.0f, -2.5f, 8, 3, 5, 0.0f);
        this.body_1 = new ModelRenderer(this, 94, 0);
        this.body_1.setRotationPoint(0.0f, 5.0f, 0.0f);
        this.body_1.addBox(-3.0f, -1.0f, -2.0f, 6, 5, 5, 0.0f);
        this.setRotateAngle(this.body_1, -0.13962634f, 0.0f, 0.0f);
        this.jointM = new ModelRenderer(this, 123, 0);
        this.jointM.setRotationPoint(0.0f, -1.2f, -2.4f);
        this.jointM.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.jointdont_3 = new ModelRenderer(this, 115, 0);
        this.jointdont_3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointdont_3.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.jointdont_3, 0.19198622f, 2.7750735f, 0.0f);
        this.b_3 = new ModelRenderer(this, 80, 0);
        this.b_3.setRotationPoint(0.0f, -23.8f, 0.4f);
        this.b_3.addBox(-1.5f, -3.0f, -2.0f, 3, 6, 4, 0.0f);
        this.setRotateAngle(this.b_3, -0.25132743f, 0.0f, 0.0f);
        this.head_1 = new ModelRenderer(this, 57, 22);
        this.head_1.setRotationPoint(0.0f, -3.0f, 0.0f);
        this.head_1.addBox(-5.0f, -10.0f, -5.0f, 10, 10, 9, 0.0f);
        this.setRotateAngle(this.head_1, -0.43982297f, 0.0f, 0.0f);
        this.jointdont = new ModelRenderer(this, 75, 0);
        this.jointdont.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointdont.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.jointdont, 0.0f, -0.06981317f, 0.0f);
        this.teeth = new ModelRenderer(this, 42, 1);
        this.teeth.setRotationPoint(-2.9f, 0.0f, -4.6f);
        this.teeth.addBox(-0.5f, -1.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth, 0.10471976f, 0.0f, 0.0f);
        this.teeth_2 = new ModelRenderer(this, 25, 2);
        this.teeth_2.setRotationPoint(-3.9f, 0.0f, -3.2f);
        this.teeth_2.addBox(-0.5f, -1.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth_2, 0.0f, 0.0f, -0.10471976f);
        this.body = new ModelRenderer(this, 0, 0);
        this.body.setRotationPoint(0.0f, -21.5f, 0.8f);
        this.body.addBox(-4.5f, -2.0f, -3.0f, 9, 7, 7, 0.0f);
        this.setRotateAngle(this.body, 0.4537856f, 0.0f, 0.0f);
        this.head = new ModelRenderer(this, 90, 20);
        this.head.setRotationPoint(0.0f, -4.2f, -0.3f);
        this.head.addBox(-3.5f, 1.0f, 2.0f, 7, 7, 3, 0.0f);
        this.setRotateAngle(this.head, -0.12217305f, 0.0f, 0.0f);
        this.mouth = new ModelRenderer(this, 95, 30);
        this.mouth.setRotationPoint(0.0f, 2.0f, 4.0f);
        this.mouth.addBox(-4.5f, -2.0f, -4.0f, 9, 5, 4, 0.0f);
        this.b_2 = new ModelRenderer(this, 58, 0);
        this.b_2.setRotationPoint(0.0f, -30.3f, 1.6f);
        this.b_2.addBox(-3.0f, -2.0f, -2.5f, 6, 8, 5, 0.0f);
        this.setRotateAngle(this.b_2, 0.56548667f, 0.0f, 0.0f);
        this.jointLA = new ModelRenderer(this, 29, 0);
        this.jointLA.setRotationPoint(5.0f, 1.0f, 0.1f);
        this.jointLA.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.teeth_4 = new ModelRenderer(this, 75, 2);
        this.teeth_4.setRotationPoint(2.9f, 0.0f, -4.6f);
        this.teeth_4.addBox(-0.5f, -1.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth_4, 0.10471976f, 0.0f, 0.0f);
        this.jointdont_1 = new ModelRenderer(this, 90, 0);
        this.jointdont_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointdont_1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.jointdont_1, 0.0f, 0.06981317f, 0.0f);
        this.b_1 = new ModelRenderer(this, 42, 0);
        this.b_1.setRotationPoint(0.0f, -30.6f, 1.0f);
        this.b_1.addBox(-2.0f, -2.0f, 1.3f, 4, 5, 4, 0.0f);
        this.setRotateAngle(this.b_1, -0.06283186f, 0.0f, 0.0f);
        this.jointLL1 = new ModelRenderer(this, 79, 0);
        this.jointLL1.setRotationPoint(0.0f, 4.0f, 0.0f);
        this.jointLL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointdont_2 = new ModelRenderer(this, 111, 0);
        this.jointdont_2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointdont_2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.jointdont_2, -0.19198622f, 0.36651915f, 0.0f);
        this.leg_2 = new ModelRenderer(this, 93, 10);
        this.leg_2.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.leg_2.addBox(-1.5f, -1.0f, -1.5f, 3, 6, 3, 0.0f);
        this.setRotateAngle(this.leg_2, -0.6387905f, 0.0f, 0.0f);
        this.teeth_1 = new ModelRenderer(this, 0, 2);
        this.teeth_1.setRotationPoint(-1.6f, 0.0f, -4.6f);
        this.teeth_1.addBox(-0.5f, -2.5f, -0.5f, 1, 3, 1, 0.0f);
        this.setRotateAngle(this.teeth_1, 0.10471976f, 0.0f, 0.0f);
        this.jointRA = new ModelRenderer(this, 39, 0);
        this.jointRA.setRotationPoint(-5.0f, 1.0f, 0.1f);
        this.jointRA.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointM_1 = new ModelRenderer(this, 3, 1);
        this.jointM_1.setRotationPoint(0.0f, 3.1f, 0.0f);
        this.jointM_1.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.teeth_3 = new ModelRenderer(this, 58, 2);
        this.teeth_3.setRotationPoint(1.6f, 0.0f, -4.6f);
        this.teeth_3.addBox(-0.5f, -1.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.teeth_3, 0.10471976f, 0.0f, 0.0f);
        this.arm_1 = new ModelRenderer(this, 105, 16);
        this.arm_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.arm_1.addBox(0.0f, -1.0f, -1.0f, 7, 2, 2, 0.0f);
        this.setRotateAngle(this.arm_1, 0.0f, 0.0f, 0.82030475f);
        this.neck = new ModelRenderer(this, 0, 18);
        this.neck.setRotationPoint(0.0f, -3.0f, -1.5f);
        this.neck.addBox(-2.5f, -1.5f, -2.0f, 5, 7, 4, 0.0f);
        this.setRotateAngle(this.neck, 0.43982297f, 0.0f, 0.0f);
        this.m = new ModelRenderer(this, 36, 22);
        this.m.setRotationPoint(0.0f, 1.2f, -1.0f);
        this.m.addBox(-2.0f, -2.0f, 0.0f, 4, 6, 3, 0.0f);
        this.setRotateAngle(this.m, -0.43982297f, 0.0f, 0.0f);
        this.jointLL = new ModelRenderer(this, 54, 0);
        this.jointLL.setRotationPoint(3.0f, -0.6f, -0.4f);
        this.jointLL.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.joint_1 = new ModelRenderer(this, 119, 0);
        this.joint_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.joint_1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.dec_2 = new ModelRenderer(this, 18, 23);
        this.dec_2.setRotationPoint(0.0f, -6.0f, -3.0f);
        this.dec_2.addBox(-3.0f, 0.0f, 0.0f, 6, 5, 3, 0.0f);
        this.nose = new ModelRenderer(this, 110, 20);
        this.nose.setRotationPoint(0.0f, -1.0f, -0.7f);
        this.nose.addBox(-1.5f, -3.0f, -6.0f, 3, 5, 2, 0.0f);
        this.setRotateAngle(this.nose, 0.0f, 0.0f, 0.37699112f);
        this.joint = new ModelRenderer(this, 25, 0);
        this.joint.setRotationPoint(0.0f, -27.0f, -1.0f);
        this.joint.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.body_2.addChild(this.jointRL);
        this.jointM_1.addChild(this.mouth_1);
        this.arm_1.addChild(this.dec_1);
        this.jointLL1.addChild(this.leg_1);
        this.jointdont_2.addChild(this.arm);
        this.mouth_1.addChild(this.teeth_5);
        this.jointRL1.addChild(this.leg_3);
        this.jointdont.addChild(this.leg);
        this.leg_2.addChild(this.jointRL1);
        this.arm.addChild(this.dec);
        this.mainbody.addChild(this.b);
        this.body_1.addChild(this.body_2);
        this.body.addChild(this.body_1);
        this.neck.addChild(this.jointM);
        this.jointRA.addChild(this.jointdont_3);
        this.mainbody.addChild(this.b_3);
        this.joint_1.addChild(this.head_1);
        this.jointLL.addChild(this.jointdont);
        this.mouth_1.addChild(this.teeth);
        this.mouth_1.addChild(this.teeth_2);
        this.mainbody.addChild(this.body);
        this.joint_1.addChild(this.head);
        this.head.addChild(this.mouth);
        this.mainbody.addChild(this.b_2);
        this.body.addChild(this.jointLA);
        this.mouth_1.addChild(this.teeth_4);
        this.jointRL.addChild(this.jointdont_1);
        this.mainbody.addChild(this.b_1);
        this.leg.addChild(this.jointLL1);
        this.jointLA.addChild(this.jointdont_2);
        this.jointdont_1.addChild(this.leg_2);
        this.mouth_1.addChild(this.teeth_1);
        this.body.addChild(this.jointRA);
        this.m.addChild(this.jointM_1);
        this.mouth_1.addChild(this.teeth_3);
        this.jointdont_3.addChild(this.arm_1);
        this.joint.addChild(this.neck);
        this.jointM.addChild(this.m);
        this.body_2.addChild(this.jointLL);
        this.neck.addChild(this.joint_1);
        this.joint_1.addChild(this.dec_2);
        this.head_1.addChild(this.nose);
        this.mainbody.addChild(this.joint);
    }

    public void render(Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale) {
        super.render(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
        this.mainbody.render(scale);
    }

    public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn) {
        EntityParasiteBase parasite = (EntityParasiteBase)entityIn;
        this.jointLL.rotateAngleX = 0.0f;
        this.jointRL.rotateAngleX = 0.0f;
        this.jointLL1.rotateAngleX = 0.0f;
        this.jointRL1.rotateAngleX = 0.0f;
        this.mainbody.offsetY = 0.0f;
        this.mainbody.rotateAngleZ = 0.0f;
        this.mainbody.rotateAngleX = 0.0f;
        this.jointLA.rotateAngleX = 0.0f;
        this.jointLA.rotateAngleY = 0.0f;
        this.jointRA.rotateAngleX = 0.0f;
        this.jointRA.rotateAngleY = 0.0f;
        this.jointM.rotateAngleX = 0.0f;
        this.joint.rotateAngleX = headPitch * 0.016f;
        this.joint.rotateAngleY = netHeadYaw * 0.016f;
        byte i = parasite.getParasiteStatus();
        if (i == 0) {
            float f2;
            if (!parasite.getStillAni()) {
                float GS = 2.0f;
                float GD = 1.0f;
                this.swingX(this.jointLL, 0.3f * GS, 1.0f * GD, 1, 1.0f, 0.2f, limbSwing, limbSwingAmount);
                this.swingX(this.jointRL, 0.3f * GS, 1.0f * GD, -1, 1.0f, 0.2f, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.6f * GS, 1, limbSwing, limbSwingAmount, 0.05f);
                this.swingX(this.jointLA, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingX(this.jointRA, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
            } else {
                float f5 = Mth.cos((float)(ageInTicks * 0.111f)) * 0.2f;
                float f6 = Mth.cos((float)(ageInTicks * 0.1721f)) * 0.05f;
                this.jointLA.rotateAngleX = -1.0f * f5;
                this.jointRA.rotateAngleX = f5;
                this.jointLA.rotateAngleZ = -1.0f * f6;
                this.jointRA.rotateAngleZ = f6;
            }
            float f1 = Mth.cos((float)(ageInTicks * 0.2f)) * 0.1f;
            this.jointM.rotateAngleX = f2 = Mth.cos((float)(ageInTicks * 0.19599f)) * 0.1112f;
        } else if (i == 1) {
            if (!parasite.getStillAni()) {
                float GS = 2.0f;
                float GD = 1.0f;
                this.swingX(this.jointLL, 0.3f * GS, 1.0f * GD, 1, 1.0f, 0.2f, limbSwing, limbSwingAmount);
                this.swingX(this.jointRL, 0.3f * GS, 1.0f * GD, -1, 1.0f, 0.2f, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.6f * GS, 1, limbSwing, limbSwingAmount, 0.05f);
                this.swingX(this.jointLA, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingX(this.jointRA, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.jointLA.rotateAngleX += -1.2f;
                this.jointRA.rotateAngleX += -1.3f;
            } else {
                float f5 = Mth.cos((float)(ageInTicks * 0.111f)) * 0.2f;
                float f6 = Mth.cos((float)(ageInTicks * 0.1721f)) * 0.05f;
                this.jointLA.rotateAngleX = -1.0f * f5;
                this.jointRA.rotateAngleX = f5;
                this.jointLA.rotateAngleZ = -1.0f * f6;
                this.jointRA.rotateAngleZ = f6;
            }
            float f1 = Mth.cos((float)(ageInTicks * 0.2f)) * 0.1f;
            float f2 = Mth.cos((float)(ageInTicks * 0.5f)) * 0.2f;
            this.jointM.rotateAngleX = 0.2f + f2;
        } else if (i == 2) {
            if (!parasite.getStillAni()) {
                float GS = 0.8f;
                float GD = 0.5f;
                this.swingX(this.jointLL, 0.4f * GS, 2.1f * GD, 1, 1.0f, 0.2f, limbSwing, limbSwingAmount);
                this.swingX(this.jointLL1, 0.4f * GS, 1.0f * GD, 1, 0.0f, 0.2f, limbSwing, limbSwingAmount);
                this.swingX(this.jointRL, 0.4f * GS, 2.1f * GD, -1, 1.0f, 0.2f, limbSwing, limbSwingAmount);
                this.swingX(this.jointRL1, 0.4f * GS, 1.0f * GD, -1, 0.0f, 0.2f, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.8f * GS, 1, limbSwing, limbSwingAmount, 0.08f);
                this.mainbody.rotateAngleX = 0.0f;
                this.swingY(this.jointLA, 0.6f * GS, 1.5f * GD, -1, 2.0f, -0.8f, limbSwing, limbSwingAmount);
                this.swingX(this.jointLA, 0.6f * GS, 1.5f * GD, -1, 1.0f, 0.4f, limbSwing, limbSwingAmount);
                this.jointLA.rotateAngleX += -1.0f;
                this.swingY(this.jointRA, 0.6f * GS, 1.5f * GD, -1, 2.0f, 0.8f, limbSwing, limbSwingAmount);
                this.swingX(this.jointRA, 0.6f * GS, 1.5f * GD, 1, 1.0f, 0.4f, limbSwing, limbSwingAmount);
                this.jointRA.rotateAngleX += -1.0f;
            }
            float f1 = Mth.cos((float)(ageInTicks * 0.2f)) * 0.1f;
            float f2 = Mth.cos((float)(ageInTicks * 0.5f)) * 0.2f;
            this.jointM.rotateAngleX = 0.2f + f2;
        }
        this.underground(parasite, ageInTicks, this.mainbody);
    }
}

