package com.dhanantry.scapeandrunparasites.client.model.entity.inborn;

import com.dhanantry.scapeandrunparasites.client.legacy.ModelRenderer;
import com.dhanantry.scapeandrunparasites.client.model.ModelSRP;
import com.dhanantry.scapeandrunparasites.entity.ai.misc.EntityParasiteBase;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.Entity;

public class ModelAta
extends ModelSRP {
    public ModelRenderer mainbody;
    public ModelRenderer head;
    public ModelRenderer bottom;
    public ModelRenderer lbody;
    public ModelRenderer rbody;
    public ModelRenderer lbody_1;
    public ModelRenderer lbody_2;
    public ModelRenderer lbody_3;
    public ModelRenderer lbody_4;
    public ModelRenderer lbody_5;
    public ModelRenderer jointFLLX;
    public ModelRenderer jointMLLX;
    public ModelRenderer jointBLLX;
    public ModelRenderer jointFRLX;
    public ModelRenderer jointMRLX;
    public ModelRenderer jointBRLX;
    public ModelRenderer hair_jointRTL;
    public ModelRenderer hair_jointRTR;
    public ModelRenderer hair_jointRTM;
    public ModelRenderer JD;
    public ModelRenderer jointFLLY;
    public ModelRenderer leg;
    public ModelRenderer jointFLL1;
    public ModelRenderer leg_1;
    public ModelRenderer jointFLL2;
    public ModelRenderer leg_2;
    public ModelRenderer JD_1;
    public ModelRenderer jointMLLY;
    public ModelRenderer leg_3;
    public ModelRenderer jointMLL1;
    public ModelRenderer leg_4;
    public ModelRenderer jointMLL2;
    public ModelRenderer leg_5;
    public ModelRenderer JD_2;
    public ModelRenderer jointBLLY;
    public ModelRenderer leg_6;
    public ModelRenderer jointBLL1;
    public ModelRenderer leg_7;
    public ModelRenderer jointBLL2;
    public ModelRenderer leg_8;
    public ModelRenderer JD_3;
    public ModelRenderer jointFRLY;
    public ModelRenderer leg_9;
    public ModelRenderer jointFRL1;
    public ModelRenderer leg_10;
    public ModelRenderer jointFRL2;
    public ModelRenderer leg_11;
    public ModelRenderer JD_4;
    public ModelRenderer jointMRLY;
    public ModelRenderer leg_12;
    public ModelRenderer jointMRL1;
    public ModelRenderer leg_13;
    public ModelRenderer jointMRL2;
    public ModelRenderer leg_14;
    public ModelRenderer JD_5;
    public ModelRenderer jointBRLY;
    public ModelRenderer leg_15;
    public ModelRenderer jointBRL1;
    public ModelRenderer leg_16;
    public ModelRenderer jointBRL2;
    public ModelRenderer leg_17;
    public ModelRenderer hair;
    public ModelRenderer hair_jointL1;
    public ModelRenderer hair_1;
    public ModelRenderer hair_jointL2;
    public ModelRenderer hair_2;
    public ModelRenderer hair_jointL3;
    public ModelRenderer hair_3;
    public ModelRenderer hair_jointL4;
    public ModelRenderer hair_4;
    public ModelRenderer hair_jointL5;
    public ModelRenderer hair_5;
    public ModelRenderer hair_jointL6;
    public ModelRenderer hair_6;
    public ModelRenderer hair_7;
    public ModelRenderer hair_jointR1;
    public ModelRenderer hair_8;
    public ModelRenderer hair_jointR2;
    public ModelRenderer hair_9;
    public ModelRenderer hair_jointR3;
    public ModelRenderer hair_10;
    public ModelRenderer hair_jointR4;
    public ModelRenderer hair_11;
    public ModelRenderer hair_jointR5;
    public ModelRenderer hair_12;
    public ModelRenderer hair_jointR6;
    public ModelRenderer hair_13;
    public ModelRenderer hair_14;
    public ModelRenderer hair_jointM1;
    public ModelRenderer hair_15;
    public ModelRenderer hair_jointM2;
    public ModelRenderer hair_16;
    public ModelRenderer hair_jointM3;
    public ModelRenderer hair_17;
    public ModelRenderer hair_jointM4;
    public ModelRenderer hair_18;
    public ModelRenderer hair_jointM5;
    public ModelRenderer hair_19;
    public ModelRenderer hair_jointM6;
    public ModelRenderer hair_20;

    public ModelAta() {
        this.textureWidth = 64;
        this.textureHeight = 64;
        this.leg_3 = new ModelRenderer(this, 19, 9);
        this.leg_3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_3.addBox(-0.5f, 0.0f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_3, 0.0f, 0.0f, -0.81332344f);
        this.jointFRLY = new ModelRenderer(this, 3, 18);
        this.jointFRLY.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointFRLY.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.lbody_3 = new ModelRenderer(this, 0, 7);
        this.lbody_3.setRotationPoint(-3.5f, -7.3f, -2.3f);
        this.lbody_3.addBox(-2.0f, -3.1f, -2.0f, 4, 5, 4, 0.0f);
        this.setRotateAngle(this.lbody_3, -0.56548667f, 0.0f, 0.31415927f);
        this.leg_13 = new ModelRenderer(this, 31, 22);
        this.leg_13.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_13.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_13, 0.0f, 0.0f, 1.3159783f);
        this.hair_11 = new ModelRenderer(this, 5, 28);
        this.hair_11.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_11.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_11, -0.43633232f, 0.0f, 0.0f);
        this.hair_3 = new ModelRenderer(this, 40, 24);
        this.hair_3.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_3.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_3, -0.61086524f, 0.0f, 0.0f);
        this.bottom = new ModelRenderer(this, 0, 0);
        this.bottom.setRotationPoint(0.0f, 0.7f, -5.2f);
        this.bottom.addBox(-0.5f, -3.0f, 0.0f, 1, 3, 1, 0.0f);
        this.setRotateAngle(this.bottom, 0.61086524f, 0.0f, 0.0f);
        this.hair_12 = new ModelRenderer(this, 36, 28);
        this.hair_12.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_12.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_12, 0.61086524f, 0.0f, 0.0f);
        this.leg_7 = new ModelRenderer(this, 0, 16);
        this.leg_7.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_7.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_7, 0.0f, 0.0f, 1.3159783f);
        this.hair_jointR1 = new ModelRenderer(this, 51, 25);
        this.hair_jointR1.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointR1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointL2 = new ModelRenderer(this, 4, 24);
        this.hair_jointL2.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_17 = new ModelRenderer(this, 10, 31);
        this.hair_17.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_17.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_17, -0.6736971f, 0.0f, 0.0f);
        this.JD_2 = new ModelRenderer(this, 54, 12);
        this.JD_2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.JD_2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD_2, 0.0f, -0.36651915f, 0.0f);
        this.hair_jointRTM = new ModelRenderer(this, 26, 2);
        this.hair_jointRTM.setRotationPoint(0.0f, -3.4f, -6.0f);
        this.hair_jointRTM.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointR5 = new ModelRenderer(this, 59, 27);
        this.hair_jointR5.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointR5.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.mainbody = new ModelRenderer(this, 0, 0);
        this.mainbody.setRotationPoint(0.0f, 18.5f, 1.7f);
        this.mainbody.addBox(-1.0f, -1.0f, -5.0f, 2, 2, 5, 0.0f);
        this.hair_14 = new ModelRenderer(this, 42, 29);
        this.hair_14.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.hair_14.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_14, 2.136283f, 0.0f, 0.0f);
        this.jointMRLY = new ModelRenderer(this, 28, 21);
        this.jointMRLY.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointMRLY.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointM2 = new ModelRenderer(this, 47, 29);
        this.hair_jointM2.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointM2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.JD_3 = new ModelRenderer(this, 31, 17);
        this.JD_3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.JD_3.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD_3, 0.0f, 2.7576203f, 0.0f);
        this.hair_8 = new ModelRenderer(this, 10, 27);
        this.hair_8.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_8.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_8, 0.5794493f, 0.0f, 0.0f);
        this.jointMLL1 = new ModelRenderer(this, 42, 7);
        this.jointMLL1.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.jointMLL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg = new ModelRenderer(this, 0, 7);
        this.leg.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg.addBox(-0.5f, 0.0f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg, 0.0f, 0.0f, -0.81332344f);
        this.jointBRL2 = new ModelRenderer(this, 10, 23);
        this.jointBRL2.setRotationPoint(0.0f, 1.7f, 0.0f);
        this.jointBRL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointFLL1 = new ModelRenderer(this, 12, 7);
        this.jointFLL1.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.jointFLL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_9 = new ModelRenderer(this, 18, 27);
        this.hair_9.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_9.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_9, -0.61086524f, 0.0f, 0.0f);
        this.hair_6 = new ModelRenderer(this, 0, 26);
        this.hair_6.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_6.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_6, 0.61086524f, 0.0f, 0.0f);
        this.leg_16 = new ModelRenderer(this, 0, 23);
        this.leg_16.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_16.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_16, 0.0f, 0.0f, 1.3159783f);
        this.hair_jointL4 = new ModelRenderer(this, 45, 24);
        this.hair_jointL4.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointL4.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointR6 = new ModelRenderer(this, 41, 28);
        this.hair_jointR6.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointR6.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_11 = new ModelRenderer(this, 7, 20);
        this.leg_11.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_11.addBox(-0.5f, -0.5f, -0.5f, 1, 3, 1, 0.0f);
        this.setRotateAngle(this.leg_11, 0.0f, 0.0f, -0.7784169f);
        this.hair_1 = new ModelRenderer(this, 26, 23);
        this.hair_1.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_1, 0.5794493f, 0.0f, 0.0f);
        this.lbody_1 = new ModelRenderer(this, 46, 0);
        this.lbody_1.setRotationPoint(0.0f, -2.3f, -1.3f);
        this.lbody_1.addBox(-2.0f, -3.1f, -2.0f, 4, 6, 3, 0.0f);
        this.setRotateAngle(this.lbody_1, -0.56548667f, 0.0f, 0.0f);
        this.hair_jointL3 = new ModelRenderer(this, 34, 24);
        this.hair_jointL3.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointL3.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_6 = new ModelRenderer(this, 32, 14);
        this.leg_6.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_6.addBox(-0.5f, 0.0f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_6, 0.0f, 0.0f, -0.81332344f);
        this.leg_10 = new ModelRenderer(this, 32, 19);
        this.leg_10.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_10.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_10, 0.0f, 0.0f, 1.3159783f);
        this.hair_13 = new ModelRenderer(this, 51, 28);
        this.hair_13.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_13.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_13, 0.61086524f, 0.0f, 0.0f);
        this.jointFLLY = new ModelRenderer(this, 42, 5);
        this.jointFLLY.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointFLLY.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_12 = new ModelRenderer(this, 59, 21);
        this.leg_12.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_12.addBox(-0.5f, 0.0f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_12, 0.0f, 0.0f, -0.81332344f);
        this.hair_20 = new ModelRenderer(this, 5, 32);
        this.hair_20.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_20.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_20, 0.61086524f, 0.0f, 0.0f);
        this.jointFLLX = new ModelRenderer(this, 9, 0);
        this.jointFLLX.setRotationPoint(0.7f, 0.9f, -4.0f);
        this.jointFLLX.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointMRL1 = new ModelRenderer(this, 3, 22);
        this.jointMRL1.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.jointMRL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointFLL2 = new ModelRenderer(this, 20, 7);
        this.jointFLL2.setRotationPoint(0.0f, 1.7f, 0.0f);
        this.jointFLL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.lbody_4 = new ModelRenderer(this, 36, 9);
        this.lbody_4.setRotationPoint(0.0f, -7.3f, 1.7f);
        this.lbody_4.addBox(-3.0f, -3.1f, -4.0f, 6, 7, 6, 0.0f);
        this.setRotateAngle(this.lbody_4, -0.31415927f, 0.0f, 0.0f);
        this.jointMLLY = new ModelRenderer(this, 38, 7);
        this.jointMLLY.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointMLLY.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointRTR = new ModelRenderer(this, 13, 2);
        this.hair_jointRTR.setRotationPoint(-1.7f, -2.4f, -6.5f);
        this.hair_jointRTR.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_4 = new ModelRenderer(this, 54, 9);
        this.leg_4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_4.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_4, 0.0f, 0.0f, 1.3159783f);
        this.hair_jointM5 = new ModelRenderer(this, 23, 31);
        this.hair_jointM5.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointM5.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_4 = new ModelRenderer(this, 52, 24);
        this.hair_4.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_4.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_4, -0.43633232f, 0.0f, 0.0f);
        this.hair_5 = new ModelRenderer(this, 46, 25);
        this.hair_5.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_5.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_5, 0.61086524f, 0.0f, 0.0f);
        this.hair_jointM3 = new ModelRenderer(this, 59, 29);
        this.hair_jointM3.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointM3.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_15 = new ModelRenderer(this, 0, 30);
        this.hair_15.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_15.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_15, 0.56199604f, 0.0f, 0.0f);
        this.leg_8 = new ModelRenderer(this, 8, 16);
        this.leg_8.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_8.addBox(-0.5f, -0.5f, -0.5f, 1, 3, 1, 0.0f);
        this.setRotateAngle(this.leg_8, 0.0f, 0.0f, -0.7784169f);
        this.JD_1 = new ModelRenderer(this, 24, 7);
        this.JD_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.JD_1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD_1, 0.0f, 0.06981317f, 0.0f);
        this.jointBLLY = new ModelRenderer(this, 58, 12);
        this.jointBLLY.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointBLLY.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.lbody_5 = new ModelRenderer(this, 12, 12);
        this.lbody_5.setRotationPoint(0.0f, -8.3f, 3.7f);
        this.lbody_5.addBox(-2.0f, -3.1f, -2.0f, 4, 7, 4, 0.0f);
        this.setRotateAngle(this.lbody_5, 0.06283186f, 0.0f, 0.0f);
        this.hair_jointL1 = new ModelRenderer(this, 23, 23);
        this.hair_jointL1.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointFRL2 = new ModelRenderer(this, 3, 20);
        this.jointFRL2.setRotationPoint(0.0f, 1.7f, 0.0f);
        this.jointFRL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.lbody_2 = new ModelRenderer(this, 26, 5);
        this.lbody_2.setRotationPoint(3.5f, -7.3f, -2.3f);
        this.lbody_2.addBox(-2.0f, -3.1f, -2.0f, 4, 5, 4, 0.0f);
        this.setRotateAngle(this.lbody_2, -0.56548667f, 0.0f, -0.31415927f);
        this.hair_7 = new ModelRenderer(this, 31, 26);
        this.hair_7.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.hair_7.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_7, 2.8274333f, 0.57595867f, 0.0f);
        this.leg_1 = new ModelRenderer(this, 16, 7);
        this.leg_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_1.addBox(-0.5f, -0.5f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_1, 0.0f, 0.0f, 1.3159783f);
        this.jointBRL1 = new ModelRenderer(this, 55, 22);
        this.jointBRL1.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.jointBRL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.head = new ModelRenderer(this, 14, 0);
        this.head.setRotationPoint(0.0f, -1.6f, -4.1f);
        this.head.addBox(-2.0f, -1.5f, -3.0f, 4, 3, 4, 0.0f);
        this.setRotateAngle(this.head, -0.5235988f, 0.0f, 0.0f);
        this.jointMLLX = new ModelRenderer(this, 13, 0);
        this.jointMLLX.setRotationPoint(0.7f, 0.9f, -2.5f);
        this.jointMLLX.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointM4 = new ModelRenderer(this, 15, 31);
        this.hair_jointM4.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointM4.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_5 = new ModelRenderer(this, 28, 14);
        this.leg_5.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_5.addBox(-0.5f, -0.5f, -0.5f, 1, 3, 1, 0.0f);
        this.setRotateAngle(this.leg_5, 0.0f, 0.0f, -0.7784169f);
        this.hair_jointR4 = new ModelRenderer(this, 23, 27);
        this.hair_jointR4.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointR4.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_2 = new ModelRenderer(this, 59, 8);
        this.leg_2.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_2.addBox(-0.5f, -0.5f, -0.5f, 1, 3, 1, 0.0f);
        this.setRotateAngle(this.leg_2, 0.0f, 0.0f, -0.7784169f);
        this.jointBLL2 = new ModelRenderer(this, 4, 16);
        this.jointBLL2.setRotationPoint(0.0f, 1.7f, 0.0f);
        this.jointBLL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.rbody = new ModelRenderer(this, 38, 0);
        this.rbody.setRotationPoint(-2.0f, -1.3f, 0.0f);
        this.rbody.addBox(-1.0f, -1.5f, -2.0f, 2, 3, 2, 0.0f);
        this.setRotateAngle(this.rbody, 0.50265485f, 0.0f, -0.15707964f);
        this.jointFRL1 = new ModelRenderer(this, 0, 19);
        this.jointFRL1.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.jointFRL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_15 = new ModelRenderer(this, 51, 22);
        this.leg_15.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_15.addBox(-0.5f, 0.0f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_15, 0.0f, 0.0f, -0.81332344f);
        this.jointMLL2 = new ModelRenderer(this, 12, 9);
        this.jointMLL2.setRotationPoint(0.0f, 1.7f, 0.0f);
        this.jointMLL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointBLL1 = new ModelRenderer(this, 24, 14);
        this.jointBLL1.setRotationPoint(0.0f, 2.0f, 0.0f);
        this.jointBLL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointR3 = new ModelRenderer(this, 15, 27);
        this.hair_jointR3.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointR3.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_14 = new ModelRenderer(this, 39, 22);
        this.leg_14.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_14.addBox(-0.5f, -0.5f, -0.5f, 1, 3, 1, 0.0f);
        this.setRotateAngle(this.leg_14, 0.0f, 0.0f, -0.7784169f);
        this.JD = new ModelRenderer(this, 38, 5);
        this.JD.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.JD.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD, 0.0f, 0.38397244f, 0.0f);
        this.JD_4 = new ModelRenderer(this, 0, 21);
        this.JD_4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.JD_4.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD_4, 0.0f, 3.0717795f, 0.0f);
        this.hair_19 = new ModelRenderer(this, 26, 31);
        this.hair_19.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_19.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_19, 0.61086524f, 0.0f, 0.0f);
        this.jointFRLX = new ModelRenderer(this, 36, 0);
        this.jointFRLX.setRotationPoint(-0.7f, 0.9f, -4.0f);
        this.jointFRLX.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointMRL2 = new ModelRenderer(this, 35, 22);
        this.jointMRL2.setRotationPoint(0.0f, 1.7f, 0.0f);
        this.jointMRL2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointBRLY = new ModelRenderer(this, 47, 22);
        this.jointBRLY.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointBRLY.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.JD_5 = new ModelRenderer(this, 43, 22);
        this.JD_5.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.JD_5.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD_5, 0.0f, -2.7750735f, 0.0f);
        this.leg_17 = new ModelRenderer(this, 14, 23);
        this.leg_17.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_17.addBox(-0.5f, -0.5f, -0.5f, 1, 3, 1, 0.0f);
        this.setRotateAngle(this.leg_17, 0.0f, 0.0f, -0.7784169f);
        this.hair_jointR2 = new ModelRenderer(this, 36, 26);
        this.hair_jointR2.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointR2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointM1 = new ModelRenderer(this, 56, 28);
        this.hair_jointM1.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointM1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_18 = new ModelRenderer(this, 18, 31);
        this.hair_18.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_18.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_18, -0.43633232f, 0.0f, 0.0f);
        this.jointBRLX = new ModelRenderer(this, 57, 0);
        this.jointBRLX.setRotationPoint(-0.7f, 0.9f, -1.0f);
        this.jointBRLX.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointMRLX = new ModelRenderer(this, 44, 0);
        this.jointMRLX.setRotationPoint(-0.7f, 0.9f, -2.5f);
        this.jointMRLX.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointL6 = new ModelRenderer(this, 10, 25);
        this.hair_jointL6.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointL6.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointL5 = new ModelRenderer(this, 57, 24);
        this.hair_jointL5.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointL5.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair_jointM6 = new ModelRenderer(this, 58, 31);
        this.hair_jointM6.setRotationPoint(0.0f, 0.0f, 2.0f);
        this.hair_jointM6.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_9 = new ModelRenderer(this, 28, 18);
        this.leg_9.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_9.addBox(-0.5f, 0.0f, -0.5f, 1, 2, 1, 0.0f);
        this.setRotateAngle(this.leg_9, 0.0f, 0.0f, -0.81332344f);
        this.lbody = new ModelRenderer(this, 30, 0);
        this.lbody.setRotationPoint(2.0f, -1.3f, 0.0f);
        this.lbody.addBox(-1.0f, -1.5f, -2.0f, 2, 3, 2, 0.0f);
        this.setRotateAngle(this.lbody, 0.50265485f, 0.0f, 0.15707964f);
        this.hair_10 = new ModelRenderer(this, 26, 27);
        this.hair_10.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_10.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_10, -0.61086524f, 0.0f, 0.0f);
        this.hair_16 = new ModelRenderer(this, 31, 30);
        this.hair_16.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_16.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_16, -0.54803336f, 0.0f, 0.0f);
        this.hair_2 = new ModelRenderer(this, 5, 24);
        this.hair_2.setRotationPoint(0.0f, 0.0f, 0.5f);
        this.hair_2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair_2, -0.61086524f, 0.0f, 0.0f);
        this.jointBLLX = new ModelRenderer(this, 26, 0);
        this.jointBLLX.setRotationPoint(0.7f, 0.9f, -1.0f);
        this.jointBLLX.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.hair = new ModelRenderer(this, 18, 23);
        this.hair.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.hair.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 3, 0.0f);
        this.setRotateAngle(this.hair, 2.8274333f, -0.57595867f, 0.0f);
        this.hair_jointRTL = new ModelRenderer(this, 9, 2);
        this.hair_jointRTL.setRotationPoint(1.7f, -2.4f, -6.5f);
        this.hair_jointRTL.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointMLLY.addChild(this.leg_3);
        this.JD_3.addChild(this.jointFRLY);
        this.mainbody.addChild(this.lbody_3);
        this.jointMRL1.addChild(this.leg_13);
        this.hair_jointR4.addChild(this.hair_11);
        this.hair_jointL3.addChild(this.hair_3);
        this.mainbody.addChild(this.bottom);
        this.hair_jointR5.addChild(this.hair_12);
        this.jointBLL1.addChild(this.leg_7);
        this.hair_7.addChild(this.hair_jointR1);
        this.hair_1.addChild(this.hair_jointL2);
        this.hair_jointM3.addChild(this.hair_17);
        this.jointBLLX.addChild(this.JD_2);
        this.mainbody.addChild(this.hair_jointRTM);
        this.hair_11.addChild(this.hair_jointR5);
        this.hair_jointRTM.addChild(this.hair_14);
        this.JD_4.addChild(this.jointMRLY);
        this.hair_15.addChild(this.hair_jointM2);
        this.jointFRLX.addChild(this.JD_3);
        this.hair_jointR1.addChild(this.hair_8);
        this.leg_3.addChild(this.jointMLL1);
        this.jointFLLY.addChild(this.leg);
        this.leg_16.addChild(this.jointBRL2);
        this.leg.addChild(this.jointFLL1);
        this.hair_jointR2.addChild(this.hair_9);
        this.hair_jointL6.addChild(this.hair_6);
        this.jointBRL1.addChild(this.leg_16);
        this.hair_3.addChild(this.hair_jointL4);
        this.hair_12.addChild(this.hair_jointR6);
        this.jointFRL2.addChild(this.leg_11);
        this.hair_jointL1.addChild(this.hair_1);
        this.mainbody.addChild(this.lbody_1);
        this.hair_2.addChild(this.hair_jointL3);
        this.jointBLLY.addChild(this.leg_6);
        this.jointFRL1.addChild(this.leg_10);
        this.hair_jointR6.addChild(this.hair_13);
        this.JD.addChild(this.jointFLLY);
        this.jointMRLY.addChild(this.leg_12);
        this.hair_jointM6.addChild(this.hair_20);
        this.mainbody.addChild(this.jointFLLX);
        this.leg_12.addChild(this.jointMRL1);
        this.leg_1.addChild(this.jointFLL2);
        this.mainbody.addChild(this.lbody_4);
        this.JD_1.addChild(this.jointMLLY);
        this.mainbody.addChild(this.hair_jointRTR);
        this.jointMLL1.addChild(this.leg_4);
        this.hair_18.addChild(this.hair_jointM5);
        this.hair_jointL4.addChild(this.hair_4);
        this.hair_jointL5.addChild(this.hair_5);
        this.hair_16.addChild(this.hair_jointM3);
        this.hair_jointM1.addChild(this.hair_15);
        this.jointBLL2.addChild(this.leg_8);
        this.jointMLLX.addChild(this.JD_1);
        this.JD_2.addChild(this.jointBLLY);
        this.mainbody.addChild(this.lbody_5);
        this.hair.addChild(this.hair_jointL1);
        this.leg_10.addChild(this.jointFRL2);
        this.mainbody.addChild(this.lbody_2);
        this.hair_jointRTR.addChild(this.hair_7);
        this.jointFLL1.addChild(this.leg_1);
        this.leg_15.addChild(this.jointBRL1);
        this.mainbody.addChild(this.head);
        this.mainbody.addChild(this.jointMLLX);
        this.hair_17.addChild(this.hair_jointM4);
        this.jointMLL2.addChild(this.leg_5);
        this.hair_10.addChild(this.hair_jointR4);
        this.jointFLL2.addChild(this.leg_2);
        this.leg_7.addChild(this.jointBLL2);
        this.mainbody.addChild(this.rbody);
        this.leg_9.addChild(this.jointFRL1);
        this.jointBRLY.addChild(this.leg_15);
        this.leg_4.addChild(this.jointMLL2);
        this.leg_6.addChild(this.jointBLL1);
        this.hair_9.addChild(this.hair_jointR3);
        this.jointMRL2.addChild(this.leg_14);
        this.jointFLLX.addChild(this.JD);
        this.jointMRLX.addChild(this.JD_4);
        this.hair_jointM5.addChild(this.hair_19);
        this.mainbody.addChild(this.jointFRLX);
        this.leg_13.addChild(this.jointMRL2);
        this.JD_5.addChild(this.jointBRLY);
        this.jointBRLX.addChild(this.JD_5);
        this.jointBRL2.addChild(this.leg_17);
        this.hair_8.addChild(this.hair_jointR2);
        this.hair_14.addChild(this.hair_jointM1);
        this.hair_jointM4.addChild(this.hair_18);
        this.mainbody.addChild(this.jointBRLX);
        this.mainbody.addChild(this.jointMRLX);
        this.hair_5.addChild(this.hair_jointL6);
        this.hair_4.addChild(this.hair_jointL5);
        this.hair_19.addChild(this.hair_jointM6);
        this.jointFRLY.addChild(this.leg_9);
        this.mainbody.addChild(this.lbody);
        this.hair_jointR3.addChild(this.hair_10);
        this.hair_jointM2.addChild(this.hair_16);
        this.hair_jointL2.addChild(this.hair_2);
        this.mainbody.addChild(this.jointBLLX);
        this.hair_jointRTL.addChild(this.hair);
        this.mainbody.addChild(this.hair_jointRTL);
    }

    public void render(Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale) {
        super.render(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
        this.mainbody.render(scale);
    }

    public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn) {
        EntityParasiteBase parasite = (EntityParasiteBase)entityIn;
        this.jointFLLX.rotateAngleY = 0.0f;
        this.jointFLLY.rotateAngleZ = 0.0f;
        this.jointFRLX.rotateAngleY = 0.0f;
        this.jointFRLY.rotateAngleZ = 0.0f;
        this.jointFLL1.rotateAngleZ = 0.0f;
        this.jointFRL1.rotateAngleZ = 0.0f;
        this.jointMLLX.rotateAngleY = 0.0f;
        this.jointMLLY.rotateAngleZ = 0.0f;
        this.jointMRLX.rotateAngleY = 0.0f;
        this.jointMRLY.rotateAngleZ = 0.0f;
        this.jointBLLX.rotateAngleY = 0.0f;
        this.jointBLLY.rotateAngleZ = 0.0f;
        this.jointBRLX.rotateAngleY = 0.0f;
        this.jointBRLY.rotateAngleZ = 0.0f;
        this.mainbody.offsetY = 0.0f;
        this.mainbody.rotateAngleX = 0.0f;
        byte i = parasite.getParasiteStatus();
        if (i == 0) {
            if (!parasite.getStillAni()) {
                float GS = 2.7f;
                float GD = 0.4f;
                this.swingY(this.jointFLLX, 0.2f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFLLY, 0.2f * GS, 1.0f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointFRLX, 0.2f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFRLY, 0.2f * GS, 1.0f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointMLLX, 0.2f * GS, 1.5f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointMLLY, 0.2f * GS, 1.0f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointMRLX, 0.2f * GS, 1.5f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointMRLY, 0.2f * GS, 1.0f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBLLX, 0.2f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBLLY, 0.2f * GS, 1.0f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBRLX, 0.2f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBRLY, 0.2f * GS, 1.0f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.4f * GS, 1, limbSwing, limbSwingAmount, 0.02f);
            }
            float f2 = Mth.cos((float)(ageInTicks * 0.1f)) * 0.05f;
            float nf2 = -1.0f * f2;
            this.hair_jointM1.rotateAngleX = f2;
            this.hair_jointM2.rotateAngleX = f2;
            this.hair_jointM3.rotateAngleX = f2;
            this.hair_jointM4.rotateAngleX = f2;
            this.hair_jointM5.rotateAngleX = f2;
            this.hair_jointM6.rotateAngleX = f2;
            this.hair_jointL1.rotateAngleX = nf2;
            this.hair_jointL2.rotateAngleX = nf2;
            this.hair_jointL3.rotateAngleX = nf2;
            this.hair_jointL4.rotateAngleX = nf2;
            this.hair_jointL5.rotateAngleX = nf2;
            this.hair_jointL6.rotateAngleX = nf2;
            this.hair_jointR1.rotateAngleX = nf2;
            this.hair_jointR2.rotateAngleX = nf2;
            this.hair_jointR3.rotateAngleX = nf2;
            this.hair_jointR4.rotateAngleX = nf2;
            this.hair_jointR5.rotateAngleX = nf2;
            this.hair_jointR6.rotateAngleX = nf2;
        } else if (i == 1) {
            if (!parasite.getStillAni()) {
                float GS = 2.7f;
                float GD = 0.4f;
                this.swingY(this.jointFLLX, 0.2f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFLLY, 0.2f * GS, 1.0f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointFRLX, 0.2f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFRLY, 0.2f * GS, 1.0f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointMLLX, 0.2f * GS, 1.5f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointMLLY, 0.2f * GS, 1.0f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointMRLX, 0.2f * GS, 1.5f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointMRLY, 0.2f * GS, 1.0f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBLLX, 0.2f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBLLY, 0.2f * GS, 1.0f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBRLX, 0.2f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBRLY, 0.2f * GS, 1.0f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.4f * GS, 1, limbSwing, limbSwingAmount, 0.02f);
            }
            float f2 = 0.3f + Mth.cos((float)(ageInTicks * 0.8f)) * 0.08f;
            float nf2 = 0.6f + -1.0f * f2;
            this.hair_jointM1.rotateAngleX = f2;
            this.hair_jointM2.rotateAngleX = f2;
            this.hair_jointM3.rotateAngleX = f2;
            this.hair_jointM4.rotateAngleX = f2;
            this.hair_jointM5.rotateAngleX = f2;
            this.hair_jointM6.rotateAngleX = f2;
            this.hair_jointL1.rotateAngleX = nf2;
            this.hair_jointL2.rotateAngleX = nf2;
            this.hair_jointL3.rotateAngleX = nf2;
            this.hair_jointL4.rotateAngleX = nf2;
            this.hair_jointL5.rotateAngleX = nf2;
            this.hair_jointL6.rotateAngleX = nf2;
            this.hair_jointR1.rotateAngleX = nf2;
            this.hair_jointR2.rotateAngleX = nf2;
            this.hair_jointR3.rotateAngleX = nf2;
            this.hair_jointR4.rotateAngleX = nf2;
            this.hair_jointR5.rotateAngleX = nf2;
            this.hair_jointR6.rotateAngleX = nf2;
        } else if (i == 2) {
            if (!parasite.getStillAni()) {
                float GS = 1.2f;
                float GD = 0.5f;
                this.swingY(this.jointFLLX, 0.6f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFLLY, 0.6f * GS, 1.0f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointFRLX, 0.6f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointFRLY, 0.6f * GS, 1.0f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointMLLX, 0.6f * GS, 1.5f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointMLLY, 0.6f * GS, 1.0f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointMRLX, 0.6f * GS, 1.5f * GD, 1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointMRLY, 0.6f * GS, 1.0f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBLLX, 0.6f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBLLY, 0.6f * GS, 1.0f * GD, 1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.swingY(this.jointBRLX, 0.6f * GS, 1.5f * GD, -1, limbSwing, limbSwingAmount);
                this.swingZ(this.jointBRLY, 0.6f * GS, 1.0f * GD, -1, 1.0f, 0.0f, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 1.2f * GS, 1, limbSwing, limbSwingAmount, 0.02f);
            }
            float f2 = 0.3f + Mth.cos((float)(ageInTicks * 0.8f)) * 0.08f;
            float nf2 = 0.6f + -1.0f * f2;
            this.hair_jointM1.rotateAngleX = f2;
            this.hair_jointM2.rotateAngleX = f2;
            this.hair_jointM3.rotateAngleX = f2;
            this.hair_jointM4.rotateAngleX = f2;
            this.hair_jointM5.rotateAngleX = f2;
            this.hair_jointM6.rotateAngleX = f2;
            this.hair_jointL1.rotateAngleX = nf2;
            this.hair_jointL2.rotateAngleX = nf2;
            this.hair_jointL3.rotateAngleX = nf2;
            this.hair_jointL4.rotateAngleX = nf2;
            this.hair_jointL5.rotateAngleX = nf2;
            this.hair_jointL6.rotateAngleX = nf2;
            this.hair_jointR1.rotateAngleX = nf2;
            this.hair_jointR2.rotateAngleX = nf2;
            this.hair_jointR3.rotateAngleX = nf2;
            this.hair_jointR4.rotateAngleX = nf2;
            this.hair_jointR5.rotateAngleX = nf2;
            this.hair_jointR6.rotateAngleX = nf2;
        } else if (i == 10) {
            float f2 = Mth.cos((float)(ageInTicks * 0.9f)) * 0.04f;
            this.jointFLLY.rotateAngleZ = -0.3f + f2;
            this.jointFRLY.rotateAngleZ = -0.3f + f2;
            this.jointFLL1.rotateAngleZ = -0.1f + f2 * 0.5f;
            this.jointFRL1.rotateAngleZ = -0.1f + f2 * 0.5f;
            this.jointMLLY.rotateAngleZ = f2 * -1.2f;
            this.jointMRLY.rotateAngleZ = f2 * -1.2f;
            this.jointBLLY.rotateAngleZ = f2 * 1.2f;
            this.jointBRLY.rotateAngleZ = f2 * 1.2f;
            this.mainbody.rotateAngleX = -0.9f;
            f2 = 0.3f + Mth.cos((float)(ageInTicks * 0.8f)) * 0.08f;
            float nf2 = 0.6f + -1.0f * f2;
            this.hair_jointM1.rotateAngleX = f2;
            this.hair_jointM2.rotateAngleX = f2;
            this.hair_jointM3.rotateAngleX = f2;
            this.hair_jointM4.rotateAngleX = f2;
            this.hair_jointM5.rotateAngleX = f2;
            this.hair_jointM6.rotateAngleX = f2;
            this.hair_jointL1.rotateAngleX = nf2;
            this.hair_jointL2.rotateAngleX = nf2;
            this.hair_jointL3.rotateAngleX = nf2;
            this.hair_jointL4.rotateAngleX = nf2;
            this.hair_jointL5.rotateAngleX = nf2;
            this.hair_jointL6.rotateAngleX = nf2;
            this.hair_jointR1.rotateAngleX = nf2;
            this.hair_jointR2.rotateAngleX = nf2;
            this.hair_jointR3.rotateAngleX = nf2;
            this.hair_jointR4.rotateAngleX = nf2;
            this.hair_jointR5.rotateAngleX = nf2;
            this.hair_jointR6.rotateAngleX = nf2;
        }
        this.underground(parasite, ageInTicks, this.mainbody);
    }
}

