package com.dhanantry.scapeandrunparasites.client.model.entity.infected;

import com.dhanantry.scapeandrunparasites.client.legacy.ModelRenderer;
import com.dhanantry.scapeandrunparasites.client.model.ModelSRP;
import com.dhanantry.scapeandrunparasites.entity.monster.infected.EntityInfSheep;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.Entity;

public class ModelInfSheep
extends ModelSRP {
    public ModelRenderer mainbody;
    public ModelRenderer body;
    public ModelRenderer body_1;
    public ModelRenderer JD;
    public ModelRenderer neck;
    public ModelRenderer JD_1;
    public ModelRenderer dec;
    public ModelRenderer body_2;
    public ModelRenderer popX5;
    public ModelRenderer popX6;
    public ModelRenderer popX7;
    public ModelRenderer popX8;
    public ModelRenderer popY6;
    public ModelRenderer popY7;
    public ModelRenderer popY8;
    public ModelRenderer popY9;
    public ModelRenderer popY10;
    public ModelRenderer popY11;
    public ModelRenderer popX9;
    public ModelRenderer popX10;
    public ModelRenderer popX11;
    public ModelRenderer popX12;
    public ModelRenderer popX13;
    public ModelRenderer popX14;
    public ModelRenderer popX15;
    public ModelRenderer popY12;
    public ModelRenderer popY13;
    public ModelRenderer popY14;
    public ModelRenderer popY15;
    public ModelRenderer popY16;
    public ModelRenderer popY17;
    public ModelRenderer popY18;
    public ModelRenderer popY19;
    public ModelRenderer popY20;
    public ModelRenderer popY21;
    public ModelRenderer JD_2;
    public ModelRenderer JD_3;
    public ModelRenderer popY1;
    public ModelRenderer popY2;
    public ModelRenderer popY3;
    public ModelRenderer popY4;
    public ModelRenderer popY5;
    public ModelRenderer popZ1;
    public ModelRenderer popZ2;
    public ModelRenderer popX1;
    public ModelRenderer popX2;
    public ModelRenderer popX3;
    public ModelRenderer popX4;
    public ModelRenderer jointBLL;
    public ModelRenderer leg;
    public ModelRenderer jointBLL1;
    public ModelRenderer dec_1;
    public ModelRenderer leg_1;
    public ModelRenderer leg_2;
    public ModelRenderer jointBRL;
    public ModelRenderer leg_3;
    public ModelRenderer jointBRL1;
    public ModelRenderer leg_4;
    public ModelRenderer leg_5;
    public ModelRenderer jointFLL;
    public ModelRenderer leg_6;
    public ModelRenderer jointFLL1;
    public ModelRenderer leg_7;
    public ModelRenderer leg_8;
    public ModelRenderer jointdont;
    public ModelRenderer jointH;
    public ModelRenderer head;
    public ModelRenderer popX16;
    public ModelRenderer mouth;
    public ModelRenderer mouthg;
    public ModelRenderer jointM;
    public ModelRenderer mouth_1;
    public ModelRenderer teeth;
    public ModelRenderer teeth_1;
    public ModelRenderer teeth_2;
    public ModelRenderer teeth_3;
    public ModelRenderer teeth_4;
    public ModelRenderer jointFRL;
    public ModelRenderer leg_9;
    public ModelRenderer jointFRL1;
    public ModelRenderer leg_10;
    public ModelRenderer leg_11;
    public ModelRenderer dec_2;

    public ModelInfSheep() {
        this.textureWidth = 128;
        this.textureHeight = 40;
        this.popX2 = new ModelRenderer(this, 52, 7);
        this.popX2.setRotationPoint(-2.5f, 0.0f, -1.2f);
        this.popX2.addBox(-2.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.popY4 = new ModelRenderer(this, 102, 5);
        this.popY4.setRotationPoint(-0.4f, -1.6f, -1.0f);
        this.popY4.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.popY5 = new ModelRenderer(this, 104, 6);
        this.popY5.setRotationPoint(-2.0f, -1.6f, 0.7f);
        this.popY5.addBox(-1.0f, 0.0f, -1.0f, 2, 2, 2, 0.0f);
        this.popY2 = new ModelRenderer(this, 94, 5);
        this.popY2.setRotationPoint(0.0f, -1.6f, 1.0f);
        this.popY2.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.jointFLL = new ModelRenderer(this, 118, 9);
        this.jointFLL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointFLL.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.popX8 = new ModelRenderer(this, 86, 0);
        this.popX8.setRotationPoint(1.5f, 2.3f, 0.8f);
        this.popX8.addBox(0.0f, 0.0f, 0.0f, 2, 2, 2, 0.0f);
        this.jointH = new ModelRenderer(this, 70, 10);
        this.jointH.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointH.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.popZ2 = new ModelRenderer(this, 82, 6);
        this.popZ2.setRotationPoint(-0.5f, 0.0f, 1.5f);
        this.popZ2.addBox(0.0f, 0.0f, 0.0f, 1, 1, 2, 0.0f);
        this.JD_3 = new ModelRenderer(this, 53, 5);
        this.JD_3.setRotationPoint(-3.0f, 5.7f, 1.1f);
        this.JD_3.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.dec_1 = new ModelRenderer(this, 78, 9);
        this.dec_1.setRotationPoint(-0.6f, 1.3f, 1.8f);
        this.dec_1.addBox(-1.0f, -1.0f, -1.0f, 2, 4, 2, 0.0f);
        this.setRotateAngle(this.dec_1, 0.15707964f, 0.0f, -0.33161256f);
        this.teeth_1 = new ModelRenderer(this, 121, 11);
        this.teeth_1.setRotationPoint(-2.9f, 0.0f, -2.2f);
        this.teeth_1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.teeth_1, 0.0f, 0.0f, -0.10471976f);
        this.leg_9 = new ModelRenderer(this, 40, 23);
        this.leg_9.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_9.addBox(-2.0f, -1.0f, -2.0f, 4, 6, 4, 0.0f);
        this.popY1 = new ModelRenderer(this, 80, 5);
        this.popY1.setRotationPoint(2.0f, -1.6f, 1.0f);
        this.popY1.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.popY18 = new ModelRenderer(this, 90, 4);
        this.popY18.setRotationPoint(1.1f, 4.0f, 0.8f);
        this.popY18.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.popX7 = new ModelRenderer(this, 82, 0);
        this.popX7.setRotationPoint(1.5f, 2.3f, 3.5f);
        this.popX7.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.jointFLL1 = new ModelRenderer(this, 122, 9);
        this.jointFLL1.setRotationPoint(0.0f, 5.0f, 0.0f);
        this.jointFLL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointM = new ModelRenderer(this, 74, 10);
        this.jointM.setRotationPoint(0.0f, -1.4f, -0.1f);
        this.jointM.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.JD_1 = new ModelRenderer(this, 35, 0);
        this.JD_1.setRotationPoint(-2.8f, 5.7f, 4.7f);
        this.JD_1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD_1, 0.29670596f, 0.0f, 0.0f);
        this.dec = new ModelRenderer(this, 49, 0);
        this.dec.setRotationPoint(3.8f, 0.9f, 3.0f);
        this.dec.addBox(-1.0f, -1.0f, -1.0f, 2, 3, 2, 0.0f);
        this.setRotateAngle(this.dec, -0.43633232f, 0.0f, -0.12217305f);
        this.popX9 = new ModelRenderer(this, 118, 0);
        this.popX9.setRotationPoint(-1.5f, 0.6f, 4.7f);
        this.popX9.addBox(-2.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.leg_1 = new ModelRenderer(this, 109, 9);
        this.leg_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_1.addBox(-1.5f, 0.0f, -1.5f, 3, 6, 3, 0.0f);
        this.setRotateAngle(this.leg_1, 0.0f, -0.08726646f, 0.0f);
        this.popY9 = new ModelRenderer(this, 106, 0);
        this.popY9.setRotationPoint(-0.7f, 1.0f, 4.3f);
        this.popY9.addBox(0.0f, -2.0f, 0.0f, 1, 2, 1, 0.0f);
        this.body_1 = new ModelRenderer(this, 30, 0);
        this.body_1.setRotationPoint(0.0f, 0.7f, 6.4f);
        this.body_1.addBox(-2.5f, 0.0f, -1.0f, 5, 5, 9, 0.0f);
        this.setRotateAngle(this.body_1, 0.4712389f, 0.0f, 0.0f);
        this.popY14 = new ModelRenderer(this, 109, 3);
        this.popY14.setRotationPoint(-0.5f, 4.0f, 4.0f);
        this.popY14.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.teeth = new ModelRenderer(this, 108, 10);
        this.teeth.setRotationPoint(-1.5f, 0.0f, -3.6f);
        this.teeth.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.teeth, 0.10471976f, 0.0f, 0.0f);
        this.popY16 = new ModelRenderer(this, 0, 4);
        this.popY16.setRotationPoint(-2.0f, 4.0f, 2.5f);
        this.popY16.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.popY17 = new ModelRenderer(this, 86, 4);
        this.popY17.setRotationPoint(-2.0f, 4.0f, 0.8f);
        this.popY17.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.leg_4 = new ModelRenderer(this, 0, 14);
        this.leg_4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_4.addBox(-1.5f, 0.0f, -1.5f, 3, 6, 3, 0.0f);
        this.setRotateAngle(this.leg_4, 0.0f, 0.08726646f, 0.0f);
        this.leg_7 = new ModelRenderer(this, 44, 14);
        this.leg_7.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_7.addBox(-1.5f, 0.0f, -1.5f, 3, 6, 3, 0.0f);
        this.setRotateAngle(this.leg_7, 0.0f, -0.08726646f, 0.0f);
        this.popY19 = new ModelRenderer(this, 117, 4);
        this.popY19.setRotationPoint(-0.5f, 4.0f, 0.8f);
        this.popY19.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.popY20 = new ModelRenderer(this, 121, 4);
        this.popY20.setRotationPoint(-1.3f, 4.0f, -0.7f);
        this.popY20.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.teeth_3 = new ModelRenderer(this, 121, 13);
        this.teeth_3.setRotationPoint(2.9f, 0.0f, -2.2f);
        this.teeth_3.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.teeth_3, 0.0f, (float)Math.PI, 0.10471976f);
        this.jointFRL = new ModelRenderer(this, 24, 14);
        this.jointFRL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointFRL.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.body_2 = new ModelRenderer(this, 58, 0);
        this.body_2.setRotationPoint(0.0f, 0.0f, 8.0f);
        this.body_2.addBox(-3.5f, -0.5f, -1.5f, 7, 6, 4, 0.0f);
        this.setRotateAngle(this.body_2, -0.17453292f, 0.0f, 0.0f);
        this.popX10 = new ModelRenderer(this, 0, 2);
        this.popX10.setRotationPoint(-1.5f, 0.6f, 2.7f);
        this.popX10.addBox(-2.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.jointBLL = new ModelRenderer(this, 34, 6);
        this.jointBLL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointBLL.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.popX12 = new ModelRenderer(this, 117, 2);
        this.popX12.setRotationPoint(-1.5f, 2.2f, 2.9f);
        this.popX12.addBox(-2.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.popX16 = new ModelRenderer(this, 102, 10);
        this.popX16.setRotationPoint(2.6f, 1.0f, -1.0f);
        this.popX16.addBox(-1.0f, -0.5f, -0.5f, 2, 1, 1, 0.0f);
        this.setRotateAngle(this.popX16, 0.4712389f, 0.0f, 0.0f);
        this.JD = new ModelRenderer(this, 23, 0);
        this.JD.setRotationPoint(2.8f, 5.7f, 4.7f);
        this.JD.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD, 0.29670596f, 0.0f, 0.0f);
        this.popX14 = new ModelRenderer(this, 93, 3);
        this.popX14.setRotationPoint(-1.5f, 3.7f, 3.6f);
        this.popX14.addBox(-2.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.head = new ModelRenderer(this, 74, 19);
        this.head.setRotationPoint(0.0f, 1.7f, -2.0f);
        this.head.addBox(-3.0f, -4.0f, -6.0f, 6, 4, 8, 0.0f);
        this.dec_2 = new ModelRenderer(this, 84, 14);
        this.dec_2.setRotationPoint(0.0f, 2.0f, -1.0f);
        this.dec_2.addBox(-1.0f, -1.0f, -1.0f, 1, 2, 2, 0.0f);
        this.setRotateAngle(this.dec_2, 0.12217305f, 0.0f, -0.41887903f);
        this.popY15 = new ModelRenderer(this, 113, 3);
        this.popY15.setRotationPoint(0.2f, 4.0f, 2.5f);
        this.popY15.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.mouth = new ModelRenderer(this, 8, 20);
        this.mouth.setRotationPoint(0.0f, 0.0f, -0.3f);
        this.mouth.addBox(-3.0f, 0.0f, -2.0f, 6, 2, 4, 0.0f);
        this.popY6 = new ModelRenderer(this, 94, 0);
        this.popY6.setRotationPoint(0.8f, 1.0f, 5.1f);
        this.popY6.addBox(0.0f, -2.0f, 0.0f, 1, 2, 1, 0.0f);
        this.JD_2 = new ModelRenderer(this, 57, 2);
        this.JD_2.setRotationPoint(3.0f, 5.7f, 1.1f);
        this.JD_2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.popX13 = new ModelRenderer(this, 81, 3);
        this.popX13.setRotationPoint(-1.5f, 2.2f, 4.5f);
        this.popX13.addBox(-2.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.leg_11 = new ModelRenderer(this, 24, 24);
        this.leg_11.setRotationPoint(0.0f, 6.3f, 0.0f);
        this.leg_11.addBox(-2.0f, -1.0f, -2.0f, 4, 2, 4, 0.0f);
        this.teeth_4 = new ModelRenderer(this, 9, 14);
        this.teeth_4.setRotationPoint(0.0f, 0.0f, -3.6f);
        this.teeth_4.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.teeth_4, 0.10471976f, 0.0f, 0.0f);
        this.jointFRL1 = new ModelRenderer(this, 28, 14);
        this.jointFRL1.setRotationPoint(0.0f, 5.0f, 0.0f);
        this.jointFRL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.popX3 = new ModelRenderer(this, 88, 7);
        this.popX3.setRotationPoint(-2.5f, 3.1f, -1.2f);
        this.popX3.addBox(-2.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.mouthg = new ModelRenderer(this, 0, 33);
        this.mouthg.setRotationPoint(0.0f, 2.0f, -1.8f);
        this.mouthg.addBox(-2.0f, -3.3f, -0.2f, 4, 3, 3, 0.0f);
        this.setRotateAngle(this.mouthg, 0.2443461f, 0.0f, 0.0f);
        this.popY8 = new ModelRenderer(this, 102, 0);
        this.popY8.setRotationPoint(-0.7f, 1.0f, 2.6f);
        this.popY8.addBox(0.0f, -2.0f, 0.0f, 1, 2, 1, 0.0f);
        this.leg_5 = new ModelRenderer(this, 12, 14);
        this.leg_5.setRotationPoint(0.0f, 6.3f, 0.0f);
        this.leg_5.addBox(-2.0f, -1.0f, -2.0f, 4, 2, 4, 0.0f);
        this.popY21 = new ModelRenderer(this, 49, 5);
        this.popY21.setRotationPoint(0.8f, 4.0f, -0.7f);
        this.popY21.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.leg_6 = new ModelRenderer(this, 28, 14);
        this.leg_6.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_6.addBox(-2.0f, -1.0f, -2.0f, 4, 6, 4, 0.0f);
        this.popY3 = new ModelRenderer(this, 98, 5);
        this.popY3.setRotationPoint(1.4f, -1.6f, -1.0f);
        this.popY3.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.popY12 = new ModelRenderer(this, 123, 1);
        this.popY12.setRotationPoint(-2.0f, 4.0f, 4.0f);
        this.popY12.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.leg_2 = new ModelRenderer(this, 54, 10);
        this.leg_2.setRotationPoint(0.0f, 6.3f, 0.0f);
        this.leg_2.addBox(-2.0f, -1.0f, -2.0f, 4, 2, 4, 0.0f);
        this.jointBRL1 = new ModelRenderer(this, 88, 9);
        this.jointBRL1.setRotationPoint(0.0f, 5.0f, 0.0f);
        this.jointBRL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.jointBLL1 = new ModelRenderer(this, 121, 7);
        this.jointBLL1.setRotationPoint(0.0f, 5.0f, 0.0f);
        this.jointBLL1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.popX11 = new ModelRenderer(this, 76, 2);
        this.popX11.setRotationPoint(-1.5f, 2.2f, 1.2f);
        this.popX11.addBox(-2.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.popX15 = new ModelRenderer(this, 99, 3);
        this.popX15.setRotationPoint(-1.5f, 3.7f, 1.8f);
        this.popX15.addBox(-2.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.popX1 = new ModelRenderer(this, 110, 6);
        this.popX1.setRotationPoint(2.5f, 0.0f, -0.8f);
        this.popX1.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.leg_10 = new ModelRenderer(this, 115, 21);
        this.leg_10.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_10.addBox(-1.5f, 0.0f, -1.5f, 3, 6, 3, 0.0f);
        this.setRotateAngle(this.leg_10, 0.0f, 0.08726646f, 0.0f);
        this.jointBRL = new ModelRenderer(this, 84, 9);
        this.jointBRL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointBRL.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.popX5 = new ModelRenderer(this, 55, 0);
        this.popX5.setRotationPoint(1.5f, 0.9f, 4.8f);
        this.popX5.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.mouth_1 = new ModelRenderer(this, 52, 19);
        this.mouth_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.mouth_1.addBox(-2.5f, 0.0f, -3.3f, 5, 2, 4, 0.0f);
        this.setRotateAngle(this.mouth_1, 0.13962634f, 0.0f, 0.0f);
        this.popZ1 = new ModelRenderer(this, 30, 6);
        this.popZ1.setRotationPoint(1.5f, 0.0f, 1.5f);
        this.popZ1.addBox(0.0f, 0.0f, 0.0f, 1, 1, 2, 0.0f);
        this.popY10 = new ModelRenderer(this, 110, 0);
        this.popY10.setRotationPoint(-2.2f, 1.0f, 3.1f);
        this.popY10.addBox(0.0f, -2.0f, 0.0f, 1, 2, 1, 0.0f);
        this.leg_8 = new ModelRenderer(this, 102, 18);
        this.leg_8.setRotationPoint(0.0f, 6.3f, 0.0f);
        this.leg_8.addBox(-2.0f, -1.0f, -2.0f, 4, 2, 4, 0.0f);
        this.teeth_2 = new ModelRenderer(this, 66, 12);
        this.teeth_2.setRotationPoint(1.5f, 0.0f, -3.6f);
        this.teeth_2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.teeth_2, 0.10471976f, 0.0f, 0.0f);
        this.popY7 = new ModelRenderer(this, 98, 0);
        this.popY7.setRotationPoint(0.8f, 1.0f, 3.1f);
        this.popY7.addBox(0.0f, -2.0f, 0.0f, 1, 2, 1, 0.0f);
        this.popY13 = new ModelRenderer(this, 105, 3);
        this.popY13.setRotationPoint(1.2f, 4.0f, 4.0f);
        this.popY13.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.neck = new ModelRenderer(this, 25, 0);
        this.neck.setRotationPoint(0.0f, -1.2f, 2.2f);
        this.neck.addBox(-2.0f, -0.7f, -1.0f, 4, 4, 2, 0.0f);
        this.popY11 = new ModelRenderer(this, 114, 0);
        this.popY11.setRotationPoint(-2.2f, 1.0f, 4.9f);
        this.popY11.addBox(0.0f, -2.0f, 0.0f, 1, 2, 1, 0.0f);
        this.leg = new ModelRenderer(this, 90, 8);
        this.leg.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg.addBox(-2.0f, -1.0f, -2.0f, 4, 7, 4, 0.0f);
        this.popX4 = new ModelRenderer(this, 115, 7);
        this.popX4.setRotationPoint(2.5f, 1.6f, -1.1f);
        this.popX4.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.popX6 = new ModelRenderer(this, 76, 0);
        this.popX6.setRotationPoint(1.5f, 0.6f, 2.8f);
        this.popX6.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.leg_3 = new ModelRenderer(this, 66, 12);
        this.leg_3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_3.addBox(-2.0f, -1.0f, -2.0f, 4, 7, 4, 0.0f);
        this.jointdont = new ModelRenderer(this, 66, 10);
        this.jointdont.setRotationPoint(0.0f, 0.0f, -0.5f);
        this.jointdont.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.jointdont, 0.29670596f, 0.0f, 0.0f);
        this.mainbody = new ModelRenderer(this, 0, 0);
        this.mainbody.setRotationPoint(0.0f, 14.9f, 0.0f);
        this.mainbody.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.body = new ModelRenderer(this, 0, 0);
        this.body.setRotationPoint(0.0f, -10.0f, -8.0f);
        this.body.addBox(-4.0f, -1.0f, 1.0f, 8, 7, 7, 0.0f);
        this.setRotateAngle(this.body, -0.29670596f, 0.0f, 0.0f);
        this.body_2.addChild(this.popX2);
        this.body_2.addChild(this.popY4);
        this.body_2.addChild(this.popY5);
        this.body_2.addChild(this.popY2);
        this.JD.addChild(this.jointFLL);
        this.body_1.addChild(this.popX8);
        this.jointdont.addChild(this.jointH);
        this.body_2.addChild(this.popZ2);
        this.body_2.addChild(this.JD_3);
        this.leg.addChild(this.dec_1);
        this.mouth_1.addChild(this.teeth_1);
        this.jointFRL.addChild(this.leg_9);
        this.body_2.addChild(this.popY1);
        this.body_1.addChild(this.popY18);
        this.body_1.addChild(this.popX7);
        this.leg_6.addChild(this.jointFLL1);
        this.mouthg.addChild(this.jointM);
        this.body.addChild(this.JD_1);
        this.body.addChild(this.dec);
        this.body_1.addChild(this.popX9);
        this.jointBLL1.addChild(this.leg_1);
        this.body_1.addChild(this.popY9);
        this.body.addChild(this.body_1);
        this.body_1.addChild(this.popY14);
        this.mouth_1.addChild(this.teeth);
        this.body_1.addChild(this.popY16);
        this.body_1.addChild(this.popY17);
        this.jointBRL1.addChild(this.leg_4);
        this.jointFLL1.addChild(this.leg_7);
        this.body_1.addChild(this.popY19);
        this.body_1.addChild(this.popY20);
        this.mouth_1.addChild(this.teeth_3);
        this.JD_1.addChild(this.jointFRL);
        this.body_1.addChild(this.body_2);
        this.body_1.addChild(this.popX10);
        this.JD_2.addChild(this.jointBLL);
        this.body_1.addChild(this.popX12);
        this.head.addChild(this.popX16);
        this.body.addChild(this.JD);
        this.body_1.addChild(this.popX14);
        this.jointH.addChild(this.head);
        this.leg_10.addChild(this.dec_2);
        this.body_1.addChild(this.popY15);
        this.head.addChild(this.mouth);
        this.body_1.addChild(this.popY6);
        this.body_2.addChild(this.JD_2);
        this.body_1.addChild(this.popX13);
        this.leg_10.addChild(this.leg_11);
        this.mouth_1.addChild(this.teeth_4);
        this.leg_9.addChild(this.jointFRL1);
        this.body_2.addChild(this.popX3);
        this.head.addChild(this.mouthg);
        this.body_1.addChild(this.popY8);
        this.leg_4.addChild(this.leg_5);
        this.body_1.addChild(this.popY21);
        this.jointFLL.addChild(this.leg_6);
        this.body_2.addChild(this.popY3);
        this.body_1.addChild(this.popY12);
        this.leg_1.addChild(this.leg_2);
        this.leg_3.addChild(this.jointBRL1);
        this.leg.addChild(this.jointBLL1);
        this.body_1.addChild(this.popX11);
        this.body_1.addChild(this.popX15);
        this.body_2.addChild(this.popX1);
        this.jointFRL1.addChild(this.leg_10);
        this.JD_3.addChild(this.jointBRL);
        this.body_1.addChild(this.popX5);
        this.jointM.addChild(this.mouth_1);
        this.body_2.addChild(this.popZ1);
        this.body_1.addChild(this.popY10);
        this.leg_7.addChild(this.leg_8);
        this.mouth_1.addChild(this.teeth_2);
        this.body_1.addChild(this.popY7);
        this.body_1.addChild(this.popY13);
        this.body.addChild(this.neck);
        this.body_1.addChild(this.popY11);
        this.jointBLL.addChild(this.leg);
        this.body_2.addChild(this.popX4);
        this.body_1.addChild(this.popX6);
        this.jointBRL.addChild(this.leg_3);
        this.neck.addChild(this.jointdont);
        this.mainbody.addChild(this.body);
    }

    public void render(Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale) {
        super.render(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
        this.mainbody.render(scale);
    }

    public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn) {
        EntityInfSheep parasite = (EntityInfSheep)entityIn;
        this.jointFLL.rotateAngleX = 0.0f;
        this.jointFRL.rotateAngleX = 0.0f;
        this.jointBLL.rotateAngleX = 0.0f;
        this.jointBRL.rotateAngleX = 0.0f;
        this.mainbody.offsetY = 0.0f;
        this.mainbody.rotateAngleX = 0.0f;
        this.mainbody.rotateAngleZ = 0.0f;
        this.jointM.rotateAngleX = 0.0f;
        this.jointH.rotateAngleX = headPitch * 0.016f;
        this.jointH.rotateAngleY = netHeadYaw * 0.016f;
        byte i = parasite.getParasiteStatus();
        if (i == 0) {
            float f22;
            if (!parasite.getStillAni()) {
                float GS = 2.0f;
                float GD = 2.0f;
                this.swingX(this.jointFLL, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.swingX(this.jointFRL, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingX(this.jointBLL, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingX(this.jointBRL, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.6f * GS, 1, limbSwing, limbSwingAmount, 0.05f);
                this.mainbody.rotateAngleX = 0.0f;
            }
            float f1 = Mth.cos((float)(ageInTicks * 0.0998f)) * 0.0215f;
            float f2 = Mth.cos((float)(ageInTicks * 0.19112f)) * 0.0261f;
            float f3 = Mth.cos((float)(ageInTicks * 0.27955f)) * 0.0262f;
            float f4 = Mth.cos((float)(ageInTicks * 0.35222f)) * 0.0265f;
            this.jointM.rotateAngleX = f22 = Mth.cos((float)(ageInTicks * 0.2f)) * 0.1f;
            this.popX5.offsetX = f1;
            this.popX6.offsetX = f2;
            this.popX7.offsetX = f3;
            this.popX8.offsetX = f1;
            this.popY6.offsetY = f2;
            this.popY7.offsetY = f3;
            this.popY8.offsetY = f4;
            this.popY9.offsetY = f1;
            this.popY10.offsetY = f2;
            this.popY11.offsetY = f3;
            this.popX9.offsetX = f1;
            this.popX10.offsetX = f2;
            this.popX11.offsetX = f3;
            this.popX12.offsetX = f4;
            this.popX13.offsetX = f1;
            this.popX14.offsetX = f2;
            this.popX15.offsetX = f3;
            this.popY12.offsetY = f1;
            this.popY13.offsetY = f2;
            this.popY14.offsetY = f3;
            this.popY15.offsetY = f4;
            this.popY16.offsetY = f1;
            this.popY17.offsetY = f2;
            this.popY18.offsetY = f3;
            this.popY19.offsetY = f1;
            this.popY20.offsetY = f2;
            this.popY21.offsetY = f3;
            this.popY1.offsetY = f4;
            this.popY2.offsetY = f1;
            this.popY3.offsetY = f2;
            this.popY4.offsetY = f3;
            this.popY5.offsetY = f1;
            this.popZ1.offsetZ = f2;
            this.popZ2.offsetZ = f3;
            this.popX1.offsetX = f4;
            this.popX2.offsetX = f1;
            this.popX3.offsetX = f2;
            this.popX4.offsetX = f3;
            this.popX16.offsetX = f1;
        } else if (i == 1) {
            float f22;
            if (!parasite.getStillAni()) {
                float GS = 2.0f;
                float GD = 2.0f;
                this.swingX(this.jointFLL, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.swingX(this.jointFRL, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingX(this.jointBLL, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingX(this.jointBRL, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.6f * GS, 1, limbSwing, limbSwingAmount, 0.05f);
                this.mainbody.rotateAngleX = 0.0f;
            }
            this.jointM.rotateAngleX = f22 = Mth.cos((float)(ageInTicks * 0.5f)) * 0.2f;
            float f1 = Mth.cos((float)(ageInTicks * 0.0998f)) * 0.0215f;
            float f2 = Mth.cos((float)(ageInTicks * 0.19112f)) * 0.0261f;
            float f3 = Mth.cos((float)(ageInTicks * 0.27955f)) * 0.0262f;
            float f4 = Mth.cos((float)(ageInTicks * 0.35222f)) * 0.0265f;
            this.popX5.offsetX = f1;
            this.popX6.offsetX = f2;
            this.popX7.offsetX = f3;
            this.popX8.offsetX = f1;
            this.popY6.offsetY = f2;
            this.popY7.offsetY = f3;
            this.popY8.offsetY = f4;
            this.popY9.offsetY = f1;
            this.popY10.offsetY = f2;
            this.popY11.offsetY = f3;
            this.popX9.offsetX = f1;
            this.popX10.offsetX = f2;
            this.popX11.offsetX = f3;
            this.popX12.offsetX = f4;
            this.popX13.offsetX = f1;
            this.popX14.offsetX = f2;
            this.popX15.offsetX = f3;
            this.popY12.offsetY = f1;
            this.popY13.offsetY = f2;
            this.popY14.offsetY = f3;
            this.popY15.offsetY = f4;
            this.popY16.offsetY = f1;
            this.popY17.offsetY = f2;
            this.popY18.offsetY = f3;
            this.popY19.offsetY = f1;
            this.popY20.offsetY = f2;
            this.popY21.offsetY = f3;
            this.popY1.offsetY = f4;
            this.popY2.offsetY = f1;
            this.popY3.offsetY = f2;
            this.popY4.offsetY = f3;
            this.popY5.offsetY = f1;
            this.popZ1.offsetZ = f2;
            this.popZ2.offsetZ = f3;
            this.popX1.offsetX = f4;
            this.popX2.offsetX = f1;
            this.popX3.offsetX = f2;
            this.popX4.offsetX = f3;
            this.popX16.offsetX = f1;
        } else if (i == 2) {
            float f22;
            if (!parasite.getStillAni()) {
                float GS = 1.3f;
                float GD = 0.25f;
                this.swingX(this.jointFLL, 0.3f * GS, 3.0f * GD, -1, 0.5f, 0.0f, limbSwing, limbSwingAmount);
                this.swingX(this.jointFRL, 0.3f * GS, 3.0f * GD, -1, -0.5f, 0.0f, limbSwing, limbSwingAmount);
                this.swingX(this.jointBLL, 0.3f * GS, 3.5f * GD, 1, -0.5f, 0.4f, limbSwing, limbSwingAmount);
                this.swingX(this.jointBRL, 0.3f * GS, 3.5f * GD, 1, 0.5f, 0.4f, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.3f * GS, -1, limbSwing, limbSwingAmount, 0.08f);
                this.swingX(this.mainbody, 0.3f * GS, 0.4f * GD, -1, 0.8f, 0.0f, limbSwing, limbSwingAmount);
            }
            this.jointM.rotateAngleX = f22 = Mth.cos((float)(ageInTicks * 0.5f)) * 0.2f;
            float f1 = Mth.cos((float)(ageInTicks * 0.0998f)) * 0.0215f;
            float f2 = Mth.cos((float)(ageInTicks * 0.19112f)) * 0.0261f;
            float f3 = Mth.cos((float)(ageInTicks * 0.27955f)) * 0.0262f;
            float f4 = Mth.cos((float)(ageInTicks * 0.35222f)) * 0.0265f;
            this.popX5.offsetX = f1;
            this.popX6.offsetX = f2;
            this.popX7.offsetX = f3;
            this.popX8.offsetX = f1;
            this.popY6.offsetY = f2;
            this.popY7.offsetY = f3;
            this.popY8.offsetY = f4;
            this.popY9.offsetY = f1;
            this.popY10.offsetY = f2;
            this.popY11.offsetY = f3;
            this.popX9.offsetX = f1;
            this.popX10.offsetX = f2;
            this.popX11.offsetX = f3;
            this.popX12.offsetX = f4;
            this.popX13.offsetX = f1;
            this.popX14.offsetX = f2;
            this.popX15.offsetX = f3;
            this.popY12.offsetY = f1;
            this.popY13.offsetY = f2;
            this.popY14.offsetY = f3;
            this.popY15.offsetY = f4;
            this.popY16.offsetY = f1;
            this.popY17.offsetY = f2;
            this.popY18.offsetY = f3;
            this.popY19.offsetY = f1;
            this.popY20.offsetY = f2;
            this.popY21.offsetY = f3;
            this.popY1.offsetY = f4;
            this.popY2.offsetY = f1;
            this.popY3.offsetY = f2;
            this.popY4.offsetY = f3;
            this.popY5.offsetY = f1;
            this.popZ1.offsetZ = f2;
            this.popZ2.offsetZ = f3;
            this.popX1.offsetX = f4;
            this.popX2.offsetX = f1;
            this.popX3.offsetX = f2;
            this.popX4.offsetX = f3;
            this.popX16.offsetX = f1;
        } else if (i == 6) {
            float f22;
            float f11 = Mth.cos((float)(ageInTicks * 2.0f)) * 0.01f;
            float f111 = Mth.cos((float)(ageInTicks * 3.0f)) * 0.2f;
            this.mainbody.rotateAngleZ = parasite.getTHeigh();
            this.mainbody.offsetY = 0.37f;
            this.mainbody.rotateAngleX = f11;
            this.jointFLL.rotateAngleX = 0.2f + f111;
            this.jointFRL.rotateAngleX = -0.2f + f111;
            this.jointBLL.rotateAngleX = -0.2f + f111;
            this.jointBRL.rotateAngleX = 0.2f + f111;
            this.jointH.rotateAngleY = f111;
            this.jointM.rotateAngleX = f22 = Mth.cos((float)(ageInTicks * 1.5f)) * 0.3f;
            float f1 = Mth.cos((float)(ageInTicks * 0.1998f)) * 0.0215f;
            float f2 = Mth.cos((float)(ageInTicks * 0.29112f)) * 0.0261f;
            float f3 = Mth.cos((float)(ageInTicks * 0.37955f)) * 0.0262f;
            float f4 = Mth.cos((float)(ageInTicks * 0.45222f)) * 0.0265f;
            this.popX5.offsetX = f1;
            this.popX6.offsetX = f2;
            this.popX7.offsetX = f3;
            this.popX8.offsetX = f1;
            this.popY6.offsetY = f2;
            this.popY7.offsetY = f3;
            this.popY8.offsetY = f4;
            this.popY9.offsetY = f1;
            this.popY10.offsetY = f2;
            this.popY11.offsetY = f3;
            this.popX9.offsetX = f1;
            this.popX10.offsetX = f2;
            this.popX11.offsetX = f3;
            this.popX12.offsetX = f4;
            this.popX13.offsetX = f1;
            this.popX14.offsetX = f2;
            this.popX15.offsetX = f3;
            this.popY12.offsetY = f1;
            this.popY13.offsetY = f2;
            this.popY14.offsetY = f3;
            this.popY15.offsetY = f4;
            this.popY16.offsetY = f1;
            this.popY17.offsetY = f2;
            this.popY18.offsetY = f3;
            this.popY19.offsetY = f1;
            this.popY20.offsetY = f2;
            this.popY21.offsetY = f3;
            this.popY1.offsetY = f4;
            this.popY2.offsetY = f1;
            this.popY3.offsetY = f2;
            this.popY4.offsetY = f3;
            this.popY5.offsetY = f1;
            this.popZ1.offsetZ = f2;
            this.popZ2.offsetZ = f3;
            this.popX1.offsetX = f4;
            this.popX2.offsetX = f1;
            this.popX3.offsetX = f2;
            this.popX4.offsetX = f3;
            this.popX16.offsetX = f1;
        }
        this.underground(parasite, ageInTicks, this.mainbody);
    }
}

