package com.dhanantry.scapeandrunparasites.client.model.entity.infected;

import com.dhanantry.scapeandrunparasites.client.legacy.ModelRenderer;
import com.dhanantry.scapeandrunparasites.client.model.ModelSRP;
import com.dhanantry.scapeandrunparasites.entity.monster.infected.EntityInfWolf;
import net.minecraft.util.Mth;
import net.minecraft.world.entity.Entity;

public class ModelInfWolf
extends ModelSRP {
    public ModelRenderer mainbody;
    public ModelRenderer body;
    public ModelRenderer body_1;
    public ModelRenderer body_2;
    public ModelRenderer popX1;
    public ModelRenderer popX2;
    public ModelRenderer popX3;
    public ModelRenderer popY1;
    public ModelRenderer popY2;
    public ModelRenderer popY3;
    public ModelRenderer popX4;
    public ModelRenderer popX5;
    public ModelRenderer popY4;
    public ModelRenderer popY5;
    public ModelRenderer JD;
    public ModelRenderer JD_1;
    public ModelRenderer neck;
    public ModelRenderer dec;
    public ModelRenderer jointFLL;
    public ModelRenderer leg;
    public ModelRenderer jointFLL1;
    public ModelRenderer leg_1;
    public ModelRenderer leg_2;
    public ModelRenderer jointFRL;
    public ModelRenderer leg_3;
    public ModelRenderer jointFRL1;
    public ModelRenderer leg_4;
    public ModelRenderer leg_5;
    public ModelRenderer jointdont;
    public ModelRenderer jointH;
    public ModelRenderer head;
    public ModelRenderer head1;
    public ModelRenderer leftear;
    public ModelRenderer rightear;
    public ModelRenderer mouth;
    public ModelRenderer jointM;
    public ModelRenderer mouth_1;
    public ModelRenderer teeth;
    public ModelRenderer teeth_1;
    public ModelRenderer teeth_2;
    public ModelRenderer teeth_3;
    public ModelRenderer body_3;
    public ModelRenderer JD_2;
    public ModelRenderer JD_3;
    public ModelRenderer tail;
    public ModelRenderer jointBLL;
    public ModelRenderer leg_6;
    public ModelRenderer jointBLL1;
    public ModelRenderer leg_7;
    public ModelRenderer leg_8;
    public ModelRenderer jointBRL;
    public ModelRenderer leg_9;
    public ModelRenderer jointBRL1;
    public ModelRenderer leg_10;
    public ModelRenderer leg_11;

    public ModelInfWolf() {
        this.textureWidth = 64;
        this.textureHeight = 36;
        this.JD = new ModelRenderer(this, 40, 2);
        this.JD.setRotationPoint(0.5f, 3.0f, -5.0f);
        this.JD.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD, -1.3264502f, 0.0f, 0.0f);
        this.JD_3 = new ModelRenderer(this, 34, 18);
        this.JD_3.setRotationPoint(-2.5f, 2.0f, -2.0f);
        this.JD_3.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD_3, -1.7627826f, 0.0f, 0.0f);
        this.leg_8 = new ModelRenderer(this, 26, 24);
        this.leg_8.setRotationPoint(0.0f, 4.2f, -0.4f);
        this.leg_8.addBox(-1.0f, -1.0f, -1.0f, 2, 1, 2, 0.0f);
        this.popX1 = new ModelRenderer(this, 14, 0);
        this.popX1.setRotationPoint(1.0f, 0.4f, 3.3f);
        this.popX1.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.jointBLL = new ModelRenderer(this, 0, 19);
        this.jointBLL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointBLL.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.jointBRL1 = new ModelRenderer(this, 14, 22);
        this.jointBRL1.setRotationPoint(1.0f, 4.0f, 0.0f);
        this.jointBRL1.addBox(-0.5f, 0.0f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_1 = new ModelRenderer(this, 58, 5);
        this.leg_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_1.addBox(-0.5f, -1.0f, -0.5f, 1, 4, 1, 0.0f);
        this.setRotateAngle(this.leg_1, 0.0f, -0.08726646f, 0.0f);
        this.JD_1 = new ModelRenderer(this, 43, 3);
        this.JD_1.setRotationPoint(-2.5f, 3.0f, -5.0f);
        this.JD_1.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD_1, -1.3264502f, 0.0f, 0.0f);
        this.leg_4 = new ModelRenderer(this, 26, 15);
        this.leg_4.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_4.addBox(-0.5f, -1.0f, -0.5f, 1, 4, 1, 0.0f);
        this.setRotateAngle(this.leg_4, 0.0f, 0.08726646f, 0.0f);
        this.leg_6 = new ModelRenderer(this, 18, 22);
        this.leg_6.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_6.addBox(0.0f, -0.5f, -1.0f, 2, 5, 2, 0.0f);
        this.jointH = new ModelRenderer(this, 14, 10);
        this.jointH.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointH.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.leg_11 = new ModelRenderer(this, 37, 26);
        this.leg_11.setRotationPoint(0.0f, 4.2f, -0.4f);
        this.leg_11.addBox(-1.0f, -1.0f, -1.0f, 2, 1, 2, 0.0f);
        this.jointdont = new ModelRenderer(this, 0, 10);
        this.jointdont.setRotationPoint(0.0f, -0.7f, 0.5f);
        this.jointdont.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.jointdont, -1.3264502f, 0.0f, 0.0f);
        this.jointM = new ModelRenderer(this, 58, 10);
        this.jointM.setRotationPoint(0.0f, 2.0f, -1.9f);
        this.jointM.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.jointBRL = new ModelRenderer(this, 24, 21);
        this.jointBRL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointBRL.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.popY2 = new ModelRenderer(this, 50, 0);
        this.popY2.setRotationPoint(0.5f, 1.0f, 1.7f);
        this.popY2.addBox(0.0f, -2.0f, 0.0f, 1, 2, 1, 0.0f);
        this.teeth_1 = new ModelRenderer(this, 14, 12);
        this.teeth_1.setRotationPoint(1.9f, 0.0f, -3.1f);
        this.teeth_1.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.teeth_1, 0.10471976f, -0.9599311f, 0.0f);
        this.leg_3 = new ModelRenderer(this, 32, 13);
        this.leg_3.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_3.addBox(0.0f, 0.0f, -1.0f, 2, 3, 2, 0.0f);
        this.head = new ModelRenderer(this, 36, 16);
        this.head.setRotationPoint(-1.0f, 0.5f, -1.0f);
        this.head.addBox(-2.0f, -3.0f, -2.0f, 6, 6, 4, 0.0f);
        this.leg = new ModelRenderer(this, 18, 12);
        this.leg.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg.addBox(0.0f, 0.0f, -1.0f, 2, 3, 2, 0.0f);
        this.body = new ModelRenderer(this, 0, 0);
        this.body.setRotationPoint(0.0f, -5.0f, -1.0f);
        this.body.addBox(-2.0f, 0.0f, 0.0f, 4, 4, 6, 0.0f);
        this.mainbody = new ModelRenderer(this, 0, 0);
        this.mainbody.setRotationPoint(0.0f, 17.0f, 0.5f);
        this.mainbody.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.dec = new ModelRenderer(this, 46, 3);
        this.dec.setRotationPoint(-2.4f, 0.2f, 0.5f);
        this.dec.addBox(0.0f, 0.0f, -1.0f, 3, 2, 2, 0.0f);
        this.setRotateAngle(this.dec, 0.0f, 0.20943952f, 0.41887903f);
        this.leg_9 = new ModelRenderer(this, 54, 25);
        this.leg_9.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_9.addBox(0.0f, -0.5f, -1.0f, 2, 5, 2, 0.0f);
        this.popX3 = new ModelRenderer(this, 40, 0);
        this.popX3.setRotationPoint(1.0f, 1.9f, 0.8f);
        this.popX3.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.leg_2 = new ModelRenderer(this, 26, 12);
        this.leg_2.setRotationPoint(0.0f, 4.0f, -0.4f);
        this.leg_2.addBox(-1.0f, -1.0f, -1.0f, 2, 1, 2, 0.0f);
        this.leg_10 = new ModelRenderer(this, 33, 26);
        this.leg_10.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_10.addBox(-0.5f, 0.0f, -0.5f, 1, 4, 1, 0.0f);
        this.setRotateAngle(this.leg_10, 0.0f, 0.08726646f, 0.0f);
        this.body_1 = new ModelRenderer(this, 20, 0);
        this.body_1.setRotationPoint(0.0f, -1.5f, -4.8f);
        this.body_1.addBox(-3.5f, 0.0f, -5.5f, 7, 6, 6, 0.0f);
        this.setRotateAngle(this.body_1, 1.3264502f, 0.0f, 0.0f);
        this.body_3 = new ModelRenderer(this, 0, 22);
        this.body_3.setRotationPoint(0.0f, 3.5f, 0.0f);
        this.body_3.addBox(-2.5f, -0.5f, -2.0f, 5, 2, 4, 0.0f);
        this.setRotateAngle(this.body_3, 0.20943952f, 0.0f, 0.0f);
        this.popY1 = new ModelRenderer(this, 46, 0);
        this.popY1.setRotationPoint(0.3f, 1.0f, 3.3f);
        this.popY1.addBox(0.0f, -2.0f, 0.0f, 1, 2, 1, 0.0f);
        this.mouth_1 = new ModelRenderer(this, 25, 20);
        this.mouth_1.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.mouth_1.addBox(0.0f, 0.0f, -3.3f, 2, 1, 3, 0.0f);
        this.setRotateAngle(this.mouth_1, 0.41887903f, 0.0f, 0.0f);
        this.leg_5 = new ModelRenderer(this, 0, 16);
        this.leg_5.setRotationPoint(0.0f, 4.0f, -0.4f);
        this.leg_5.addBox(-1.0f, -1.0f, -1.0f, 2, 1, 2, 0.0f);
        this.jointFLL1 = new ModelRenderer(this, 58, 3);
        this.jointFLL1.setRotationPoint(1.0f, 4.0f, 0.0f);
        this.jointFLL1.addBox(-0.5f, 0.0f, -0.5f, 1, 1, 1, 0.0f);
        this.jointBLL1 = new ModelRenderer(this, 32, 20);
        this.jointBLL1.setRotationPoint(1.0f, 4.0f, 0.0f);
        this.jointBLL1.addBox(-0.5f, 0.0f, -0.5f, 1, 1, 1, 0.0f);
        this.popY3 = new ModelRenderer(this, 54, 0);
        this.popY3.setRotationPoint(-1.1f, 1.0f, 2.6f);
        this.popY3.addBox(0.0f, -2.0f, 0.0f, 1, 2, 1, 0.0f);
        this.leg_7 = new ModelRenderer(this, 0, 21);
        this.leg_7.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.leg_7.addBox(-0.5f, 0.0f, -0.5f, 1, 4, 1, 0.0f);
        this.setRotateAngle(this.leg_7, 0.0f, -0.08726646f, 0.0f);
        this.head1 = new ModelRenderer(this, 4, 16);
        this.head1.setRotationPoint(0.0f, 0.0f, -0.5f);
        this.head1.addBox(-0.5f, 0.0f, -5.0f, 3, 2, 4, 0.0f);
        this.setRotateAngle(this.head1, 0.13962634f, 0.0f, 0.0f);
        this.leftear = new ModelRenderer(this, 52, 16);
        this.leftear.setRotationPoint(-0.4f, -0.4f, -0.5f);
        this.leftear.addBox(2.0f, -5.0f, 0.0f, 2, 2, 1, 0.0f);
        this.setRotateAngle(this.leftear, 0.0f, -0.05235988f, 0.2268928f);
        this.JD_2 = new ModelRenderer(this, 30, 18);
        this.JD_2.setRotationPoint(0.5f, 2.0f, -2.0f);
        this.JD_2.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.JD_2, -1.7627826f, 0.0f, 0.0f);
        this.teeth_3 = new ModelRenderer(this, 58, 16);
        this.teeth_3.setRotationPoint(0.0f, 0.0f, -3.1f);
        this.teeth_3.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.teeth_3, 0.10471976f, 0.9599311f, 0.0f);
        this.tail = new ModelRenderer(this, 57, 18);
        this.tail.setRotationPoint(0.0f, 1.5f, 1.0f);
        this.tail.addBox(-0.5f, 0.0f, -0.5f, 1, 6, 1, 0.0f);
        this.setRotateAngle(this.tail, -1.2915436f, 0.0f, 0.0f);
        this.popX4 = new ModelRenderer(this, 14, 2);
        this.popX4.setRotationPoint(-2.9f, 1.7f, 0.7f);
        this.popX4.addBox(0.0f, 0.0f, 0.0f, 2, 2, 2, 0.0f);
        this.popX5 = new ModelRenderer(this, 0, 2);
        this.popX5.setRotationPoint(-1.0f, 2.7f, 3.0f);
        this.popX5.addBox(-2.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.jointFRL = new ModelRenderer(this, 0, 4);
        this.jointFRL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointFRL.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.popY5 = new ModelRenderer(this, 22, 2);
        this.popY5.setRotationPoint(-1.9f, 3.0f, 1.7f);
        this.popY5.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.body_2 = new ModelRenderer(this, 41, 7);
        this.body_2.setRotationPoint(0.0f, 2.3f, 5.0f);
        this.body_2.addBox(-3.0f, 0.0f, -2.5f, 6, 4, 5, 0.0f);
        this.setRotateAngle(this.body_2, 1.7627826f, 0.0f, 0.0f);
        this.rightear = new ModelRenderer(this, 14, 17);
        this.rightear.setRotationPoint(0.3f, 0.5f, 0.0f);
        this.rightear.addBox(-2.0f, -5.0f, 0.0f, 2, 2, 1, 0.0f);
        this.setRotateAngle(this.rightear, 0.08726646f, 0.12217305f, -0.2268928f);
        this.teeth_2 = new ModelRenderer(this, 24, 12);
        this.teeth_2.setRotationPoint(2.4f, 0.0f, -1.6f);
        this.teeth_2.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.teeth_2, 0.0f, (float)Math.PI, 0.10471976f);
        this.jointFRL1 = new ModelRenderer(this, 40, 4);
        this.jointFRL1.setRotationPoint(1.0f, 4.0f, 0.0f);
        this.jointFRL1.addBox(-0.5f, 0.0f, -0.5f, 1, 1, 1, 0.0f);
        this.popX2 = new ModelRenderer(this, 20, 0);
        this.popX2.setRotationPoint(1.0f, 0.6f, 1.8f);
        this.popX2.addBox(0.0f, 0.0f, 0.0f, 2, 1, 1, 0.0f);
        this.popY4 = new ModelRenderer(this, 58, 0);
        this.popY4.setRotationPoint(-1.6f, 3.0f, 0.3f);
        this.popY4.addBox(0.0f, 0.0f, 0.0f, 1, 2, 1, 0.0f);
        this.neck = new ModelRenderer(this, 0, 10);
        this.neck.setRotationPoint(0.0f, -1.2f, -3.0f);
        this.neck.addBox(-2.5f, -0.5f, -2.0f, 5, 2, 4, 0.0f);
        this.teeth = new ModelRenderer(this, 0, 12);
        this.teeth.setRotationPoint(-0.4f, 0.0f, -1.6f);
        this.teeth.addBox(-0.5f, -0.5f, -0.5f, 1, 1, 1, 0.0f);
        this.setRotateAngle(this.teeth, 0.0f, 0.0f, -0.10471976f);
        this.jointFLL = new ModelRenderer(this, 54, 3);
        this.jointFLL.setRotationPoint(0.0f, 0.0f, 0.0f);
        this.jointFLL.addBox(0.0f, 0.0f, 0.0f, 1, 1, 1, 0.0f);
        this.mouth = new ModelRenderer(this, 18, 18);
        this.mouth.setRotationPoint(0.0f, 2.0f, -2.7f);
        this.mouth.addBox(-0.5f, 0.0f, 0.0f, 3, 1, 2, 0.0f);
        this.body_1.addChild(this.JD);
        this.body_2.addChild(this.JD_3);
        this.leg_7.addChild(this.leg_8);
        this.body.addChild(this.popX1);
        this.JD_2.addChild(this.jointBLL);
        this.leg_9.addChild(this.jointBRL1);
        this.jointFLL1.addChild(this.leg_1);
        this.body_1.addChild(this.JD_1);
        this.jointFRL1.addChild(this.leg_4);
        this.jointBLL.addChild(this.leg_6);
        this.jointdont.addChild(this.jointH);
        this.leg_10.addChild(this.leg_11);
        this.neck.addChild(this.jointdont);
        this.head1.addChild(this.jointM);
        this.JD_3.addChild(this.jointBRL);
        this.body.addChild(this.popY2);
        this.mouth_1.addChild(this.teeth_1);
        this.jointFRL.addChild(this.leg_3);
        this.jointH.addChild(this.head);
        this.jointFLL.addChild(this.leg);
        this.mainbody.addChild(this.body);
        this.body_1.addChild(this.dec);
        this.jointBRL.addChild(this.leg_9);
        this.body.addChild(this.popX3);
        this.leg_1.addChild(this.leg_2);
        this.jointBRL1.addChild(this.leg_10);
        this.body.addChild(this.body_1);
        this.body_2.addChild(this.body_3);
        this.body.addChild(this.popY1);
        this.jointM.addChild(this.mouth_1);
        this.leg_4.addChild(this.leg_5);
        this.leg.addChild(this.jointFLL1);
        this.leg_6.addChild(this.jointBLL1);
        this.body.addChild(this.popY3);
        this.jointBLL1.addChild(this.leg_7);
        this.head.addChild(this.head1);
        this.head.addChild(this.leftear);
        this.body_2.addChild(this.JD_2);
        this.mouth_1.addChild(this.teeth_3);
        this.body_3.addChild(this.tail);
        this.body.addChild(this.popX4);
        this.body.addChild(this.popX5);
        this.JD_1.addChild(this.jointFRL);
        this.body.addChild(this.popY5);
        this.body.addChild(this.body_2);
        this.head.addChild(this.rightear);
        this.mouth_1.addChild(this.teeth_2);
        this.leg_3.addChild(this.jointFRL1);
        this.body.addChild(this.popX2);
        this.body.addChild(this.popY4);
        this.body_1.addChild(this.neck);
        this.mouth_1.addChild(this.teeth);
        this.JD.addChild(this.jointFLL);
        this.head1.addChild(this.mouth);
    }

    public void render(Entity entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scale) {
        super.render(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scale);
        this.mainbody.render(scale);
    }

    public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn) {
        EntityInfWolf parasite = (EntityInfWolf)entityIn;
        this.jointFLL.rotateAngleX = 0.0f;
        this.jointFRL.rotateAngleX = 0.0f;
        this.jointBLL.rotateAngleX = 0.0f;
        this.jointBRL.rotateAngleX = 0.0f;
        this.mainbody.offsetY = 0.0f;
        this.mainbody.rotateAngleX = 0.0f;
        this.mainbody.rotateAngleZ = 0.0f;
        this.jointM.rotateAngleX = 0.0f;
        this.jointH.rotateAngleX = headPitch * 0.016f;
        this.jointH.rotateAngleY = netHeadYaw * 0.016f;
        byte i = parasite.getParasiteStatus();
        if (i == 0) {
            float f22;
            if (!parasite.getStillAni()) {
                float GS = 1.5f;
                float GD = 1.4f;
                this.swingX(this.jointFLL, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.swingX(this.jointFRL, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingX(this.jointBLL, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingX(this.jointBRL, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.6f * GS, 1, limbSwing, limbSwingAmount, 0.05f);
                this.mainbody.rotateAngleX = 0.0f;
            }
            float f1 = Mth.cos((float)(ageInTicks * 0.0998f)) * 0.0215f;
            float f2 = Mth.cos((float)(ageInTicks * 0.19112f)) * 0.0261f;
            float f3 = Mth.cos((float)(ageInTicks * 0.27955f)) * 0.0262f;
            float f4 = Mth.cos((float)(ageInTicks * 0.35222f)) * 0.0265f;
            this.jointM.rotateAngleX = f22 = Mth.cos((float)(ageInTicks * 0.2f)) * 0.1f;
            this.popX5.offsetX = f1;
            this.popY1.offsetY = f4;
            this.popY2.offsetY = f1;
            this.popY3.offsetY = f2;
            this.popY4.offsetY = f3;
            this.popY5.offsetY = f1;
            this.popX1.offsetX = f4;
            this.popX2.offsetX = f1;
            this.popX3.offsetX = f2;
            this.popX4.offsetX = f3;
        } else if (i == 1) {
            float f22;
            if (!parasite.getStillAni()) {
                float GS = 1.5f;
                float GD = 1.4f;
                this.swingX(this.jointFLL, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.swingX(this.jointFRL, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingX(this.jointBLL, 0.3f * GS, 1.0f * GD, -1, limbSwing, limbSwingAmount);
                this.swingX(this.jointBRL, 0.3f * GS, 1.0f * GD, 1, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.6f * GS, 1, limbSwing, limbSwingAmount, 0.05f);
                this.mainbody.rotateAngleX = 0.0f;
            }
            this.jointM.rotateAngleX = f22 = Mth.cos((float)(ageInTicks * 0.5f)) * 0.2f;
            float f1 = Mth.cos((float)(ageInTicks * 0.0998f)) * 0.0215f;
            float f2 = Mth.cos((float)(ageInTicks * 0.19112f)) * 0.0261f;
            float f3 = Mth.cos((float)(ageInTicks * 0.27955f)) * 0.0262f;
            float f4 = Mth.cos((float)(ageInTicks * 0.35222f)) * 0.0265f;
            this.popX5.offsetX = f1;
            this.popY1.offsetY = f4;
            this.popY2.offsetY = f1;
            this.popY3.offsetY = f2;
            this.popY4.offsetY = f3;
            this.popY5.offsetY = f1;
            this.popX1.offsetX = f4;
            this.popX2.offsetX = f1;
            this.popX3.offsetX = f2;
            this.popX4.offsetX = f3;
        } else if (i == 2) {
            float f22;
            if (!parasite.getStillAni()) {
                float GS = 1.3f;
                float GD = 0.2f;
                this.swingX(this.jointFLL, 0.3f * GS, 5.0f * GD, -1, 0.5f, 0.0f, limbSwing, limbSwingAmount);
                this.swingX(this.jointFRL, 0.3f * GS, 5.0f * GD, -1, -0.5f, 0.0f, limbSwing, limbSwingAmount);
                this.swingX(this.jointBLL, 0.3f * GS, 5.5f * GD, 1, -0.5f, 0.5f, limbSwing, limbSwingAmount);
                this.swingX(this.jointBRL, 0.3f * GS, 5.5f * GD, 1, 0.5f, 0.5f, limbSwing, limbSwingAmount);
                this.moveY(this.mainbody, 0.3f * GS, -1, limbSwing, limbSwingAmount, 0.08f);
                this.swingX(this.mainbody, 0.3f * GS, 0.8f * GD, -1, 0.8f, 0.0f, limbSwing, limbSwingAmount);
            }
            this.jointM.rotateAngleX = f22 = Mth.cos((float)(ageInTicks * 0.5f)) * 0.2f;
            float f1 = Mth.cos((float)(ageInTicks * 0.0998f)) * 0.0215f;
            float f2 = Mth.cos((float)(ageInTicks * 0.19112f)) * 0.0261f;
            float f3 = Mth.cos((float)(ageInTicks * 0.27955f)) * 0.0262f;
            float f4 = Mth.cos((float)(ageInTicks * 0.35222f)) * 0.0265f;
            this.popX5.offsetX = f1;
            this.popY1.offsetY = f4;
            this.popY2.offsetY = f1;
            this.popY3.offsetY = f2;
            this.popY4.offsetY = f3;
            this.popY5.offsetY = f1;
            this.popX1.offsetX = f4;
            this.popX2.offsetX = f1;
            this.popX3.offsetX = f2;
            this.popX4.offsetX = f3;
        } else if (i == 6) {
            float f22;
            float f11 = Mth.cos((float)(ageInTicks * 2.0f)) * 0.01f;
            float f111 = Mth.cos((float)(ageInTicks * 3.0f)) * 0.2f;
            this.mainbody.rotateAngleZ = parasite.getTHeigh();
            this.mainbody.offsetY = 0.25f;
            this.mainbody.rotateAngleX = f11;
            this.jointFLL.rotateAngleX = 0.2f + f111;
            this.jointFRL.rotateAngleX = -0.2f + f111;
            this.jointBLL.rotateAngleX = -0.2f + f111;
            this.jointBRL.rotateAngleX = 0.2f + f111;
            this.jointH.rotateAngleY = f111;
            this.jointM.rotateAngleX = f22 = Mth.cos((float)(ageInTicks * 1.5f)) * 0.3f;
            float f1 = Mth.cos((float)(ageInTicks * 0.1998f)) * 0.0215f;
            float f2 = Mth.cos((float)(ageInTicks * 0.29112f)) * 0.0261f;
            float f3 = Mth.cos((float)(ageInTicks * 0.37955f)) * 0.0262f;
            float f4 = Mth.cos((float)(ageInTicks * 0.45222f)) * 0.0265f;
            this.popX5.offsetX = f1;
            this.popY1.offsetY = f4;
            this.popY2.offsetY = f1;
            this.popY3.offsetY = f2;
            this.popY4.offsetY = f3;
            this.popY5.offsetY = f1;
            this.popX1.offsetX = f4;
            this.popX2.offsetX = f1;
            this.popX3.offsetX = f2;
            this.popX4.offsetX = f3;
        }
        this.underground(parasite, ageInTicks, this.mainbody);
    }
}

