package com.dhanantry.scapeandrunparasites.phase;

import com.dhanantry.scapeandrunparasites.config.SRPConfigSystems;

/** Per-phase / per-dislodgment config lookups (SRPCommandEvolution, SRPCommandDislodgment, SRPWorldData and SRPSaveData helpers of 1.10.9). Generated by porting/tools/gen_phaseconfig.py. */
public final class PhaseConfig {
    private PhaseConfig() {}

    public static int neededPoints(byte in) {
        switch (in) {
            case 1: return SRPConfigSystems.phaseKillsOne;
            case 2: return SRPConfigSystems.phaseKillsTwo;
            case 3: return SRPConfigSystems.phaseKillsThree;
            case 4: return SRPConfigSystems.phaseKillsFour;
            case 5: return SRPConfigSystems.phaseKillsFive;
            case 6: return SRPConfigSystems.phaseKillsSix;
            case 7: return SRPConfigSystems.phaseKillsSeven;
            case 8: return SRPConfigSystems.phaseKillsEight;
            case 9: return SRPConfigSystems.phaseKillsNine;
            case 10: return SRPConfigSystems.phaseKillsTen;
            default: return 0;
        }
    }

    public static int delayTicks(byte in) {
        switch (in) {
            case 1: return SRPConfigSystems.phaseDelayTicksOne;
            case 2: return SRPConfigSystems.phaseDelayTicksTwo;
            case 3: return SRPConfigSystems.phaseDelayTicksThree;
            case 4: return SRPConfigSystems.phaseDelayTicksFour;
            case 5: return SRPConfigSystems.phaseDelayTicksFive;
            case 6: return SRPConfigSystems.phaseDelayTicksSix;
            case 7: return SRPConfigSystems.phaseDelayTicksSeven;
            case 8: return SRPConfigSystems.phaseDelayTicksEight;
            case 9: return SRPConfigSystems.phaseDelayTicksNine;
            case 10: return SRPConfigSystems.phaseDelayTicksTen;
            default: return 0;
        }
    }

    public static int vectorPointCap(int in) {
        switch (in) {
            case -1: return SRPConfigSystems.phaseVectorPointCapZero / 2;
            case 0: return SRPConfigSystems.phaseVectorPointCapZero;
            case 1: return SRPConfigSystems.phaseVectorPointCapOne;
            case 2: return SRPConfigSystems.phaseVectorPointCapTwo;
            case 3: return SRPConfigSystems.phaseVectorPointCapThree;
            case 4: return SRPConfigSystems.phaseVectorPointCapFour;
            case 5: return SRPConfigSystems.phaseVectorPointCapFive;
            case 6: return SRPConfigSystems.phaseVectorPointCapSix;
            case 7: return SRPConfigSystems.phaseVectorPointCapSeven;
            case 8: return SRPConfigSystems.phaseVectorPointCapEight;
            case 9: return SRPConfigSystems.phaseVectorPointCapNine;
            default: return Integer.MAX_VALUE;
        }
    }

    public static String warning(int in) {
        switch (in) {
            case 0: return SRPConfigSystems.phaseWarningZero;
            case 1: return SRPConfigSystems.phaseWarningOne;
            case 2: return SRPConfigSystems.phaseWarningTwo;
            case 3: return SRPConfigSystems.phaseWarningThree;
            case 4: return SRPConfigSystems.phaseWarningFour;
            case 5: return SRPConfigSystems.phaseWarningFive;
            case 6: return SRPConfigSystems.phaseWarningSix;
            case 7: return SRPConfigSystems.phaseWarningSeven;
            case 8: return SRPConfigSystems.phaseWarningEight;
            case 9: return SRPConfigSystems.phaseWarningNine;
            case 10: return SRPConfigSystems.phaseWarningTen;
            default: return "";
        }
    }

    public static double disloPhaseCooldown(byte in) {
        switch (in) {
            case 1: return SRPConfigSystems.phaseDisloCooldownOne;
            case 2: return SRPConfigSystems.phaseDisloCooldownTwo;
            case 3: return SRPConfigSystems.phaseDisloCooldownThree;
            case 4: return SRPConfigSystems.phaseDisloCooldownFour;
            case 5: return SRPConfigSystems.phaseDisloCooldownFive;
            case 6: return SRPConfigSystems.phaseDisloCooldownSix;
            case 7: return SRPConfigSystems.phaseDisloCooldownSeven;
            case 8: return SRPConfigSystems.phaseDisloCooldownEight;
            case 9: return SRPConfigSystems.phaseDisloCooldownNine;
            case 10: return SRPConfigSystems.phaseDisloCooldownTen;
            default: return 1.0;
        }
    }

    public static double originBonusSize(int in) {
        switch (in) {
            case 1: return SRPConfigSystems.phaseOriginBonusSizeOne;
            case 2: return SRPConfigSystems.phaseOriginBonusSizeTwo;
            case 3: return SRPConfigSystems.phaseOriginBonusSizeThree;
            case 4: return SRPConfigSystems.phaseOriginBonusSizeFour;
            case 5: return SRPConfigSystems.phaseOriginBonusSizeFive;
            case 6: return SRPConfigSystems.phaseOriginBonusSizeSix;
            case 7: return SRPConfigSystems.phaseOriginBonusSizeSeven;
            case 8: return SRPConfigSystems.phaseOriginBonusSizeEight;
            case 9: return SRPConfigSystems.phaseOriginBonusSizeNine;
            case 10: return SRPConfigSystems.phaseOriginBonusSizeTen;
            default: return 0.0;
        }
    }

    public static double originBonusHealth(int in) {
        switch (in) {
            case 1: return SRPConfigSystems.phaseOriginBonusHealthOne;
            case 2: return SRPConfigSystems.phaseOriginBonusHealthTwo;
            case 3: return SRPConfigSystems.phaseOriginBonusHealthThree;
            case 4: return SRPConfigSystems.phaseOriginBonusHealthFour;
            case 5: return SRPConfigSystems.phaseOriginBonusHealthFive;
            case 6: return SRPConfigSystems.phaseOriginBonusHealthSix;
            case 7: return SRPConfigSystems.phaseOriginBonusHealthSeven;
            case 8: return SRPConfigSystems.phaseOriginBonusHealthEight;
            case 9: return SRPConfigSystems.phaseOriginBonusHealthNine;
            case 10: return SRPConfigSystems.phaseOriginBonusHealthTen;
            default: return 0.0;
        }
    }

    public static int disloCooldown(int code) {
        switch (code) {
            case 0: return SRPConfigSystems.disloCOTHIgnoreAmpCooldown;
            case 1: return SRPConfigSystems.disloCOTHTiersCooldown;
            case 2: return SRPConfigSystems.disloSummonByDeathCooldown;
            case 3: return SRPConfigSystems.disloPotiEffCooldown;
            case 4: return SRPConfigSystems.dislostatsCooldown;
            case 5: return SRPConfigSystems.disloDeathRaidCooldown;
            case 6: return SRPConfigSystems.disloItemDuraCooldown;
            case 7: return SRPConfigSystems.disloHealingDeathCooldown;
            case 8: return SRPConfigSystems.disloDamageDeathCooldown;
            case 9: return SRPConfigSystems.disloFoodDeathCooldown;
            case 10: return SRPConfigSystems.disloDeathHighVerionsCooldown;
            case 11: return SRPConfigSystems.disloParasiteNoPotionCooldown;
            case 12: return SRPConfigSystems.disloHealthDrainingCooldown;
            case 13: return SRPConfigSystems.disloFoodDrainingCooldown;
            case 14: return SRPConfigSystems.disloNextPhaseLCooldown;
            case 15: return SRPConfigSystems.disloGrowlNoiseCooldown;
            case 16: return SRPConfigSystems.disloWalkNoiseCooldown;
            case 17: return SRPConfigSystems.disloShieldFoodCooldown;
            case 18: return SRPConfigSystems.disloLootXpCancCooldown;
            case 19: return SRPConfigSystems.disloKillcountIncCooldown;
            case 20: return SRPConfigSystems.disloGiveBodiesCooldown;
            case 21: return SRPConfigSystems.disloBurningDeathCooldown;
            case 22: return SRPConfigSystems.disloSameVersionDyeingCooldown;
            case 23: return SRPConfigSystems.disloColonyNoLimitCooldown;
            case 24: return SRPConfigSystems.disloNexusGrowthCooldown;
            case 25: return SRPConfigSystems.disloParasiteBlockCooldown;
            default: return 0;
        }
    }

    public static String disloMessage(int code, boolean start) {
        switch (code) {
            case 0: return start ? SRPConfigSystems.disloCOTHIgnoreAmpStartMess : SRPConfigSystems.disloCOTHIgnoreAmpEndMess;
            case 1: return start ? SRPConfigSystems.disloCOTHTiersStartMess : SRPConfigSystems.disloCOTHTiersEndMess;
            case 2: return start ? SRPConfigSystems.disloSummonByDeathStartMess : SRPConfigSystems.disloSummonByDeathEndMess;
            case 3: return start ? SRPConfigSystems.disloPotiEffStartMess : SRPConfigSystems.disloPotiEffEndMess;
            case 4: return start ? SRPConfigSystems.disloStatsStartMess : SRPConfigSystems.disloStatsEndMess;
            case 5: return start ? SRPConfigSystems.disloDeathRaidS : SRPConfigSystems.disloDeathRaidE;
            case 6: return start ? SRPConfigSystems.disloItemDuraS : SRPConfigSystems.disloItemDuraE;
            case 7: return start ? SRPConfigSystems.disloHealingDeathS : SRPConfigSystems.disloHealingDeathE;
            case 8: return start ? SRPConfigSystems.disloDamageDeathS : SRPConfigSystems.disloDamageDeathE;
            case 9: return start ? SRPConfigSystems.disloFoodDeathS : SRPConfigSystems.disloFoodDeathE;
            case 10: return start ? SRPConfigSystems.disloDeathHighVerionsS : SRPConfigSystems.disloDeathHighVerionsE;
            case 11: return start ? SRPConfigSystems.disloParasiteNoPotionS : SRPConfigSystems.disloParasiteNoPotionE;
            case 12: return start ? SRPConfigSystems.disloHealthDrainingS : SRPConfigSystems.disloHealthDrainingE;
            case 13: return start ? SRPConfigSystems.disloFoodDrainingS : SRPConfigSystems.disloFoodDrainingE;
            case 14: return start ? SRPConfigSystems.disloNextPhaseLS : SRPConfigSystems.disloNextPhaseLE;
            case 15: return start ? SRPConfigSystems.disloGrowlNoiseS : SRPConfigSystems.disloGrowlNoiseE;
            case 16: return start ? SRPConfigSystems.disloWalkNoiseS : SRPConfigSystems.disloWalkNoiseE;
            case 17: return start ? SRPConfigSystems.disloShieldFoodS : SRPConfigSystems.disloShieldFoodE;
            case 18: return start ? SRPConfigSystems.disloLootXpCancS : SRPConfigSystems.disloLootXpCancE;
            case 19: return start ? SRPConfigSystems.disloKillcountIncS : SRPConfigSystems.disloKillcountIncE;
            case 20: return start ? SRPConfigSystems.disloGiveBodiesS : SRPConfigSystems.disloGiveBodiesE;
            case 21: return start ? SRPConfigSystems.disloBurningDeathS : SRPConfigSystems.disloBurningDeathE;
            case 22: return start ? SRPConfigSystems.disloSameVersionDyeingS : SRPConfigSystems.disloSameVersionDyeingE;
            case 23: return start ? SRPConfigSystems.disloColonyNoLimitS : SRPConfigSystems.disloColonyNoLimitE;
            case 24: return start ? SRPConfigSystems.disloNexusGrowthS : SRPConfigSystems.disloNexusGrowthE;
            case 25: return start ? SRPConfigSystems.disloParasiteBlockS : SRPConfigSystems.disloParasiteBlockE;
            default: return "missing dislo message";
        }
    }

    // ---- config lookups that lived in the command classes of the original (SRPCommandDislodgment / SRPCommandEvolution)
    public static byte[] getDisloPhase(int id) {
        switch (id) {
            case 1: {
                return SRPConfigSystems.disloPhaseOne;
            }
            case 2: {
                return SRPConfigSystems.disloPhaseTwo;
            }
            case 3: {
                return SRPConfigSystems.disloPhaseThree;
            }
            case 4: {
                return SRPConfigSystems.disloPhaseFour;
            }
            case 5: {
                return SRPConfigSystems.disloPhaseFive;
            }
            case 6: {
                return SRPConfigSystems.disloPhaseSix;
            }
            case 7: {
                return SRPConfigSystems.disloPhaseSeven;
            }
            case 8: {
                return SRPConfigSystems.disloPhaseEight;
            }
            case 9: {
                return SRPConfigSystems.disloPhaseNine;
            }
            case 10: {
                return SRPConfigSystems.disloPhaseTen;
            }
        }
        return null;
    }

    public static int getDisloPointPrice(byte in) {
        switch (in) {
            case 0: {
                return SRPConfigSystems.disloCOTHIgnoreAmpPrice;
            }
            case 1: {
                return SRPConfigSystems.disloCOTHTiersPrice;
            }
            case 2: {
                return SRPConfigSystems.disloSummonByDeathPrice;
            }
            case 3: {
                return SRPConfigSystems.disloPotiEffPrice;
            }
            case 4: {
                return SRPConfigSystems.dislostatsPrice;
            }
            case 5: {
                return SRPConfigSystems.disloDeathRaidPrice;
            }
            case 6: {
                return SRPConfigSystems.disloItemDuraPrice;
            }
            case 7: {
                return SRPConfigSystems.disloHealingDeathPrice;
            }
            case 8: {
                return SRPConfigSystems.disloDamageDeathPrice;
            }
            case 9: {
                return SRPConfigSystems.disloFoodDeathPrice;
            }
            case 10: {
                return SRPConfigSystems.disloDeathHighVerionsPrice;
            }
            case 11: {
                return SRPConfigSystems.disloParasiteNoPotionPrice;
            }
            case 12: {
                return SRPConfigSystems.disloHealthDrainingPrice;
            }
            case 13: {
                return SRPConfigSystems.disloFoodDrainingPrice;
            }
            case 14: {
                return SRPConfigSystems.disloNextPhaseLPrice;
            }
            case 15: {
                return SRPConfigSystems.disloGrowlNoisePrice;
            }
            case 16: {
                return SRPConfigSystems.disloWalkNoisePrice;
            }
            case 17: {
                return SRPConfigSystems.disloShieldFoodPrice;
            }
            case 18: {
                return SRPConfigSystems.disloLootXpCancPrice;
            }
            case 19: {
                return SRPConfigSystems.disloKillcountIncPrice;
            }
            case 20: {
                return SRPConfigSystems.disloGiveBodiesPrice;
            }
            case 21: {
                return SRPConfigSystems.disloBurningDeathPrice;
            }
            case 22: {
                return SRPConfigSystems.disloSameVersionDyeingPrice;
            }
            case 23: {
                return SRPConfigSystems.disloColonyNoLimitPrice;
            }
            case 24: {
                return SRPConfigSystems.disloNexusGrowthPrice;
            }
            case 25: {
                return SRPConfigSystems.disloParasiteBlockPrice;
            }
        }
        return 0;
    }

    public static int getDisloDuration(byte in) {
        switch (in) {
            case 0: {
                return SRPConfigSystems.disloCOTHIgnoreAmpDuration;
            }
            case 1: {
                return SRPConfigSystems.disloCOTHTiersDuration;
            }
            case 2: {
                return SRPConfigSystems.disloSummonByDeathDuration;
            }
            case 3: {
                return SRPConfigSystems.disloPotiEffDuration;
            }
            case 4: {
                return SRPConfigSystems.dislostatsDuration;
            }
            case 5: {
                return SRPConfigSystems.disloDeathRaidDuration;
            }
            case 6: {
                return SRPConfigSystems.disloItemDuraDuration;
            }
            case 7: {
                return SRPConfigSystems.disloHealingDeathDuration;
            }
            case 8: {
                return SRPConfigSystems.disloDamageDeathDuration;
            }
            case 9: {
                return SRPConfigSystems.disloFoodDeathDuration;
            }
            case 10: {
                return SRPConfigSystems.disloDeathHighVerionsDuration;
            }
            case 11: {
                return SRPConfigSystems.disloParasiteNoPotionDuration;
            }
            case 12: {
                return SRPConfigSystems.disloHealthDrainingDuration;
            }
            case 13: {
                return SRPConfigSystems.disloFoodDrainingDuration;
            }
            case 14: {
                return SRPConfigSystems.disloNextPhaseLDuration;
            }
            case 15: {
                return SRPConfigSystems.disloGrowlNoiseDuration;
            }
            case 16: {
                return SRPConfigSystems.disloWalkNoiseDuration;
            }
            case 17: {
                return SRPConfigSystems.disloShieldFoodDuration;
            }
            case 18: {
                return SRPConfigSystems.disloLootXpCancDuration;
            }
            case 19: {
                return SRPConfigSystems.disloKillcountIncDuration;
            }
            case 20: {
                return SRPConfigSystems.disloGiveBodiesDuration;
            }
            case 21: {
                return SRPConfigSystems.disloBurningDeathDuration;
            }
            case 22: {
                return SRPConfigSystems.disloSameVersionDyeingDuration;
            }
            case 23: {
                return SRPConfigSystems.disloColonyNoLimitDuration;
            }
            case 24: {
                return SRPConfigSystems.disloNexusGrowthDuration;
            }
            case 25: {
                return SRPConfigSystems.disloParasiteBlockDuration;
            }
        }
        return 0;
    }

    public static int getDisloValue(byte in) {
        switch (in) {
            case 0: {
                return 1;
            }
            case 1: {
                return SRPConfigSystems.disloCOTHTiersValue;
            }
            case 2: {
                return SRPConfigSystems.disloSummonByDeathValue;
            }
            case 3: {
                return SRPConfigSystems.disloPotiEffValue;
            }
            case 4: {
                return SRPConfigSystems.dislostatsValue;
            }
            case 5: {
                return SRPConfigSystems.disloDeathRaidValue;
            }
            case 6: {
                return SRPConfigSystems.disloItemDuraValue;
            }
            case 7: {
                return SRPConfigSystems.disloHealingDeathValue;
            }
            case 8: {
                return SRPConfigSystems.disloDamageDeathValue;
            }
            case 9: {
                return SRPConfigSystems.disloFoodDeathValue;
            }
            case 10: {
                return SRPConfigSystems.disloDeathHighVerionsValue;
            }
            case 11: {
                return 1;
            }
            case 12: {
                return SRPConfigSystems.disloHealthDrainingValue;
            }
            case 13: {
                return SRPConfigSystems.disloFoodDrainingValue;
            }
            case 14: {
                return SRPConfigSystems.disloNextPhaseLValue;
            }
            case 15: {
                return 1;
            }
            case 16: {
                return 1;
            }
            case 17: {
                return 1;
            }
            case 18: {
                return 1;
            }
            case 19: {
                return SRPConfigSystems.disloKillcountIncValue;
            }
            case 20: {
                return 1;
            }
            case 21: {
                return 1;
            }
            case 22: {
                return SRPConfigSystems.disloSameVersionDyeingValue;
            }
            case 23: {
                return SRPConfigSystems.disloColonyNoLimitValue;
            }
            case 24: {
                return SRPConfigSystems.disloNexusGrowthValue;
            }
            case 25: {
                return SRPConfigSystems.disloParasiteBlockValue;
            }
        }
        return 0;
    }

    public static double getDisloPhaseDuration(byte in) {
        switch (in) {
            case 1: {
                return SRPConfigSystems.phaseDisloDurationOne;
            }
            case 2: {
                return SRPConfigSystems.phaseDisloDurationTwo;
            }
            case 3: {
                return SRPConfigSystems.phaseDisloDurationThree;
            }
            case 4: {
                return SRPConfigSystems.phaseDisloDurationFour;
            }
            case 5: {
                return SRPConfigSystems.phaseDisloDurationFive;
            }
            case 6: {
                return SRPConfigSystems.phaseDisloDurationSix;
            }
            case 7: {
                return SRPConfigSystems.phaseDisloDurationSeven;
            }
            case 8: {
                return SRPConfigSystems.phaseDisloDurationEight;
            }
            case 9: {
                return SRPConfigSystems.phaseDisloDurationNine;
            }
            case 10: {
                return SRPConfigSystems.phaseDisloDurationTen;
            }
        }
        return 0.0;
    }

    public static double getDisloPhaseCost(byte in) {
        switch (in) {
            case 1: {
                return SRPConfigSystems.phaseDisloPointCostOne;
            }
            case 2: {
                return SRPConfigSystems.phaseDisloPointCostTwo;
            }
            case 3: {
                return SRPConfigSystems.phaseDisloPointCostThree;
            }
            case 4: {
                return SRPConfigSystems.phaseDisloPointCostFour;
            }
            case 5: {
                return SRPConfigSystems.phaseDisloPointCostFive;
            }
            case 6: {
                return SRPConfigSystems.phaseDisloPointCostSix;
            }
            case 7: {
                return SRPConfigSystems.phaseDisloPointCostSeven;
            }
            case 8: {
                return SRPConfigSystems.phaseDisloPointCostEight;
            }
            case 9: {
                return SRPConfigSystems.phaseDisloPointCostNine;
            }
            case 10: {
                return SRPConfigSystems.phaseDisloPointCostTen;
            }
        }
        return 0.0;
    }

    public static double getDisloPhaseValue(byte in) {
        switch (in) {
            case 1: {
                return SRPConfigSystems.phaseDisloMoreValueOne;
            }
            case 2: {
                return SRPConfigSystems.phaseDisloMoreValueTwo;
            }
            case 3: {
                return SRPConfigSystems.phaseDisloMoreValueThree;
            }
            case 4: {
                return SRPConfigSystems.phaseDisloMoreValueFour;
            }
            case 5: {
                return SRPConfigSystems.phaseDisloMoreValueFive;
            }
            case 6: {
                return SRPConfigSystems.phaseDisloMoreValueSix;
            }
            case 7: {
                return SRPConfigSystems.phaseDisloMoreValueSeven;
            }
            case 8: {
                return SRPConfigSystems.phaseDisloMoreValueEight;
            }
            case 9: {
                return SRPConfigSystems.phaseDisloMoreValueNine;
            }
            case 10: {
                return SRPConfigSystems.phaseDisloMoreValueTen;
            }
        }
        return 0.0;
    }

    public static int getVectorHealthBonus(int in) {
        switch (in) {
            case -1: {
                return SRPConfigSystems.phaseVectorMultBonusMinusOne;
            }
            case 0: {
                return SRPConfigSystems.phaseVectorMultBonusZero;
            }
            case 1: {
                return SRPConfigSystems.phaseVectorMultBonusOne;
            }
            case 2: {
                return SRPConfigSystems.phaseVectorMultBonusTwo;
            }
            case 3: {
                return SRPConfigSystems.phaseVectorMultBonusThree;
            }
            case 4: {
                return SRPConfigSystems.phaseVectorMultBonusFour;
            }
            case 5: {
                return SRPConfigSystems.phaseVectorMultBonusFive;
            }
            case 6: {
                return SRPConfigSystems.phaseVectorMultBonusSix;
            }
            case 7: {
                return SRPConfigSystems.phaseVectorMultBonusSeven;
            }
            case 8: {
                return SRPConfigSystems.phaseVectorMultBonusEight;
            }
            case 9: {
                return SRPConfigSystems.phaseVectorMultBonusNine;
            }
        }
        return SRPConfigSystems.phaseVectorMultBonusTen;
    }
}
